### ISSUE TITLE
Refactor primitive type representation to make it more orthogonal

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1004]
Seems like code in https://github.com/rust-analyzer/rust-analyzer/blob/90ff3ba64133c1bcae9d49709c4dd704ae59b1ee/crates/ra_hir/src/ty/primitive.rs could be simplified by making representation more orthogonal (separating signdness, bitness and unknownness into orthogonal bits). See https://github.com/rust-analyzer/rust-analyzer/pull/485#discussion_r267503173. Might be a good idea to see how chalk handles primitive type, if they represent them at all!

**Comment by flodiebold** [comment]
I don't think Chalk represents them at all, they'd be just another `ItemId` :)

**Comment by yanchith** [comment]
I'd love to give this a try. Will post status/questions here :)

**Comment by yanchith** [comment]
Ok, started experimenting with it. This is the current representation for int types I settled upon:

```rust
#[derive(Debug, Copy, Clone, Eq, PartialEq, Hash)]
pub enum Signedness {
    Signed,
    Unsigned,
}

#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum IntBitness {
    Xsize,
    X8,
    X16,
    X32,
    X64,
    X128,
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Copy)]
pub enum UncertainIntTy {
    Unknown,
    Known(IntTy),
}

#[derive(Copy, Clone, Eq, PartialEq, Hash)]
pub struct IntTy {
    pub signedness: Signedness,
    pub bitness: IntBitness,
}
```

I (for now) kept the "unknownedness" as it was before, as part of `UncertainIntTy` so that unknown int types with `signedness` or `bitness` are not representable.  Not sure if it would be useful to have them representable.

Since `IntTy` no longer is a simple enum variant, I added convenience constructors, like `IntType::u8()`.

One thing I noticed is that the current int types implemented `Ord`, with the `{U,I}size` variants being the smallest values. I for now preserved this for the `IntBitness` enum, but is this utilized somewhere? Is it correct to be able to sort them when the `{u,i}size`s depend on the target architecture?

Also, do we want to apply analogous refactoring to float types for symmetry (modulo signedness)? Either way, expect a PR soon 🙂

**Comment by matklad** [comment]
This sounds right!

* we do need to apply the same refactoring to floats
* Ord indeed seems confusing, let's remove it and see if anything breaks? We really shouldn't rely on target platform at this layer...
* With this repr, we should be able to move `from_name`, `from_suffix` into `IntTy`, b/c these methods can't produce an uncertain ty anyway
