### ISSUE TITLE
rust-analyzer/inlayHints returns 0 when called just after RA is initialized

### ISSUE THREAD

**Issue by simrat39** [rust-analyzer/rust-analyzer#10050]
Pretty much the title. If we call rust-analyzer/inlayHints just after RA is initialized, it instantly returns 0. Only if we wait a couple of seconds do we get a normal response. 

Noticed here: https://github.com/simrat39/rust-tools.nvim/issues/57

I'm not sure if this is a neovim thingy, but i'm pretty sure that neovim returns null when there is no result (ideally the callback is not called at all), not zero.

Relevant function in rust-tools: https://github.com/simrat39/rust-tools.nvim/blob/master/lua/rust-tools/inlay_hints.lua#L93

**Comment by matklad** [comment]
Does it return a literal `0` (that is, the value of wrong type), or just some nullable valued (null or an empty array)? Assuming that it is the latter...

This is expected behavior, and one of the more "interesting" bits of the whole LSP protocol. rust-analyzer is robust and tries to provide partial service, if possible. In particular, during project loading rust-analyzer goes via three phases:

* no project info whatsoever
* got `cargo metadata` results
* compiled proc macros

If the client sends a requests during this loading phase, rust-analyzer gives the best possible results. So if you send inlay hints before project is loaded, you get only a subset of the hints (possibly even an empty subset). If you requery later, you get full hints.

The motivation here is that loading a project can take arbitrary long (it can start downloading crtes from the internet, for example), and it'd be cool to provide some kind of support while that's happening. 

Now, the problem (fundamental more or less to every LSP feature) is that there's no good way in LSP, for the server to say "hey, you've asked that info before, I gave a partial answer, now I know the full answer". 

We send some refresh requests, but here we are abusing the protocol: 

https://github.com/rust-analyzer/rust-analyzer/blob/bb1987b45e90a4f4bceabe4added1998dc0b2092/crates/rust-analyzer/src/main_loop.rs#L436-L446

We *can* do the same for inlay hints, but I would consider that a hack. 

See https://github.com/microsoft/vscode/issues/130486 for the context, and look at the dart analyzer [subscriptions](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#request_analysis.setSubscriptions) to see one principled fix for this problem. 

For rust-analyzer specifically, what you can also do is listen to the status notification:

https://github.com/rust-analyzer/rust-analyzer/blob/bb1987b45e90a4f4bceabe4added1998dc0b2092/docs/dev/lsp-extensions.md#L429

When status flips to `quiescent: true`, you'll know that you'll get the full set of results know. 


I guess, we also handle this somehow in the TS Code, but, to be honest, I don't recall how :) 
Anothe

**Comment by simrat39** [comment]
Thanks for the help. The server status stuff seems like a good enough solution for now, but it would be nice to have dartls's subscription for things like inlay hints.
