### ISSUE TITLE
Unknown types implement all traits

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#10454]
![image](https://user-images.githubusercontent.com/308347/135877181-5e5fb079-9930-49fa-b27d-e489421c0902.png)

**Comment by flodiebold** [comment]
[`iterate_method_candidates`](https://github.com/rust-analyzer/rust-analyzer/blob/5bdae82947c83fbc742ead628f4845a6933e3323/crates/hir_ty/src/method_resolution.rs#L415) should probably just return an empty result when called with a free variable.

**Comment by iDawer** [comment]
I guess this happened after #10373 ? :smile: 
I bet that here
https://github.com/rust-analyzer/rust-analyzer/blob/cf1ea9d0b9241265369b3ba869795ac9bda9f146/crates/hir/src/lib.rs#L2592-L2602
the `{error}` type gets replaced with bound variable and that may implement all(?) traits in scope. May be shouldn't call `replace_errors_with_variables` on the `{error}` type itself?

**Comment by flodiebold** [comment]
> I guess this happened after #10373 ?

Yes.

> May be shouldn't call replace_errors_with_variables on the {error} type itself?

No, that's fine. Note that the type of `x` in the example *is* a type variable originally. The problem here is just trying to do method resolution on a method receiver that's a variable, which rustc will just refuse to do.

**Comment by iDawer** [comment]
From my limited understanding Chalk treats bound vars as existentially quantified and placeholders as universally quantified, right? Since `hir_ty::replace_errors_with_variables` uses bound vars it getting ambiguous solution for queries like `exists<T> { T: AnyTrait }`.

Cant remember but I saw somewhere talking about special handling of sized bound on type vars (or errors?) on Chalk side. So could we hack it on RA side with `FromEnv({error}: Sized)`? I applied this in `hir::Type::iterate_method_candidates_dyn` and it seems solved both this and #10297 issues.

Thinking on how the hack could break, the `{error}` type will satisfy `: Sized` and `: ?Sized` bounds. Luckily, `: !Sized` bounds are impossible :smile:

**Comment by flodiebold** [comment]
Bound vars can be existentially or universally quantified, it depends on what they refer to. And no, we shouldn't add hacks for the error type; replacing the errors back with variables, which is what they were during type inference, is the correct thing to do.

**Comment by kornelski** [comment]
Please consider special-casing this for #8468 by disabling auto-imports. Auto-complete suggestions of potentially irrelevant methods isn't a big deal. However, auto-import of definitely incorrect traits that break correctly-picked inherent methods is a real problem.
