### ISSUE TITLE
Mutable binding syntax highlighting flashes too often when typing

### ISSUE THREAD

**Issue by BlackHoleFox** [rust-analyzer/rust-analyzer#10690]
I'm not sure when this started since I only started to notice it and get annoyed by it earlier yesterday but as of recently the syntax highlighting that underlines mutable bindings in VSCode has been persistently annoying. Everytime I start and stop typing, every mutable binding on my screen briefly loses its underlining. This occurs even if I'm not changing any actual code

Even weirder, it only really happens when I type two characters consecutively. Typing one, pausing, then typing another doesn't trigger it. See below:

![bfa7682f-e613-4871-bdaf-00d0edd77481](https://user-images.githubusercontent.com/20936452/140256338-a8cd6fa2-0c79-4894-9749-24073bd79549.gif)

Let me know if there's anything else I can provide, but here are my relevant versions:

rust-analyzer version: a8247685c 2021-11-04 nightly
vscode-insiders version: 1.62.0-insider b3318bc0524af3d74034b8bb8a64df0ccf35549a
OS: Win 10

**Comment by Veykril** [comment]
Can't reproduce this myself(vscode 1.16.1), this seems like either a VSCode bug to me, or maybe another extension of yours is interfering with things.

**Comment by jhgg** [comment]
I can reproduce this in a larger workspace. It appears to be related to when salsa queries get cancelled and it sends the content modified error back to vscode. Not sure if the bug is in vscode's end or not however.

**Comment by thomcc** [comment]
I have this issue, except it happens for the color of documentation comments (switching back/forth between the doc-comment and plain-comment color). I'm assuming it's the same, since they're both related to semantic highlighting.

I have some issues with photo-sensitivity triggered by flashing, and when editing a lot of documentation the flickering felt like it was starting to trigger it. I'll find a way to work around it, but a fix would be greatly appreciated, since it could be a bigger issue for someone more sensitive to this than I am.

**Comment by Veykril** [comment]
Okay I just tested it with the insiders build of VSCode(1.63.0-insider), and I can reproduce it there. So this seems to be a regression on their part as I can't reproduce it on `1.16.1`.

**Comment by Veykril** [comment]
Opened an issue on the vscode repo https://github.com/microsoft/vscode/issues/136540

**Comment by Veykril** [comment]
The issue has been fixed upstream, so I assume the next insiders build should ship with it.
