### ISSUE TITLE
Feature request: show value of constant on hover tooltip

### ISSUE THREAD

**Issue by rodrigocfd** [rust-analyzer/rust-analyzer#10783]
I don't know if it's possible or not, but here it goes.

I find myself needing to check the value of a constant quite often. It would be really handy if the value could show up in the hover tooltip:

![const val](https://user-images.githubusercontent.com/1283868/142089622-f089f4e1-afde-4b6c-b80e-91930289b510.png)

**Comment by jhgg** [comment]
I was trying to take a stab at this, since it seemed pretty *easy*, but I'm a bit stuck...

So, this is rendered by: https://github.com/rust-analyzer/rust-analyzer/blob/7776aad166760480726ee9d4692d2597dd2fa399/crates/hir/src/display.rs#L402-L414

I was thinking the aproach to grab the `0x40` might be to use the `ast_id` in `Const` (which we can expose via `ConstData` in `DefDatabase::const_data`. However, I can't figure out a way to go from `FileAstId<ast::Const>` to the actual ast node, so I can grab the body (and then stringify it.)

**Comment by jhgg** [comment]
figured it out, I think! #10785

**Comment by rodrigocfd** [comment]
That's great. Than you @jhgg.
