### ISSUE TITLE
Function's return type completion, Appeared in wrong place

### ISSUE THREAD

**Issue by nurmohammed840** [rust-analyzer/rust-analyzer#10892]
Consider this example:

```rs
fn _test(){
    0
}
```
Then if we tried code action, to add return type, It give us this output:

```rs
fn _test(){-> i32 
    0
}
```
This is happened, if there is no white space between `){ `

**Comment by Veykril** [comment]
Cause of this is the line here https://github.com/rust-analyzer/rust-analyzer/blob/2d0db312b543343f1c208b6be21a7a001cec7dd6/crates/ide_assists/src/handlers/add_return_type.rs#L73

**Comment by izik1** [comment]
Would this be a reasonable issue to claim as a "good first issue"? (the followup question being "how do I do that")

It looks fairly straight forward at first glance

**Comment by Veykril** [comment]
Ye this should be a pretty simple fix. So instead of passing the text position of the right side parentheses/pipe to `ret_ty_to_action` we should pass the SyntaxToken itself, then check if the next(right) sibling token to it is whitespace or not to determine if we need to add an offset to the position or not.
And then we probably want to conditionally add an extra whitespace to the output text if whitespace is missing so that the return type isn't touching other tokens.

**Comment by nurmohammed840** [comment]
Closing, Because Fixed: #10906
