### ISSUE TITLE
`fn` hover docs always show keyword form, even when used as primitive

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-analyzer/rust-analyzer#11036]
rust-analyzer version: db2a7087b 2021-12-13 stable

rustc 1.59.0-nightly (c5ecc1570 2021-12-15)

When you hover over the `fn` token in this code, it shows the [keyword](https://doc.rust-lang.org/std/keyword.fn.html) docs, even though the [primitive](https://doc.rust-lang.org/std/primitive.fn.html) docs actualy describe how it being used here

```rust
type Function = fn(i32) -> i32;
```

<img width="764" alt="image" src="https://user-images.githubusercontent.com/28781354/146476741-b0a28fc3-a183-4933-8415-f021281ed7f9.png">

In the case when `fn` is being used as a keyword, the hover docs are correct, and this should not be changed

<img width="645" alt="image" src="https://user-images.githubusercontent.com/28781354/146476778-727702bc-0058-42fd-b86e-4c46fba32c61.png">

**Comment by Veykril** [comment]
So the reason for this is that technically `fn` on its own doesn't address a primitive, its just part of specifying a function pointer type. Fixing this up to show the primitive docs in this case seems like a good idea nevertheless.

This is how we render hovers for builtins https://github.com/rust-analyzer/rust-analyzer/blob/f79f3db7b71b192dd2e387d2d7face7e27b3b3bd/crates/ide/src/hover/render.rs#L449-L455
and this is how we do it for keywords https://github.com/rust-analyzer/rust-analyzer/blob/f79f3db7b71b192dd2e387d2d7face7e27b3b3bd/crates/ide/src/hover/render.rs#L232-L252

Now, the `builtin` function we shouldn't change, simply because `hir::BuiltinType` doesn't encompass function pointers, so instead we should adjust the `keyword` function to check if the fn keyword is a child of a `FnPtrType` node and swap out the format string in that case.
