### ISSUE TITLE
😱😱😱 [READ THIS] VS Code Marketplace serves old version 😱😱😱

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#11098]
In Code 1.63, it appears that if you try to install the stable version from the Marketplace, you get 0.2.853 instead of 0.2.867 (the latest one). As a work-around, you can switch to the pre-release version, then downgrade to stable.

Filed https://github.com/microsoft/vscode/issues/139628 on the Code side for this.

CC #11026.

**Comment by Emerentius** [comment]
The work-around actually downgraded my version from 0.2.867 to 0.2.853 and rerunning it didn't get me back to the newer version. I'm using VS Code (1.63.2).
I ran the work-around to see if there had been a newer release since this issue was created. 

You can manually choose the version to install by right-clicking the extension and then selecting "Install different version..." (possibly worded differently). That way I got back to 0.2.867.

Example screenshot (in German).
![image](https://user-images.githubusercontent.com/9992929/147477198-87795ce0-2aac-49be-89ae-1c1148c19f14.png)

**Comment by lnicola** [comment]
There should have been a newer release, but everything runs off GitHub Actions and it's throwing a fit today.

**Comment by lnicola** [comment]
Switching to pre-release and back still works for me. And unfortunately it's still needed. I hoped that this would somehow get fixed today, but it didn't.

**Comment by LotusBlanc** [comment]
On windows, I got silently updated to 0.2.867 (displayed as up to date), I tried to switch to pre-release, then go back to release, and it displayed 0.2.853 with "reload required" but after reload rust-analyzer is v0.2.880 ^^

**Comment by jminer** [comment]
Since I'm not seeing newer versions, I just tried the workaround of switching to the pre-release version, and VS Code showed this message:

![cant-switch-to-prerelease-rust-analyzer](https://user-images.githubusercontent.com/824671/147803027-d2ea719c-7c82-4f7a-b2e7-290259202839.png)

It should be compatible, right? I don't mind sticking with the older version of rust-analyzer for now, but I thought I'd mention it. I'm using 32-bit VS Code on Windows 10 64-bit.

**Comment by lnicola** [comment]
@jminer we don't build 32-bit binaries because it seems pretty easy to go over the 3 GB of available address space. There was a workaround to download the 64-bit server on 32-bit Code because we assumed that nobody is actually using a 32-bit version of Windows. If course, this want necessarily true, but nobody complained.

Now Code itself asks for the extension that corresponds to your platform. And since there are no 32-bit builds, you get an error.

**Comment by jminer** [comment]
Thanks for the explanation. For programs that don't come close to using 2GB of memory, I try to use 32-bit programs because they use less memory than the 64-bit version. Since I build rust-analyzer's LSP server myself, is there a way for me to still use the extension with 32-bit VS Code without building the extension myself?

For unsupported platforms, I think it would be nice to have an extension build without a bundled server binary. But I don't want extra work done only for me.

(BTW, I happen to also use a 32-bit build of rust-analyzer's LSP server, and I can't remember it ever using more than 1GB of memory. On both ra's codebase and on one project with over 200 transitive dependencies, it's using less than 800MB of virtual memory.)

**Comment by lnicola** [comment]
@jminer 

> For unsupported platforms, I think it would be nice to have an extension build without a bundled server binary. But I don't want extra work done only for me.

That would be https://github.com/rust-analyzer/rust-analyzer/releases/download/2021-12-27/rust-analyzer-no-server.vsix :smile:. (thanks to @bjorn3 who made the same argument). You can also install the x64 version and set the server path in the settings. Code should probably show an error, but it currently doesn't.

> I can't remember it ever using more than 1GB of memory

That's interesting. Maybe we should also provide 32-bit binaries, then?

**Comment by jminer** [comment]
I'm glad to see it already exists. I installed the no-server vsix from the releases page, and it works for me. Thanks!

**Comment by pravic** [comment]
It looks like we are now forced to "update" RA manually via:

* Switch to Pre-Release Version
* Reload
* Switch to Release Version
* Reload

**Comment by lnicola** [comment]
Installing the extension works fine now :tada:.
