### ISSUE TITLE
Check on debounce

### ISSUE THREAD

**Issue by Milo123459** [rust-analyzer/rust-analyzer#11154]
Perhaps, if you stop typing for a period of time, it automatically runs the check command? The TS extension does this, but it does it because of how fast it can be in doing this. If it is managed to be heavily optimised, it could even run when typing.

Possibly related (on the speed side): #10149

**Comment by bjorn3** [comment]
The check command can only run after you save (manually or autosave) due to rustc only being able to read files from the disk and not from the rust-analyzer vfs. See https://github.com/rust-analyzer/rust-analyzer/issues/3107.

**Comment by lnicola** [comment]
Check runs on save, and you can configure Code to save automatically after a delay. We can't show the cargo check diagnostics without saving the files (because cargo reads them from disk) and we shouldn't save files automatically in other editors (because it's the editor's job to write the files to disk).

The cache priming is unrelated, it's just precomputing information about the symbols and exports in the project.

**Comment by Milo123459** [comment]
Ah, alright. I guess to get something like this more static analysing would need to be done. Thanks.
