### ISSUE TITLE
Renaming a module shouldn’t change path segments referring this module by `super`

### ISSUE THREAD

**Issue by EFanZh** [rust-analyzer/rust-analyzer#11289]
In the following code:

```rust
mod foo {
    struct X;

    mod bar {
        use super::X;
    }
}
```

If I rename `foo` to `baz`, the code changes into:

```rust
mod baz {
    struct X;

    mod bar {
        use baz::X;
    }
}
```

Which doesn’t compile any more.

**Comment by Veykril** [comment]
The problem here is that we forgot a check for a name-ref being `super` in which case we don't want to rename, https://github.com/rust-analyzer/rust-analyzer/blob/844c152fd1be8f0142343a095d5b45586189f435/crates/ide_db/src/rename.rs#L291-L321 and https://github.com/rust-analyzer/rust-analyzer/blob/844c152fd1be8f0142343a095d5b45586189f435/crates/ide_db/src/rename.rs#L340-L429
