### ISSUE TITLE
input Chinese comment flash in VSCode

### ISSUE THREAD

**Issue by tjx666** [rust-analyzer/rust-analyzer#11335]
https://user-images.githubusercontent.com/41773861/150691182-41664249-8c7d-4934-9d76-a1fd04c0e8ef.mov

VSCode info:

```
Version: 1.64.0-insider (Universal)
Commit: 23664355e61f3fb614932a5cb16613b4d987cfb7
Date: 2022-01-21T13:27:12.081Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)

```
rust-analyzer version: baa5cd952 2022-01-23 nightly
```

**rustc version**: (eg. output of `rustc -V`)

```
rustc 1.58.0 (02072b482 2022-01-11)
```

**Comment by tjx666** [comment]
@alexdima maybe you are fammiliar with this.

**Comment by alexdima** [comment]
@tjx666 This flashing might be caused by this code [here]( https://github.com/microsoft/vscode/blob/77a0d770031bbee4cbef7c6414ca22038ead4cba/src/vs/editor/browser/controller/textAreaHandler.ts#L658-L669) where we check that the text being composed doesn't span two distinct tokens. I'm not certain, but perhaps this is caused by syntactical tokens interacting with semantic tokens and creating for a brief moment two distinct tokens. Does this reproduce when disabling semantic tokens via `"editor.semanticHighlighting.enabled": false`?

**Comment by tjx666** [comment]
@alexdima After I disable semanticHighlighting, can't reproduce this issue.

**Comment by Veykril** [comment]
This is issue should lie with VSCode, there is nothing in r-a that would specifically flash when typing in comments as all we do is sent semantic token info over to the client.
