### ISSUE TITLE
Mark variable as `mut` when inserting `&mut ` reference

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-analyzer/rust-analyzer#11338]
https://user-images.githubusercontent.com/24700207/150756759-f3ead372-7c5d-4426-bbfc-ebb85d7e124c.mp4

It will be nice if rust-analyzer would mark `v` as `mut` (`let mut v = 0;`).

**Comment by Veykril** [comment]
We feel strongly against automagically fixing mutability of bindings, see https://github.com/rust-analyzer/rust-analyzer/issues/11084

And in this case instead of having the `add reference` diagnostic fix up the reference ***and*** the bindings mutability, we should instead show another diagnostic after applying this one, https://github.com/rust-analyzer/rust-analyzer/issues/8449
