### ISSUE TITLE
Missing info for rustc internal crates

### ISSUE THREAD

**Issue by cameron1024** [rust-analyzer/rust-analyzer#11385]
**rust-analyzer version**: rust-analyzer 17afa2e77 2022-01-24 stable

**rustc version**: rustc 1.59.0-nightly (acbe4443c 2021-12-02)

When using rustc internals (e.g. `extern crate rustc_parser`) IDE features largely seem to stop working (autocomplete, goto definition, show docs, etc). I don't know if this counts as a "bug", or if it's a missing feature, or maybe my setup is misconfigured 🤷 . FWIW I'm using the following config (using NeoVim's builtin LSP implementation):
```
{
  cargo = {
    allFeatures = true,
    loadOutDirsFromCheck = true,
  },
  checkOnSave = {
    command = "clippy"
  },
  diagnostics = {
    disabled = { "inactive-code" }
  },
}
```

I also wondered if there was an issue with "stable" RA with nightly Rust, but I this hasn't been an issue before (I assume "stable RA" means something similar to what it means in the context of "stable Rust", rather than "this version of RA only works with stable Rust"). Also apart from the rustc_* crates, everything else works great.

**Comment by bjorn3** [comment]
You need to set `rust-analyzer.rustcSource` to `"discover"` and the `Cargo.toml` needs to contain

```toml
[package.metadata.rust-analyzer]
rustc_private=true
```

for rust-analyzer. The first tells rust-analyzer to try to find the rustc source code in the rustc toolchain and the second tells rust-analyzer that the project uses rustc internal crates. The second is necessary because unconditionally loading rustc internal crates would be slow.

> (I assume "stable RA" means something similar to what it means in the context of "stable Rust", rather than "this version of RA only works with stable Rust")

Pretty much. Stable rust-analyzer should work with the latest nightly rustc most of the time.

**Comment by cameron1024** [comment]
Perfect, that fixed it, thanks for the speedy reply! 😁
