### ISSUE TITLE
Unable to find `Analysis`

### ISSUE THREAD

**Issue by jrvidal** [rust-analyzer/rust-analyzer#1151]
While dogfooding a bit I noticed that `Analysis` is never in the results of workspace symbol search. I think the culprit is:

https://github.com/rust-analyzer/rust-analyzer/blob/2fc2d4373b2c4e96bebf320a84270eee3afe34aa/crates/ra_ide_api/src/symbol_index.rs#L139-L148

I suspect `Analysis` is dropped in favor of some other candidate due to the `unicase` comparison.

Was the `unicase` thing a temporary solution, or is there a more nuanced rationale for it?

**Comment by matklad** [comment]
Oh yeah, that's the annoying bug, would be awesome to fix it! 

We use fst crate to do fuzzy search. fst stores a map from strings to u64 values. Because searching is fuzzy, we want ignore case while searching, and that means we need to lowercase identifiers. That means that we potentially need to map a single string to multiple FileSymbols, and this is the bit whihc is not implemented yet.

Now, because fst can only use u64 as keys, we store all FileSymbols in a `Vec<FileSymbol>` and use index as key in fst (see `SymbolIndex`). A naive way to support multi-maps would be to store `Vec<Vec<FileSymbol>>`, but we really don't want to do that: for symbols, we must optimize memory usage.

So I suggest the following solution: we still store a single `Vec<FileSymbol>`, which is sorted by lowercase comparator. That is, it's a sequence of clusters where consecutive elements of the cluster have equal names. In the fst, we store a "slice" of `FileSymbol` by encoding an `(usize, usize)` pair of indices into a single `u64`. To do so, we assume that the total length of `Vec<FileSymbols>` is `<= u32::max_value()` which is a reasonable assumption.

@jrvidal do you want to take a crack at this?

**Comment by jrvidal** [comment]
Yes, will do :+1:

**Comment by detrumi** [comment]
Fixed in #1200, so can be closed.
