### ISSUE TITLE
how to go to definition of hint type?

### ISSUE THREAD

**Issue by bigdogs** [rust-analyzer/rust-analyzer#11519]
Hi,

I want to jump to definition of hint type `UsageError` . when my mouse at position "a",  the blue panel is show up, But when I trying to move my mouse from position "a" to position "b", the blue panel is gone, I have no chance to go to definition of "hint" type.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/20614926/154988150-0647689a-9fd9-43d3-b61e-75c2b9a5beae.png">
What should I do to go to definition of `UsageError`

**Comment by bigdogs** [comment]
Is there possible to go to definition of hint type just with "cmd" + "click" ,  when my mouse pointer at the hint type?  (like inteijj rust? )

**Comment by SomeoneToIgnore** [comment]
Answering the latest comment's question: it is not possible now due to the hacky way our hints are implemented.

But after https://github.com/rust-analyzer/rust-analyzer/pull/11445 lands, inlay hints will be using official VSCode API which does provide a way to Cmd/Ctrl+click a reference.
Yet there has to be more work done to support it, since the migration PR does not implement it yet.

**Comment by Veykril** [comment]
Tracked in https://github.com/rust-analyzer/rust-analyzer/issues/11701
