### ISSUE TITLE
`expected literal` when using `concat_bytes`

### ISSUE THREAD

**Issue by ihciah** [rust-analyzer/rust-analyzer#11544]
**rust-analyzer version**: 1f5f4ccfb 2022-02-24 nightly

**rustc version**: rustc 1.61.0-nightly (03a8cc7df 2022-02-21)

I enable concat_bytes feature with `#![feature(concat_bytes)]`, and I generate a bytes with(I have the files in `src`):
```
concat_bytes!(
    include_bytes!("certs/tls.crt"),
    include_bytes!("certs/tls.key")
)
```
It can be successfully compiled and work. But RA shows an error `expected literal` about the related lines.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/1707505/155461543-2c5a5071-5ca9-4c95-a632-c54c21034d17.png">

**Comment by jonas-schievink** [comment]
That happens because it isn't yet implemented, so its definition is treated as a lazy macro, not an eager one. To fix it, the implementation of `concat` can probably be adjusted and added in this list:

https://github.com/rust-analyzer/rust-analyzer/blob/90f7899903238930633b8de620a12e8bfbafa8d7/crates/hir_expand/src/builtin_fn_macro.rs#L122

**Comment by ihciah** [comment]
> That happens because it isn't yet implemented, so its definition is treated as a lazy macro, not an eager one. To fix it, the implementation of `concat` can probably be adjusted and added in this list:
> 
> https://github.com/rust-analyzer/rust-analyzer/blob/90f7899903238930633b8de620a12e8bfbafa8d7/crates/hir_expand/src/builtin_fn_macro.rs#L122

Thanks, I will try to make it work :)

**Comment by jonas-schievink** [comment]
Fixed by https://github.com/rust-analyzer/rust-analyzer/pull/11549
