### ISSUE TITLE
Notebook support for upcoming LSP 3.17.0 spec

### ISSUE THREAD

**Issue by jackos** [rust-analyzer/rust-analyzer#11569]
Please see draft PR for adding Notebook support to `lsp-types` for the upcoming changes to the LSP spec:
https://github.com/gluon-lang/lsp-types/pull/229

To get this working there will need to be some extra, but very simple code generation, see here:
https://github.com/codebooknet/codebook/blob/main/src/languages/rust.ts

Would the `rust-analyzer` project be interested in merging this functionality if it doesn't affect the existing codebase, or should it be a separate fork? If there is no interest I can create a separate language server that only registers `NotebookDocumentSyncCapabilities`, but it would be preferable to have it inside `rust-analyzer`, any notebook extension in VS Code will magically get full LSP Rust support, which will make writing documentation and learning/experimenting with Rust a great user experience.

**Comment by ChayimFriedman2** [comment]
rust-analyzer requires a Cargo workspace to provide rich experience. Notebooks are usually standalone files.

That said, there might be a way to create a Cargo workspace on-the-fly or something, I'm not sure.

**Comment by bjorn3** [comment]
The only rust notebook I am aware of is evcxr which internally uses rust-analyzer for determining the types of variables to persist across notebook cells. It uses rust-analyzer as library because lsp doesn't provide the interfaces it needs. Maybe it would make sense to add support for being an lsp server to evcxr. It needs integration with evcxr anyway as evcxr changes the code you enter. Rust doesn't allow expressions at the top level so bare rust-analyzer doesn't either. Evcxr could present rust-analyzer with the actual code it is going to run and then forward the response from rust-analyzer.

**Comment by jackos** [comment]
> This means that rust-analyzer can't directly implement the notebook lsp api
My thoughts were that it's so simple to turn Notebooks into valid rust code that all notebook runners would be implementing their code generation in the same way, which would match what I implement in `rust-analyzer`

But yeah you're right, the best approach is to probably to generate the code client-side and sync that, I just need to figure out how to:

- Get VS Code to generate an intermediary file that's stored in memory not disk, and updates with each keystroke, for all the fast responses
- Get `rust-analyzer` to sync that intermediary file inside a generated workspace with a Cargo.toml
- Apply the changes that are being sent back to each notebook cell with an offset for the positions

Shouldn't be too hard, and I think more simple than all the additions that would be required in `rust-analyzer`.

Thanks for your thoughts, I'll close this issue.
