### ISSUE TITLE
Wrong inferred type in `while` and `if` with block conditions

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#11561]
```rust
fn main() {
    while { true } {}
       // ^ Expected (), got bool
}
```

**Comment by Veykril** [comment]
Ah, that is because condition is now an `Expr` node, so when it is a `BlockExpr` we actually have two `BlockExpr` children for these now which causes the `HasLoopBody::loop_body` call to return the condition instead of the body.

Similar thing I assume will happen for `if` expressions as well now.

It's the same problem I have fixed for `for` loops some time ago here https://github.com/rust-analyzer/rust-analyzer/pull/10668

**Comment by Veykril** [comment]
Problematic parts for if expressions are here
https://github.com/rust-analyzer/rust-analyzer/blob/a153b18d6d38e06db9465d616dc3b316a0c1b717/crates/syntax/src/ast/expr_ext.rs#L50-L69
https://github.com/rust-analyzer/rust-analyzer/blob/a153b18d6d38e06db9465d616dc3b316a0c1b717/crates/syntax/src/ast/generated/nodes.rs#L887

**Comment by ChayimFriedman2** [comment]
It's interesting as it's very hard to prevent this kind of issues ahead of time. Fixed syntax trees can do that, but in our current model things can break unexpectedly.
