### ISSUE TITLE
cargo watch output doesn't line up in problems pane

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1205]
`cargo-watch` support is great! I am noticing that in windows at least the problem matcher doesn't line up properly. For instance this is what shows up in the pane:

![image](https://user-images.githubusercontent.com/4325700/56681012-665cdc00-6696-11e9-949d-6a76c50ae5cb.png)

This is what shows up on hover

![image](https://user-images.githubusercontent.com/4325700/56681171-bdfb4780-6696-11e9-9b7f-0d13af104756.png)

I haven't yet looked into any font issue.

**Comment by matklad** [comment]
I belibe this is just a limitation of vs code, whihc can't us monospace font for hovers

**Comment by kjeremy** [comment]
Judging by the error message I think that the hover is correct, it's the problem area that is not.

**Comment by DJMcNab** [comment]
We might be able to make a theme to force a monospace font, although an issue in vscode might be more appropriate. Does the problem panel support markdown (we might be able to wrap it in a codeblock if so)

Just throwing ideas out - don't know if any of them will work. We could only enable this theme if cargo watch is running, maybe based on a prompt.

**Comment by edwin0cheng** [comment]
Yeah, there is no api to change the font style in Problem Panel. And in fact the api of problem panel is shared with hover. 

Here is another Idea: Currently we use `cargo check --message-format=json` and set the `rendered` output to the problems panel directly. Since the json message contains all the spans and other diagnostics, we can render it to another format which do not depends on font size.

For example , instead of this output:
```
|
274|   match.self.token_source(self.token_pos){
|         ^^^^^^^^^^^^^^^^^^^^^^^^
```

We can render this as

```
|     match.<|>self.token_source<|>(self.token_pos){
```

**Comment by DJMcNab** [comment]
In fact we could probably just not use a special format and instead use the built in secondary spans feature (whatever it is called)

**Comment by kiljacken** [comment]
We don't show the "verbose" message anymore, so this can probably be closed.
