### ISSUE TITLE
Support patch.crates-io section in Cargo.toml

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#1210]
It is nice if we support looking for source of a crate from `patch.crates-io` if present. 

Do `cargo-metadata` expose this part of information ?

**Comment by edwin0cheng** [comment]
Sorry, seem like it just works, although i have to reload the whole project.

**Comment by matklad** [comment]
yeah, it just works. The real bit that is missing though is ability to reload workspace on `Cargo.toml` changes, preferably without forgetting all of the analysis we did so far.

**Comment by flodiebold** [comment]
By the way @matklad, what do you think about editing support for `Cargo.toml`? Part of rust-analyzer or a separate crate?

**Comment by matklad** [comment]
@flodiebold I've actually already got something here: https://github.com/matklad/tom/commit/e3e6da3ffe18796bf589f76e414eaadb66c8e043

**Comment by matklad** [comment]
That's a hard question which I feel doesn't have a non-awful answer in the LSP mindset.

I like how this is solved in IntelliJ: there's a separate plugin for parsing syntax highlighting and formatting of TOML files. This plugin knows nothing about Cargo, but it does provide extension points (most notably, completion contributors)

The Rust plugin depends on the Toml plugin, and defines its Cargo.toml specific [completion contributor](https://github.com/intellij-rust/intellij-rust/blob/41b1fee24bb20a67e2fffb3ea6ebf4616d7957de/toml/src/main/kotlin/org/rust/toml/RsTomlKeysCompletionProvider.kt)

However, we can't do that in LSP: even if we ignore the IPC aspect of it, the core issues is that completion contributors export syntax trees (and, more generally, semantics of a particular) as an API, and LSP very intentionally doesn't contain semantic bits at all (which is a good thing!). So, cross-language resolve is an area where multi-language combines like IntelliJ has a significant edge over LSP-like approaches. 


Practically speaking, I'd love first to revive the `tom` library one day, port it to the latest version of rowan and provide a stand-alone language server which has specific knowledge of Cargo.toml. That should be enough to provide basic completions for dependencies, etc. 

I think I might revisit that soon by the way! Last time I've dropped work on tom, because I was unable to find a satisfactory answer for structured editing of tables, which is convenient but doesn't destroy formatting (TOML is much tougher challenge for structured editing, because you really want to edit JSON-like model, but maintain the original representation, which is completely differetn. In programming languages, model is usually much closer to syntax). However, the editing API we have now in rust-analyzer seems like a solution!

If, at some point, we need a tight integraton between toml and rust parts, we could extract toml bits as a library and serve it via language server in our process, but that seems pretty complicated.
