### ISSUE TITLE
Code Action: Go from derive to custom impl

### ISSUE THREAD

**Issue by JeanMertz** [rust-analyzer/rust-analyzer#1256]
Sometimes you have a derived `Debug` or `Default` that now requires a custom implementation. So you remove the derive, and start to impl `Default`.

It'd be nice if you could move your cursor over the derived `Default` and use some kind of "replace with impl", ready to be modified further.

**Comment by paulolieuthier** [comment]
I'll give this a try!

**Comment by paulolieuthier** [comment]
I'm having a hard time working with the ast types...

```
pub(crate) fn add_custom_impl(mut ctx: AssistCtx<impl HirDatabase>) -> Option<Assist> {
    let attr = ctx.node_at_offset::<ast::AttrInput>()?;
    ...
```

With this I can get the attribute input (the trait to be customly derived), but how can I get its "parent" (the attribute name, `derive`)?

Also, how can I install the vscode extension without optimizations? That way I can have a quicker feedback loop (how is the recommended workflow, btw)?

Thanks in advance!

**Comment by matklad** [comment]
Replied in the zulip, but let me just copy-paste info here, so that it's publically visible:


The core thing to understand for working with synatax tree efficiently is that there are two layers there.

There's a tree of SyntaxNodes, where each node has the same Rust type. In this tree, you can traverse parents, childrent, siblings, etc just fine.

There's an AST layer, where each kind of node has it's own type. This layer is more type safe, but you can't traverse it that easily.

To go from AST to SyntaxNode you use .syntax method. To go in the opposite direction, you use ast::Foo::cast familty of method.

In this case, a way to get an attr would be attr.syntax().parent().and_then(ast::Atrr::cast)?

>    also, how can i install the vscode extension without optimization?

I usually don't install without optimization. However, we have a VS Code task to laucnh both the sever and the extension in debug mode. The docs are here: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/README.md#working-with-vs-code-extension

Note that, as I don't use this feature personally, it might have bitrotted.

>    how is your workflow, btw

Building the whole server and the type script extension on top is pretty slow and a lot of moving parts. So I lean heavily on tests to check my implementation. Specifically, rust-analyzer has this feature where you can run a tests if you cursor is inside it. I use it heavily.

For assists specifically, the tests are just "apply the assist to input, check that the result matches output": https://github.com/rust-analyzer/rust-analyzer/blob/77f2dd96a122e59a8d8df8afb53a741df9b1af76/crates/ra_assists/src/assists/add_derive.rs#L51-L62.

<|> signifies cursor position

> Oh, there's a "tutorial" about syntax tree API here: https://github.com/rust-analyzer/rust-analyzer/blob/77f2dd96a122e59a8d8df8afb53a741df9b1af76/crates/ra_syntax/src/lib.rs#L177
