### ISSUE TITLE
btw, would be cool to write a `#[test] fn`  which runs `cargo gen-kinds verify`

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#126]
_Originally posted by @matklad in https://github.com/rust-analyzer/rust-analyzer/pull/110_

**Comment by mominul** [comment]
How should we implement this? Should we replicate code from `tools` crate or run `cargo gen-kinds verify` inprocess?

**Comment by aochagavia** [comment]
This could eventually be implemented on a CI level, instead of in a `#[test]`

**Comment by matklad** [comment]
We already check this during CI, but I'd love to make it so that `cargo tests` checks everything, so that CI only calls `cargo test`.

Strawman proposal: in the `tools` crate, have a 

```
tests/
  ci.rs
```

where `ci.rs` runs all non-trivial checks, like verifying that generated stuff is fresh, that the code is properly formatted (when/if we add rustfmt), that it doesn't have clippy problems (when/if we add clippy).

**Comment by mominul** [comment]
I'll be working on this issue like @matklad has pointed out.
