### ISSUE TITLE
Support .await Syntax

### ISSUE THREAD

**Issue by davidbarsky** [rust-analyzer/rust-analyzer#1263]
Hiya! I've been using rust-analyzer for the last few months  and have been _loving it_. It's a really wonderful piece of software. I'm opening this issue to track/ask for support of the `.await` syntax _with_ the understanding that y'all might not want to commit to a syntax prior to the May 23, 2019 finalization deadline.

**Comment by lnicola** [comment]
Nb. `dot.await` syntax is now final.

**Comment by flodiebold** [comment]
There's two parts to this:

#### Type inference for `x.await`
This should be very similar to #1426 to implement, just using `std::future::Future::Output` as the associated type. We just have to handle the syntax first, since `foo.await` will currently just be parsed as a field access. I don't know if it's necessary to modify the parser, or whether we should just add it to [Expr](https://github.com/rust-analyzer/rust-analyzer/blob/61135d4d4df0a16cbd39831e23b7b0deeeea44a9/crates/ra_hir/src/expr.rs#L168) and handle it during [lowering](https://github.com/rust-analyzer/rust-analyzer/blob/61135d4d4df0a16cbd39831e23b7b0deeeea44a9/crates/ra_hir/src/expr.rs#L727) (i.e. checking whether the 'field' is `await` and lowering to an `Expr::Await` instead). @matklad what do you think?

(@unrealhoang maybe you'd be interested in taking this up?)

#### Completing `.await`
For this, we need to check in [`complete_dot`](https://github.com/rust-analyzer/rust-analyzer/blob/61135d4d4df0a16cbd39831e23b7b0deeeea44a9/crates/ra_ide_api/src/completion/complete_dot.rs#L12) whether the receiver type implements `Future`, and add the `await` completion in that case. To check that, we might need to add a method to [`SourceAnalyzer`](https://github.com/rust-analyzer/rust-analyzer/blob/61135d4d4df0a16cbd39831e23b7b0deeeea44a9/crates/ra_hir/src/source_binder.rs#L376) (or maybe we can just call `db.solve` directly).

We might want to check whether we're in an async method, although on the other hand we could also always provide the completion and add the `async` when necessary. In any case, I think for a first stab not bothering about this at all would be fine :)

**Comment by unrealhoang** [comment]
I can take this, let's decide on how we will handle syntax parsing part. I think we should modify parser.

**Comment by matklad** [comment]
@unrealhoang yeah, we should modify the parser

* we need new `AWAIT_EXPR` Syntax kind (in grammar.ron)
* we also need a related ast node (in `ast` in grammar.ron)
* modify `postfix_expr` to handle `.await` the same way calls and fields are handled.

**Comment by unrealhoang** [comment]
@matklad Should this be closed with https://github.com/rust-analyzer/rust-analyzer/pull/1562 and https://github.com/rust-analyzer/rust-analyzer/pull/1558?

**Comment by flodiebold** [comment]
I think we're still missing completion for await.

**Comment by eupn** [comment]
@flodiebold how can we determine that some `receiver_ty` implements `Future` trait? Should we find all `impl` blocks in a crate for that type and look for one that implements `Future` trait or should we call `db.trait_solve(...)`? In the case of `trait_solve`, what goal should we specify then?

**Comment by flodiebold** [comment]
> Should we find all `impl` blocks in a crate for that type and look for one that implements `Future` trait or should we call `db.trait_solve(...)`?

That's what `trait_solve` is there for ;) It's not as easy as going through all impl blocks, consider impls like `impl<T> Future for T where ...`.

> In the case of `trait_solve`, what goal should we specify then?

We need a [`Trait`](https://github.com/rust-analyzer/rust-analyzer/blob/831d39b0f7ed0041cbc2fb8beb4cb375ab9652b1/crates/ra_hir/src/ty/traits.rs#L100) goal, where the trait is of course `Future`, with self type (the first parameter) `receiver_ty`. There's a similar check [during method resolution](https://github.com/rust-analyzer/rust-analyzer/blob/831d39b0f7ed0041cbc2fb8beb4cb375ab9652b1/crates/ra_hir/src/ty/method_resolution.rs#L216).
