### ISSUE TITLE
Can't find MACRO_CALL in AstIdMap

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#1264]
Running `ra_cli analysis-stats` currently often produces the above error. I can reproduce this with Chalk, Cranelift and rustc. I guess it's looking in the wrong map when nested expansions are involved? I don't know the macro machinery well enough to investigate this though.

Full error and relevant part of the stacktrace:
```
thread 'main' panicked at 'Can't find MACRO_CALL@[11; 187) in AstIdMap:
[SyntaxNodePtr { range: [0; 391), kind: MACRO_CALL }]', crates/ra_hir/src/source_id.rs:108:21
stack backtrace:
(...)
   7: ra_hir::source_id::AstIdMap::ast_id
             at /home/florian/Projekte/opensource/rust-analyzer/<::std::macros::panic macros>:8
   8: <ra_hir::expr::ExprCollector<&'a DB>>::collect_expr
             at /home/florian/Projekte/opensource/rust-analyzer/crates/ra_hir/src/expr.rs:825
```
I can try to isolate a smaller reproduction, but I don't know if it's necessary ;)

**Comment by edwin0cheng** [comment]
It maybe related to #1243, which is the only macro expanding errors when i run `ra-cli analysis-stats` on rustc code.

**Comment by edwin0cheng** [comment]
And that issues maybe fixed by swapping the orders of locals and globals:

https://github.com/rust-analyzer/rust-analyzer/blob/940c538ecf42a53e5a0e0e9ebad7267c1fe843ca/crates/ra_hir/src/nameres.rs#L275

But i am not near computer till Monday. I would investigate more about it later.

**Comment by flodiebold** [comment]
But even if we can't resolve the macro / resolve it wrongly, we shouldn't crash, right?

**Comment by matklad** [comment]
I guess, we need to be just more principled with macro resolution....

Specifically:

* instead of just "public macros" in DefMap, we should introduce proper macro scopes
* inside Bodies, properly add stuff from macro-generated files to source map (I wonder if we can avoid storing an HitFileId for each expr)
* take a calling context into account when expanding macro to item/expr/pattern etc

I've sort of punted on that for the time being in the hope that "name resolution librarification" effort deals with all these in a principled way, but the effort is stalled :(

**Comment by matklad** [comment]
Heh, I actually was trying to fix this bug in https://github.com/rust-analyzer/rust-analyzer/commit/594aac059e1f8c15a7c856e2778b0c4ff2a240aa#diff-874c3972fedd96a674824aaf3f448d98, and the fix was incomplete

**Comment by edwin0cheng** [comment]
>But even if we can't resolve the macro / resolve it wrongly, we shouldn't crash, right? 

Yes you are right, I just checked #1243  is not the reason of the assert. :(

**Comment by matklad** [comment]
Now analysis doesn't crash for chalk.

For rustc, it hangs inside chalk
