### ISSUE TITLE
ra_lsp_server doesn't get shut down and requires a lot of RAM

### ISSUE THREAD

**Issue by Matthias247** [rust-analyzer/rust-analyzer#1292]
I had several occasions where VsCode was already closed, but the rust-analyzer process still stuck around and required >= 2GB RAM on my machine.

Maybe there is an issue which prevents it from a clean shutdown, and VsCode doesn't care. But on the other hand, if it's a real child process, shouldn't it always be terminated?

Maybe related, maybe some other issue: Before this happened I sometimes could edit in the editor anymore (e.g. pressing the "Enter" key did nothing). Maybe that was also due to the LSP process being unresponsive?

**Comment by matklad** [comment]
This could be
https://github.com/microsoft/vscode-languageserver-node/issues/484

**Comment by matklad** [comment]
>Maybe related, maybe some other issue: Before this happened I sometimes could edit in the editor anymore (e.g. pressing the "Enter" key did nothing). Maybe that was also due to the LSP process being unresponsive?

I think that is due to recent problems with chalk taking exponential time to solve queries. We've papared over this issue yesterday, so ra-lsp should be responsive know.

Let's close the issue with the following conclusion:

* process stick around -- problem on the VS Code side
* huge ram usage -- that's a known issue, the solution here is to basically use less ram, it's just little effort has been into this issue so far
* hanging (and 100% CPU usage) -- fixed recently!

**Comment by Matthias247** [comment]
Seems fair. I will try a newer revision
