### ISSUE TITLE
Run Test hover not working

### ISSUE THREAD

**Issue by radu-matei** [rust-analyzer/rust-analyzer#1423]
For all tests, there is a hover provider registered that enables to run the specific - however, that for some reason it currently fails.
On top of that, I haven't actually found where that is implemented, which is peculiar. Any pointers here?

![image](https://user-images.githubusercontent.com/13103165/59960183-0f745700-94cd-11e9-9313-e25692dfe387.png)

Of course, running the test command manually succeeds:
```
$ cargo test --package libcnab --lib -- test_bundle_from_file_not_found --nocapture
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running target/debug/deps/libcnab-1bbabf1758c0b6a2

running 1 test
test tests::test_bundle_from_file_not_found ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 8 filtered out
```

Thanks!

**Comment by lnicola** [comment]
It works for me. The `execvp` sounds like it can't find `cargo`. Are you using Windows or Unix, and does `cargo` work in the integrated terminal of VS Code?

**Comment by radu-matei** [comment]
Everything else works fine - it might as well be a VS Code config error on my side.

**Comment by lnicola** [comment]
So it looks like the command line is built by RA, then passed via LSP to be executed by Code. Can you check the environment of the Code processes to see whether `PATH` is set correctly? On Linux you can look into `/proc/PID/environ`, at least.

I'm running `cargo` from a system-wide location, but I've had issues before with this. I'm adding `~/.cargo/bin` to `PATH` in my shell's config, but Code doesn't iherit that because it's not started from the shell, and fails to spawn RA because of it.

**Comment by matklad** [comment]
The entry point for server-side implementation is here:

https://github.com/rust-analyzer/rust-analyzer/blob/7d79be32801036c39507fe96f87ed316e3934662/crates/ra_lsp_server/src/main_loop/handlers.rs#L718-L749

The client side is here:

https://github.com/rust-analyzer/rust-analyzer/blob/7d79be32801036c39507fe96f87ed316e3934662/editors/code/src/commands/runnables.ts

Judging by the screenshot, it indeed looks the problem is on the client-side, basically, what @lnicola is saying

**Comment by lnicola** [comment]
@matklad by the way, can we expand `~` and `~user` in `rust-analyzer.raLspServerPath`? I had to make a symlink under `/usr/local/bin` to be able to run RA.

**Comment by matklad** [comment]
Yeah, sure we should expand `~`.

**Comment by edwin0cheng** [comment]
This one can be closed, right?

**Comment by lnicola** [comment]
I think we have a couple of "we should look for `cargo` in known paths" issues open.
