### ISSUE TITLE
Too many "Rust file outside current workspace is not supported yet"

### ISSUE THREAD

**Issue by Dushistov** [rust-analyzer/rust-analyzer#1521]
I time to time edit files in emacs that not belong to workspace.
Actually they belong to workspace, but rust-analyzer can not understand it (they are processed by build.rs).

And during editing of this files it is impossible to use editor, because of "Rust file outside current workspace is not supported yet" spams every seconds, and mini buffer show only this message, it is impossible to search inside file for example, find and replace, run command via M-x and so and so on.

May be it is possible to report "Rust file outside current workspace is not supported yet" once per file ?

**Comment by Timmmm** [comment]
This also happens if you add a rust folder to a workspace. So it really *is* in the workspace but rust-analyzer doesn't realise until you reload VSCode.

**Comment by RReverser** [comment]
In VSCode this prevents even basic editing of file, too - for example, while I can type some characters, I can't put in a newline, because it only results in more errors and fails.

**Comment by suhr** [comment]
It would be nice to have an option to disable RA outside a workspace.

**Comment by RReverser** [comment]
Please fix this - at least giving an option to not show these as errors would be nice. Right now it triggers on every single command, and due to severity of message Output window opens over and over again.

This is what the experience using RA on files looks like right now (sorry for the poor quality, Github doesn't allow either large files nor MP4):

![D8149819-319B-46CB-9C96-B05F991CCD47](https://user-images.githubusercontent.com/557590/76081812-d9ff9300-5fa1-11ea-9d66-d2341414bbe2.GIF)

**Comment by matklad** [comment]
Pushed the work-around in https://github.com/rust-analyzer/rust-analyzer/pull/3526. 

Hope to fix this properly sonish, but it'll require a pretty significant refactoring of internals.

**Comment by RReverser** [comment]
@matklad Thank you!

**Comment by virtualritz** [comment]
Since today I get this all the time in VSC:
```
Error: LspError { code: -32900, message: "Rust file outside current workspace is not supported yet." }
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"[Info  - 8:06:39 PM] Connection to server got closed. Server will restart.
[Error - 8:06:39 PM] Request textDocument/semanticTokens/range failed.
Error: Connection got disposed.
[...]
```

I am never setting a workspace and didn't have issues with this at all since I switched from RLS to RA a few weeks ago. Everything just worked.

I switched RA to the nightly build just now in hope that will help but no luck. The messages keep persisting. When this happens RA keeps hanging on the last package in the status line (eg. showing `rust-analyzer: 3/261` and spinning on that package no. 3 forever).
Saving often brings the popup that it is running rust formatter that then also hangs and means the save is not happening. All this started today.
