### ISSUE TITLE
Compiling ra_hir fails due to missing field in TraitFlags

### ISSUE THREAD

**Issue by ElusiveMori** [rust-analyzer/rust-analyzer#1531]
Tried to install rust-analyzer on my fresh linux install, but ran into this:

```
error[E0063]: missing field `non_enumerable` in initializer of `chalk_rust_ir::TraitFlags`
   --> crates/ra_hir/src/ty/traits/chalk.rs:462:20
    |
462 |             flags: chalk_rust_ir::TraitFlags {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^ missing `non_enumerable`

error[E0063]: missing field `non_enumerable` in initializer of `chalk_rust_ir::TraitFlags`
   --> crates/ra_hir/src/ty/traits/chalk.rs:476:17
    |
476 |     let flags = chalk_rust_ir::TraitFlags {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^ missing `non_enumerable`
```

No clue why this happens, I compiled rust-analyzer a week back and it was totally fine. The commit that changed TraitFlags in Chalk was around a month ago.

This is my current rustc:
```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.38.0-nightly (69656fa4c 2019-07-13)
```

Anyone got any idea?

**Comment by flodiebold** [comment]
I updated my Chalk branch to include the latest master, but didn't PR the cargo update here yet. I was assuming this wouldn't be a problem because of the lock file, but because I force-pushed to the branch, of course anyone who hasn't cloned it before will not get the locked commit, which I didn't keep in mind. #1532 should fix compilation, sorry.

**Comment by ElusiveMori** [comment]
Switching to your branch fixed it! Thanks!

**Comment by kjeremy** [comment]
I think this can be closed now.
