### ISSUE TITLE
Inlay hints update too fast

### ISSUE THREAD

**Issue by davyzhang** [rust-analyzer/rust-analyzer#1607]
It's a very good feature but currently, it changes too fast with every keystroke backing to {unknown}. If it can stay as where they are and update when ready, that would be much nicer to use.

**Comment by SomeoneToIgnore** [comment]
I've managed reproduce the issue by typing really fast (guess that's what you've meant under `it changes too fast with every keystroke`), nice catch.

I think I've fixed it in https://github.com/rust-analyzer/rust-analyzer/pull/1610/ , give it a try.

**Comment by matklad** [comment]
I wonder if we can also avoid updating type hints on the *current* line while the user is typing...

**Comment by SomeoneToIgnore** [comment]
I'm a bit uncertain about it.

First of all, I see a single method in the VS Code api that allows updating decorations — `setDecorations`.
If this is the only method truly, we need to have a custom logic that stores and updates the collection of hints on the client for each file to emulate the non-updated decorations.

Then, as far as I understand, this won't reduce the number of the server requests, since the client cannot predict if the change alters any other types in the file (it can, for instance, in the long chain of closures: you update `map` body and the parameter type of the following closures may change).

We also need to keep in mind edge cases such as multiple type parameters on a single line: multiple lambdas [(RA example)](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_lsp_server/src/main_loop/handlers.rs#L64), destructuring usage etc.
There we should update the line, even though the user types something.

Last, but not the least, current code updates very fast and smooth, looks nice to me :)
