### ISSUE TITLE
Add handling for no_std crate panic_handler definition

### ISSUE THREAD

**Issue by Dhs92** [rust-analyzer/rust-analyzer#1626]
Currently, ra will mark a user-definition of `panic` in a `no_std` crate as a redefinition of the `std` function.
![image](https://user-images.githubusercontent.com/3068714/62148571-d474f880-b2ae-11e9-9b53-923a006155e8.png)

**Comment by matklad** [comment]
I think this comes from `cargo check` and nor from rust-analyzer proper

**Comment by Dhs92** [comment]
Manually running `cargo check` does not yield the same results

**Comment by AlphaModder** [comment]
Is it possible this is related to or equivalent to [this issue that occurs without ra at all?](https://github.com/rust-lang/rls/issues/904)

**Comment by mgostIH** [comment]
Is this issue totally dead? It's quite a problem whenever one has to work with no_std, even a manual solution to turn off the error would be enough

**Comment by flodiebold** [comment]
The error comes from `cargo check`. If you can't reproduce it by running in the command line, it's likely because you're not running it in the command line with the same parameters. Try checking whether you have `checkOnSave.allTargets`, `checkOnSave.allFeatures` or `checkOnSave.features` enabled, and running it in the command line with the corresponding parameters (or disabling them in the rust-analyzer settings).

**Comment by mgostIH** [comment]
@flodiebold Thanks! Disabling checkOnSave.allTargets removed the error being displayed

**Comment by Dhs92** [comment]
Can this issue be closed now?

**Comment by flodiebold** [comment]
I'd say so.
