### ISSUE TITLE
Code: Use fs wrappers

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1670]
I'm not sure if RA will work in the remote mode, but it might be worth using `vscode.workspace.fs`: https://code.visualstudio.com/updates/v1_37#_vscodeworkspacefs.

I think the only methods are `fs.readFileSync` (in a test) and `fs.existsSync` (for `cargo watch`).

**Comment by DJMcNab** [comment]
Basically, using this API would be difficult because there is no support for it in the LSP, and would be close to useless because we can't run `cargo metadata` using it.

<details> <summary>More detail</summary>
I don't think that API is not about the remote mode - it is instead about running the extension using contributed file systems, such as those provided by the SSH and WSL remote development extensions or for FTP. This is not yet supported over the LSP (see for example https://github.com/microsoft/language-server-protocol/issues/809 and https://github.com/microsoft/vscode-languageserver-node/issues/1).

The tests will always be running locally, so the `readFileSync` in the test is fine. The `existsSync` for `cargo watch` should not be updated to use `vscode.workspace.fs`, because there is no way to run `cargo watch` on the server anyway. Additionally, since we can't run `cargo metadata` on a remote filesystem, we cannot get that information (unless we can compile cargo to WASM, which is a whole other kettle of fish). The only thing this would allow would be completions/go to definition etc. of items inside a single crate (with no information on external crates or `std`).

rust-analyzer itself would work fine in a remote development context if the remote server had ra_lsp_server installed, at least assuming that the remote doesn't use a contributed file system.
</details>

**Comment by bjorn3** [comment]
> can't run cargo metadata on a remote filesystem

Except using FUSE :)

**Comment by matklad** [comment]
I think there's no reason to *not* use Code's fs in the TypeScript extension

**Comment by DJMcNab** [comment]
I think the PR to fix this would be a single line diff - probably not E-medium :p
