### ISSUE TITLE
Auto-complete doesn't work with Arc (Deref)

### ISSUE THREAD

**Issue by cynecx** [rust-analyzer/rust-analyzer#1709]
Test-case:

```rust
use std::ops::Deref;
use std::sync::Arc;

struct Foo {
    a: u32,
}

impl Foo {
    fn bar(&self, a: u32) {
        println!("nights");
    }
}

struct Ref<'a, T> {
    obj: &'a T,
}

impl<'a, T> Deref for Ref<'a, T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        self.obj
    }
}

fn main() {
    let a = Arc::new(Ref { obj: &Foo { a: 8u32 } });
    a.<|>; // should show completions for `bar(&self, u32)` and `a`
}
```

rust-analyzer: `c7d37e424f1e04f87982233f97e1e9385191b7f1`

**Comment by flodiebold** [comment]
Hm, you're right, and I'm pretty sure it used to work. I'll have to investigate this.

Or if someone else wants to look into it:
I'd probably start by creating a very small test project to reproduce this, basically just
```rust
use std::sync::Arc;

fn foo(x: Arc<u32>) {
    let y = *x;
}
```
and then running `RUST_LOG=ra_hir::ty::traits=debug CHALK_DEBUG=1 ra_cli analysis-stats` on it. This should produce a lot of logs and might start giving a clue. It might/probably will be necessary to add some more logging to find out whether the `Deref` implementation of `Arc` is found correctly, and to make more sense of the Chalk logs (Chalk currently only uses IDs).

**Comment by flodiebold** [comment]
Ah, found it -- I think the problem is the `?Sized` bound on the impl, which we used to ignore because we had a hardcoded blacklist of traits that caused performance problems, but we removed that since the floundering improvements in Chalk fixed most of those performance problems. The problem is that we don't even lower the `?Sized` bound correctly (i.e. we ignore the `?` completely). For now, we should probably ignore `Sized` and `?Sized` bounds completely.
