### ISSUE TITLE
Missing `assert_eq` suggestion

### ISSUE THREAD

**Issue by max-sixty** [rust-analyzer/rust-analyzer#1727]
I don't get any suggestions for `assert_eq`. This was a completely blank project and I tried restarting rust-analyzer. 

These are the only `as*` suggestions I see:

<img width="138" alt="image" src="https://user-images.githubusercontent.com/5635139/63560861-aee1b480-c525-11e9-8e37-e40920fa538a.png">

Ref https://github.com/rust-analyzer/rust-analyzer/issues/1710 re posting these

**Comment by flodiebold** [comment]
Related to #1688

**Comment by matklad** [comment]
I think we have these macros in the global macro scope when we run `nameres/collect`. However, it's not super clear how to expose this to completion infrastructure properly. 

The problem is, that the global macro scope is a mutable map, which is cleared after we have processed the crate. We  could record snapshots of the map as we process the crate, but that would put an IDE specific concern into the compiler. A more clean separation would be to just traverse the crate in dfs order up to completion point in the ide, collecting macros along the way. This would duplicate nameres logic in IDE though. 

A nice short-term 80% solution would be to only process macros from `#[macro_use] extern crate`, which covers all std macros: for such macros, we already maintain the `exported_macros` table, and IDE can just look into it.
