### ISSUE TITLE
Assist: Apply De Morgan's law

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1807]
Input (cursor's on `||`)

```rust
subtree.delimiter != tt::Delimiter::None || !subtree.token_trees.is_empty()
```

Output

```rust
!(subtree.delimiter == tt::Delimiter::None && subtree.token_trees.is_empty())
```

See https://github.com/rust-analyzer/rust-analyzer/pull/1761 for the recent example of new assits

**Comment by p-avital** [comment]
If we're gonna have it on `||`, why not have it on `&&` too ? It's practically identical, might as well treat both cases at once.

Input (cursor's on `&&`)
```rust
subtree.delimiter != tt::Delimiter::None && !subtree.token_trees.is_empty()
```
Output
```rust
!(subtree.delimiter == tt::Delimiter::None || subtree.token_trees.is_empty())
```

**Comment by matklad** [comment]
Sure, it should work both ways!

**Comment by p-avital** [comment]
Should the assist work with any type, or just with `bool`.
After all, it only really applies to boolean algebra. I think there are already assists with deep enough insight into typing to check for that.

Should there be equivalent assists for bitwise operations ?
Although I may be complicating the issue too much by expanding it this much, probably better to keep it to the boolean operations so that it doesn't spiral for a first issue.

**Comment by matklad** [comment]
`&&` and `||` work only for `bool`, it's impossible to override them. 

I don't think bitwise version would be very useful, I suggest adding it when someone actually asks for it

**Comment by cronokirby** [comment]
I've started working on this, but could use a little help.
