### ISSUE TITLE
Mod vs type name conflict

### ISSUE THREAD

**Issue by sinkuu** [rust-analyzer/rust-analyzer#1905]
```rust
mod str {
}

fn foo() -> &'static str {
    ""
}

fn main() {
    let t = foo();
}
```

rust-analyzer cannot resolve `str` in the return type to the primitive `str`. This breaks type inference for `String::as_str` in liballoc, which has `str` module.

**Comment by edwin0cheng** [comment]
@flodiebold After #2455 landed, The above code is fixed now. However, the following code is failed: 
```rust
use std::u32;

fn main() {
    let _s = u32::max(0, 1);  // _s = {unknown}
}
```

It is because when resolving `u32::max`, we use the following code to resolve the path:
https://github.com/rust-analyzer/rust-analyzer/blob/9712889ee4c6cffa37c2ace5da9b00bf29adab56/crates/ra_hir_ty/src/lower.rs#L199-L224

Even if we want to change the name resolution code to a specific shadow mode in this function, it seems we don't have enough information to decide which one to choose, right?

**Comment by edwin0cheng** [comment]
Sorry, I misunderstand the code I mentioned before, It seem to be unrelated. I am trying to dig more now.

**Comment by edwin0cheng** [comment]
Um.. I finally under what actually happen. I just tried, this issue is fixed by #2455.  
However, for example the following code will not work: 

```rust
use std::u32;

fn main() {
    let s = u32::MAX; // Expect u32 as mod
    let t = u32::max(0,1); // Expect u32 as type    
}
```

It seem like we can't decide which mode to choose only by the path. And the case here is quite complicated. The `u32::Max` is from trait `Ord`, which means we can't get the result by simply test which path is resolvable. (i.e. `resolve(Mode::Module).or_else(||resolve(Mode::Other))`).

**Comment by flodiebold** [comment]
I would guess that path resolution needs to actually go back and look whether the last resolved segment can be resolved as a type if the path cannot be fully resolved. I.e. `u32::MAX` resolves fully, so that's fine; for `u32::max`, once `max` is not found in the module, before returning the incomplete resolution, we'd need to check whether the previous segment resolved as a type.

**Comment by flodiebold** [comment]
Of course, it'd also be a good idea to take a look at the logic in rustc, which I don't know off the top of my head ;)

**Comment by edwin0cheng** [comment]
> I would guess that path resolution needs to actually go back and look whether the last resolved segment can be resolved as a type if the path cannot be fully resolved. I.e. `u32::MAX` resolves fully, so that's fine; for `u32::max`, once `max` is not found in the module, before returning the incomplete resolution, we'd need to check whether the previous segment resolved as a type.

Here what rustc do:

https://github.com/rust-lang/rust/blob/f5c81e0a986e4285d3d0fd781a1bd475753eb12c/src/librustc_resolve/late.rs#L1737-L1756

```rust
// In `a(::assoc_item)*` `a` cannot be a module. If `a` does resolve to a module we
// don't report an error right away, but try to fallback to a primitive type.
// So, we are still able to successfully resolve something like
//
// use std::u8; // bring module u8 in scope
// fn f() -> u8 { // OK, resolves to primitive u8, not to std::u8
//     u8::max_value() // OK, resolves to associated function <u8>::max_value,
//                     // not to non-existent std::u8::max_value
// }
//
// Such behavior is required for backward compatibility.
// The same fallback is used when `a` resolves to nothing.
PathResult::Module(ModuleOrUniformRoot::Module(_)) |
PathResult::Failed { .. }
        if (ns == TypeNS || path.len() > 1) &&
           self.r.primitive_type_table.primitive_types
               .contains_key(&path[0].ident.name) => {
    let prim = self.r.primitive_type_table.primitive_types[&path[0].ident.name];
    PartialRes::with_unresolved_segments(Res::PrimTy(prim), path.len() - 1)
}
```

So basically it is what you described :)
