### ISSUE TITLE
Add impl members doesn't qualify types

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1943]
Consider this code:

```rust
impl std::fmt::Display for Foo {}
```

The add missing impl members action will turn it into:

```rust
impl std::fmt::Display for Foo {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result { unimplemented!() }
}
```

An unsuspecting user might think the `Result` is the prelude `Result` instead of `std::fmt::Result`.

**Comment by flodiebold** [comment]
Yeah, this is a problem in general (e.g. for the 'fill match arms' action as well). We need to have a general way of writing types such that they resolve from that location (but ideally otherwise keep type aliases etc. from the definition).

**Comment by flodiebold** [comment]
For this code action in particular, we also need to substitute type parameters.

**Comment by flodiebold** [comment]
My general idea for this was to somehow track where a type was explicitly referred to when doing type lowering and inference, and then build the signature from the lowered types, with the help of that information. Not sure how hard that will be though.

**Comment by matklad** [comment]
I feel that aliases and use paths should be handled pretty differently. For aliases, we should track them during type-inference explicitly. [This post](https://medium.com/@slavapestov/the-secret-life-of-types-in-swift-ff83c3c000a5) touches a bit on how Swift does this, not sure what is implemented in rustc.  

For paths, we can't really make use of the paths at def-site, because they usually use imports. 

Rather, for every `Def` we should have a `canonicalUsePath(self, db: &impl DB) -> hir::Path` which heuristically figures out the best path for import, taking facades, visibility and re-exports into account.

For the first step, we should just use these canonicalPaths, but, ideally, this should be integrated with auto-import. Here's the relevant code from IntelliJRust: https://github.com/intellij-rust/intellij-rust/blob/d23e13f8a7a9424795e9072f9806e2cbbb997989/src/main/kotlin/org/rust/ide/inspections/import/RsImportHelper.kt#L26-L34

**Comment by Diggsey** [comment]
Maybe a first step could be to add a "import into module" refactor.

In the code `f: &mut std::fmt::Formatter` you could right-click on the word `fmt` and the refactor option would add `use std::fmt;` to the top of the module, whilst also replacing all uses of `std::fmt` with just `fmt`.

Then it would be fine for generated code to start with fully qualified paths for all types not already in scope.

**Comment by matklad** [comment]
>In the code f: &mut std::fmt::Formatter you could right-click on the word fmt and the refactor option would add use std::fmt; to the top of the module,

This already exists

>whilst also replacing all uses of std::fmt with just fmt.

And this is not implemented yet, although should be doable with the current infra

**Comment by Diggsey** [comment]
> This already exists

It does? I checked before I left that comment and I couldn't find a way to do that :/

**Comment by matklad** [comment]
@Diggsey it works like this: https://youtu.be/Frr-3crs-4w. docced here: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/assists.md#add_import
