### ISSUE TITLE
Provide option to synchronize logging?

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#206]
Looking at logs output via RUST_LOG variable can be tricky due to multi-threading. Maybe it would be possible to synchronize output?

**Comment by aochagavia** [comment]
How would this work conceptually? Maybe you could group the messages by thread and dump them all at once once in a while? Or do you have a different approach in mind?

**Comment by kjeremy** [comment]
I'm not sure yet. I was just trying to debug something and it was a problem.

**Comment by matklad** [comment]
I feel like this is a not too actionable feature: everything about rust-analyzer and lsp is concurrent, so it's just the nature of the problem that all the stuff happens at the same time. 

Perhaps we could investigate some sort of "structured" logging, so that every action is tagged with the source request/notification id which triggered the action, but this seems a relatively complex thing to do... So, closing for now!

**Comment by DJMcNab** [comment]
I'm working on improving our logging (we already have #302 for example, which gives us some very useful logs). However, these could be more useful once the story around https://github.com/Microsoft/vscode-languageserver-node/pull/444 is worked out.
