### ISSUE TITLE
rustfmt fail (>Format Document) with async syntax (wrong edition)

### ISSUE THREAD

**Issue by Speedy37** [rust-analyzer/rust-analyzer#2146]
Typing edition 2018 syntax like:

```rust
async fn test() {
    0;
}
```

Makes the formatting to fail with:
```
error[E0670]: `async fn` is not permitted in the 2015 edition
  --> <stdin>:25:1
   |
25 | async fn test() {
   | ^^^^^
```

In handlers.rs:547, rustfmt is started without an edition provided.
A workaround is to set the edition in rustfmt config file.
But I think rust-analyser should know the current edition, and provide it when running rustfmt

**Comment by matklad** [comment]
We run `rustfmt` as an external process, and I feel this is out of scope for the current implementation. Once we use `rustfmt` as a library (which won't be any time soon), we should make sure to pass the proper edition. For the time being, it seems like it might be a good idea for `rustfmt` to fetch edition from Cargo.toml? Otherwise, every project would have to use a dummy `rustfmt.toml` which sets an edition, which seems not really necessary from the user's POW.

**Comment by matklad** [comment]
OTOH, I'll accept a PR which papers over this specific issue :)

**Comment by Speedy37** [comment]
I've a local patch that add --edition 2018 to the command would you accept that?

**Comment by matklad** [comment]
>I've a local patch that add --edition 2018 to the command would you accept that?

Just adding `--edition 2018` would be wrong, b/c edition *could* be `2015`. We need to check to which crate the current file belongs, and only pass this option if it matches `Cargo.toml`
