### ISSUE TITLE
Box<{unknown}> when using ? sigil with rawsock function

### ISSUE THREAD

**Issue by fasterthanlime** [rust-analyzer/rust-analyzer#2168]
I tried finding a more minimal test case but this is the best I could do right now:

![image](https://user-images.githubusercontent.com/7998310/68086926-16cf4800-fe51-11e9-93a1-677376a02f54.png)

The signature of `rawsock::open_best_library` isn't particularly fishy:

```rust
pub fn open_best_library() -> Result<Box<dyn Library>, Error> { /* ... */ }
```

(`Error` there is `rawsock::common::err::Error` and `Library` is `rawsock::traits::Library`)

Repository for repro: https://github.com/fasterthanlime/ra-box-issue

I'm seeing this on Windows 10 x64, Rust 1.38.0 stable, rust-analyzer @ 5d96ade59484927e7e590b64e2846ab409bbe63b

Let me know if there's any way I can help.

**Comment by flodiebold** [comment]
This is because the associated type projection for the `?` operator goes through Chalk, which doesn't support dyn/impl Trait types yet; or rather, the support is too buggy at the moment, so when such a type goes through Chalk, it turns to `Unknown`. Once the Chalk support works, fixing this will be trivial on the RA side.

**Comment by fasterthanlime** [comment]
So this is actually a chalk issue? Do you want it keep this issue open for tracking or is it covered by some other issue?

Also, was there a point where RA didn't depend on chalk for those? It feels like it "worked" a few weeks/months ago, but bisecting sounds lengthy from my end! I'd be fine with reverting to an older revision for the time being.

**Comment by flodiebold** [comment]
It's not directly a Chalk bug -- rather, we avoid passing `dyn Foo` to Chalk because that would break other things, so we turn the `dyn Foo` into `{unknown}`. We can keep this open until we fix that.

> Also, was there a point where RA didn't depend on chalk for those?

Hmm, we _might_ have had a workaround for the `?` operator before we implemented it properly using Chalk. I wouldn't really recommend going back so far though; a _lot_ of stuff has improved since then ;)

**Comment by flodiebold** [comment]
Basically, #2030 would fix this, but as you can see, it breaks other tests because of crashes in Chalk.

**Comment by flodiebold** [comment]
@fasterthanlime Please try again with current master, I'd guess this should work now.

**Comment by fasterthanlime** [comment]
Works great as of 2d32e6ba30fc793eb9fc77d6feeed27ddbff77bb !

![image](https://user-images.githubusercontent.com/7998310/69009797-6df91080-0959-11ea-9048-994dbca867ef.png)

Thanks for the update and all the hard work 💙
