### ISSUE TITLE
Windows: have to regenerate grammar

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2184]
I keep running into the "grammar is not fresh" issue on windows again. I know I saw some PRs floating around with line endings.

**Comment by edwin0cheng** [comment]
On the other hand, even changing to write preamble before reformatting will not work here. Since the default option of `rustfmt` line-ending is "Auto", which means the line-ending is guessed by the first line of input, is `LF` in our case. 

So to prevent all these annoying things, the ultimate solution is forcing `LF` in `.gitattribute` **AND** setting the `rustfmt` line-ending to LF too.

**Comment by kjeremy** [comment]
> So to prevent all these annoying things, the ultimate solution is forcing `LF` in `.gitattribute` **AND** setting the `rustfmt` line-ending to LF too.

I think that's the right approach.

**Comment by matklad** [comment]
Gosh, I feel we should just switch to U+2028 /s

I think another alternative might work: just be more lax about whether the file is fresh or not in our codegen.

**Comment by kjeremy** [comment]
When I go to commit the regened files the line endings are different so I
think we still need a gitattributes change.

**Comment by matklad** [comment]
I *think* that with autocrlf enabled, committed files should contain `\n` line endings.
