### ISSUE TITLE
Cannot start new line from the end of a comment

### ISSUE THREAD

**Issue by aochagavia** [rust-analyzer/rust-analyzer#219]
To reproduce, start writing a comment like the one below and press enter.

```rust
// <|>
```

Expected behavior:

```rust
// 
// <|>
```

Actual behavior (enter is ignored)

```rust
// <|>
```

**Comment by kjeremy** [comment]
This may be because we don't specify a language configuration json file in the vscode extension's package.json.

See https://github.com/rust-lang-nursery/rls-vscode/blob/master/language-configuration.json as an example of what rls uses

**Comment by matklad** [comment]
>This may be because we don't specify a language configuration json file in the vscode extension's package.json.

We ignore language configuration stuff and try to do all the things ourselves. This goes against how vscode typically work, but I think ultimately is the better approach: language configuration does not know about syntax, so it can go only so far. Compare, for example, how ra_lsp's extend selection and VS Code's build one works. 

I believe this particular issue is caused by our on-enter handler here: https://github.com/rust-analyzer/rust-analyzer/blob/0952b928addce602bef9b671d7904033df39f632/crates/ra_analysis/src/lib.rs#L227-L231. In theory, it could be better than the built-in one, but in practice, I expect we have more bugs currently :)

**Comment by matklad** [comment]
Excellent catch!

I wonder if we should have a test for this...

Seems tricky to write, because it's the VS Code which should be behind the wheel here (currently, we have zero tests for typescript code...)
