### ISSUE TITLE
Design: desugaring infrastructure

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2236]
Meta: this issue is an experiment in managing an open-source repository. The biggest problem with rust-analyzer at the moment is that relatively few people are doing design work. Given that rust-analyzer uses a novel approach to IDE building, design is actually a huge fraction of work, and a natural bottleneck. Let's see if we can add mentoring instructions for needs-design issue?

rust-analyzer has two representations for expressions:

* concrete syntax tree (defined in [ast/generated.rs](https://github.com/rust-analyzer/rust-analyzer/blob/8af85263f7cd249356382aa61b98094594165364/crates/ra_syntax/src/ast/generated.rs))
* AST (defined in [expr.rs](https://github.com/rust-analyzer/rust-analyzer/blob/8af85263f7cd249356382aa61b98094594165364/crates/ra_hir/src/expr.rs))

Because we want to be incremental, AST does not directly refer to CST. In particular, AST nodes do not know their spans. Additionally, there's no one-to-one correspondence between AST and CST nodes, because we do desugaring when switching from CST to AST. Another complication is that CST may be spread across several logical files (due to macro expansion), but AST is a single "glued" datastructure. 

At the same time, we need ability to map, in both directions, between AST and CST. This is needed:

* for error reporting (errors are detected in the AST, but should be reported in terms of CST)
* for debuginfo (we don't handle this yet)
* for IDE features (IDE starts with CST, then gets AST to run some analysis, than presents results back as edits of CST)

Currently, this mapping is impercise and very ad-hoc, see [body.rs](https://github.com/rust-analyzer/rust-analyzer/blob/8af85263f7cd249356382aa61b98094594165364/crates/ra_hir_def/src/body.rs#L119-L143). 

We should design and implement a bidirectional desugaring system which is guaranteed to be precise and never returns `None`. This system should be plugged into [lower.rs](https://github.com/rust-analyzer/rust-analyzer/blob/8af85263f7cd249356382aa61b98094594165364/crates/ra_hir/src/ty/lower.rs).

**Comment by cjgillot** [comment]
Hello,
I would like to work on this.
However, it may take me some time to get intimate knowledge of the code base.
Do you have further constraints?

**Comment by matklad** [comment]
That's cool @cjgillot we have some (somewhat obsoleted) documentation in `docs/dev` folder, as well as a module-level docs!

> Do you have further constraints?

I can't name more constraints off the top of my head. However, there may be some additional things to consider which I don't know about :)

**Comment by cjgillot** [comment]
This is what I understood from the requirements.
----

The parser provides a concrete syntax tree with all the position information.
Semantic analysis does not need that much information,
so we want it on a simpler abstract syntax tree.
However, reporting requires to go back to the concrete tree.

Therefore, the problem is of designing a mapping `CST -> (AST, BackMap)`
such that the first projection `CST -> AST` is forgetful,
but going back is easy using the `BackMap`.

Precision requirement: the round-trip `CST node -> AST node -> CST node` must be identity.
Completeness requirement: lowering and backmapping must not fail.

This what I got about the current implementation
----

The concrete syntax tree is called AST. It follows faithfully the Rust syntax.
The abstract tree is called HIR. It contains 2 kinds of objects: expressions and patterns.

Macro expansion is done on the AST. A virtual file is created to contain the expanded form. The created AST is then lowered.

The lowering is done for each function, static and const independently.
It recursively walks the AST, registering 2 pairs of maps:
AST expr -> HIR expr; HIR expr -> AST expr; likewise for patterns.
Some desugaring is done at the same time.

Problems:
* HIR nodes created as part of desugaring have no AST counterparts.
* Backmapping can fail.
* Precision is not guaranteed.

------------

Does this seem right to you @matklad ?

**Comment by matklad** [comment]
Yep, creating a stream is a good idea: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Desugaring

**Comment by matklad** [comment]
A somewhat related issue is https://github.com/rust-analyzer/rust-analyzer/issues/2258

**Comment by matklad** [comment]
Update:

A lot of exploration was done in https://github.com/rust-analyzer/rust-analyzer/pull/2417 and https://github.com/rust-analyzer/rust-analyzer/pull/2405. One promising approach that was discovered is using `Result<_, MissingExpr>` as source for missing expressions intoroduced by lowring. By flipping from `Option` to `Result`, we very clearly express "this expression is synthesized out of thin air, it wasn't present in the original source", and, in theory, we cal also add extra info to error type, for example, the parent expression.

Actually applying this design and merging the work is to be done though.
