### ISSUE TITLE
Disable laggy enhanced typing

### ISSUE THREAD

**Issue by Timmmm** [rust-analyzer/rust-analyzer#2331]
There's an option `rust-analyzer.enableEnhancedTyping` which automatically continues `//` comments when you press enter. Unfortunately it works by [overriding the type command](https://github.com/rust-analyzer/rust-analyzer/blob/545c21923e2bc8daee889b26919256bb2ba55282/editors/code/src/extension.ts#L88). That makes typing with [other extensions](https://github.com/Dart-Code/Dart-Code/issues/1800#issuecomment-556195953) extremely laggy.

I think this feature should be disabled by default:

* It's pretty bad for a feature to make *typing* slow in a text editor.
* It's honestly a really annoying feature. When I press enter at the end of a comment I want to continue it maybe 20% of the time. Adding or removing `// ` is the same number of keystrokes so it makes sense to optimise fo the common case (not continuing a comment). Not only that, but it is much more predictable to *not* automatically insert `// ` so I can add `// ` faster than I can remove it, because I don't have to read the screen to see if `// ` was inserted.

To be honest, the fact that you had to override a basic part of VSCode to do this is a pretty big sign that you shouldn't do it. It's more appropriate for extensions that actually change how typing works - like the Vim extension. No other language extensions do this.

**Comment by lnicola** [comment]
This seems a bit strange.

```ts
export async function handle(event: { text: string }): Promise<boolean> {
    const editor = vscode.window.activeTextEditor;
    if (
        editor == null ||
        editor.document.languageId !== 'rust' ||
        event.text !== '\n'
    ) {
        return false;
    }
```

I'm surprised that simply running this code slows down typing in other languages. Code does a lot of stuff while typing anyway, e.g. each arrow key press fires a telemetry event, yet holding down an arror isn't particularly laggy.

**Comment by DanTup** [comment]
FWIW - There's some more info about this issue in the VS Code issue tracker here:

https://github.com/microsoft/vscode/issues/75627

The reason it's laggy is that every key press has to round trip from the VS Code process to the extension host process (to be processed by the extension code) and then back to the editor before it renders on the screen. Since there's a single extension host that all extensions run in and nodejs is single-threaded, that also means that any other extensions that have code handlers firing from that key press (for example if they've hooked document edits, selection changes, or provide code completion etc.) all of those handlers will be processed synchronously and can delay your key press handling. This means the experience is really variable based on how many extensions you have installed, which events they listen to, and how much synchronous computation they do in those event handlers (or even computation that just may happen to overlap with the keypresses).

**Comment by GeorgeHahn** [comment]
I'm having an issue where pressing enter sometimes takes tens of seconds before inserting a newline. Disabling enhanced typing seems to have fixed it.

The setup is VSCode SSH Remote with rust-analyzer 4516c4c1447942a8f01b59a71dcf5abfa2c5e37a and all other extensions disabled. The same issue is observed on VSCode stable (1.41.1 user) and insiders (1.42.0 user). Cargo watch is enabled. The issue can be reproduced reliably after saving a file.

**Comment by matklad** [comment]
@GeorgeHahn which os rust-analyzer runs on?

**Comment by gilescope** [comment]
I've seen enter not work on windows and OSX. Disabling it worked fine though.
Maybe for now it shouldn't be on by default?

**Comment by GeorgeHahn** [comment]
> @GeorgeHahn which os rust-analyzer runs on?

Remote is Linux (Ubuntu 16)

**Comment by zackangelo** [comment]
I'm also experiencing the issue where the enter key becomes unresponsive. It seems to coincide with when `cargo check` is running.

**Comment by matklad** [comment]
it is disabled by default since some time.

**Comment by ilyagr** [comment]
Is it enabled by default again? In VS Code, `rust-analyzer.typing.continueCommentsOnNewline` seemed to be true by default. I disabled it, will now see if it helps with my issue.

(The issue is that, after VS Code is running for ~a few hours, typing and moving the cursor becomes extremely laggy. A workaround is to reload the VS Code window. I initially saw the problem on nightly rust-analyzer for VS Code release, now down-graded to stable and changed that option. I'm not yet 100% sure how to diagnose whether rust-analyzer is the curprit and, if it is, how I could get any helpful debugging info).

Another aside: I also tried putting `"rust-lang.rust-analyzer": 2` in the [`extensions.experimental.affinity` setting](https://github.com/microsoft/vscode/issues/75627#issuecomment-1078827311). Not yet sure whether that helped, since it takes hours for the issue to occur.
