### ISSUE TITLE
`super::super` shows autocompletions for `super`

### ISSUE THREAD

**Issue by YetAnotherEmuDev** [rust-analyzer/rust-analyzer#2377]
```rust
mod a {
	const A: usize = 0;
	mod b {
		const B: usize = 0;
		mod c {
			use super::super::<|>; // Shows B as a completion item
		}
	}
}
```
Note that goto definition appears to work.

**Comment by matklad** [comment]
Huh, not sure what's going on here. The place to start would be to print `path_prefix` and `def` over here:

https://github.com/rust-analyzer/rust-analyzer/blob/1aded342266f18b519666ac512e77b0c211fff5d/crates/ra_ide_api/src/completion/complete_path.rs#L10-L17

**Comment by detrumi** [comment]
In the snippet above, `path` is always `ModPath { kind: Super(1), ..}` for one or more super's in `super::super::<|>`.

**Comment by matklad** [comment]
That's funny! We've basically never supported nested supers in the name resolution. Recently, I've refactored paths and actually added the proper handing to the name resolution code:

https://github.com/rust-analyzer/rust-analyzer/blob/010d90202102e4e30ecd670e8500170247ef74a6/crates/ra_hir_def/src/nameres/path_resolution.rs#L159-L160

However, I didn't add a test for it, and surprise, the feature as a whole does not work because we never *produce* paths with nested supers in the first place. We need to fix lowering code in two places to produce nested super:

* https://github.com/rust-analyzer/rust-analyzer/blob/010d90202102e4e30ecd670e8500170247ef74a6/crates/ra_hir_def/src/path/lower/lower_use.rs#L106-L110
* https://github.com/rust-analyzer/rust-analyzer/blob/010d90202102e4e30ecd670e8500170247ef74a6/crates/ra_hir_def/src/path/lower.rs#L103-L105

(note that we do need two separate code-paths for it, because nested use trees *are* a separate way to express a path).

**Comment by matklad** [comment]
The test for this should go here:

https://github.com/rust-analyzer/rust-analyzer/blob/010d90202102e4e30ecd670e8500170247ef74a6/crates/ra_hir_def/src/nameres/tests.rs
