### ISSUE TITLE
Type inference for overloadable operators

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#2454]
Follow-up to #390. We don't support overloads of the binary operators in the type system yet, e.g. handling custom `Add` implementations etc.. We have all the necessary systems in place to do this, but I don't know if it makes sense to try doing it before we've got a solution for https://github.com/rust-lang/chalk/issues/234, since that would probably prevent many cases from working anyway.

**Comment by flodiebold** [comment]
This is mostly implemented, except for some bugs (#7150).

**Comment by rben01** [comment]
If RA reports that the inferred type of `1_u32 / 2_u32` is `<u32 as Div<u32>>::Output`, does that fall under this issue, or should I submit a separate issue? (I'd expect `u32` due to the trait implementation [here](https://doc.rust-lang.org/std/primitive.u32.html#impl-Div%3Cu32%3E-for-u32), which AFAIK is unambiguous.)

**Comment by Veykril** [comment]
That seems to be a problem with your rust setup or project
