### ISSUE TITLE
How to disable function information while typing?

### ISSUE THREAD

**Issue by readlnh** [rust-analyzer/rust-analyzer#2532]
ra always shows function information while typing, which is really annoyed. How can I disable it?
<img width="672" alt="图片" src="https://user-images.githubusercontent.com/16349082/70682338-8d295a80-1cd9-11ea-8d1b-d9968d190a60.png">

**Comment by matklad** [comment]
This is controlled by the VS code setting here:

![image](https://user-images.githubusercontent.com/1711539/70701192-3d906200-1ccc-11ea-8a2e-e9133a5ddc11.png)

It might also be the case that we are over-eager in triggering the hints. It might make sense to compare our behavior with type script. cc @kjeremy 

<rant>I personally find VS Code's UI for parameter hints obtrusive, I wish it worked like the one in IntelliJ</rant>

**Comment by kjeremy** [comment]
It's triggered by default when typing  `(`, `)` and `,`:

 https://github.com/rust-analyzer/rust-analyzer/blob/4444192b05c107a40a5a05ea3c9091ad8f8cbbcc/crates/ra_lsp_server/src/caps.rs#L27

It looks like the typescript LS triggers on `(`, `,` and `<`:
https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-server.ts#L157

I originally added the trigger on `)` because I couldn't get back into the signature help after closing the function but maybe that should be taken out.

**Comment by flodiebold** [comment]
Is there anything left to do here?

**Comment by matklad** [comment]
yeah, I think we can close!
