### ISSUE TITLE
rust-analyzer failed to load workspace: cargo metadata failed: Permission denied (os error 13)

### ISSUE THREAD

**Issue by iduanyingjie** [rust-analyzer/rust-analyzer#2653]
![WechatIMG76](https://user-images.githubusercontent.com/8772749/71353460-12532000-25b4-11ea-92aa-5d2acf5336fc.png)

OS: Ubuntu 18.04

**Comment by matklad** [comment]
Does running `cargo metadata` from the terminal works?

**Comment by iduanyingjie** [comment]
> Does running `cargo metadata` from the terminal works?

Yes it works

**Comment by abronan** [comment]
Getting the same issue somehow.

```
ArchLinux 5.6.4 + AwesomeWM
vscode 1.44.2
```

The error (_logged in vscode output for both stable and nightly rust-analyzer_):

```
[ERROR rust_analyzer::main_loop] loading workspace failed: Failed to read Cargo metadata from Cargo.toml file /home/myuser/testproject/Cargo.toml
    
    Caused by:
        0: Failed to run `cargo metadata --manifest-path /home/myuser/testproject/Cargo.toml`
        1: Permission denied (os error 13)
        2: Permission denied (os error 13)
```

I'm scratching my head on this one because this is a fresh install, Cargo bin directory is in `PATH`, permissions look OK everywhere and I can run `cargo metadata` just fine on my shell (outside or within vscode). Nothing I do fiddling with permissions or reinstalling the toolchain helps.

I guess I can attempt compiling from sources and add some debug statements because I'm stuck at the moment.

**Comment by lnicola** [comment]
Since you're running a WM I don't expect this to be in issue, but does it still happen if you run Code from a terminal? With a DE it's easy to end up with a different `PATH` for programs not spawned by a shell.

I would try adding a `std::thread::sleep` somewhere around [here](https://github.com/rust-analyzer/rust-analyzer/blob/36840bd6c71eaf18cdf418c92af51c24e547a4a7/crates/rust-analyzer/src/bin/main.rs#L74). This will allow you to check the environment of the server (`tr '\0' '\n' < /proc/$(pidof rust-analyzer)/environ`) and trace it to see what it's running (`sudo strace -fp $(pidof rust-analyzer)` and look for `EPERM` errors).

I suspect that `EPERM` here is a non-executable `cargo`, but I don't know how you could end up in that situation.

**Comment by abronan** [comment]
@lnicola Did exactly that and found out this was my error after all. I used `CARGO` as I would use `CARGO_HOME` (pointing to cargo root directory) and because rust-analyzer is loading the `CARGO` env var to locate the cargo binary, it was effectively trying to call `~/.cargo metadata ...` which obviously would return the perm error because pointing to the cargo directory.

Everything works like a charm now. Excited to start using it! Thank you.

**Comment by lnicola** [comment]
I wonder if we should check whether the `CARGO` environment variable points to a directory. We'd have to see if it's an absolute or relative path, then go through `PATH` and look it up in each directory there.

@iduanyingjie it's been a while, but would you be willing to give it a try again? It's possible that you were having the same issue, or that the debugging steps above would help.

**Comment by pbr0ck3r** [comment]
I am getting this error on a Mac. My bash_profile points to `~/.cargo/` and I can run cargo metadata just fine from a command line

**Comment by lnicola** [comment]
@pbr0ck3r Does it work if you run your editor from the terminal? Do you have a `CARGO` environment variable set?

**Comment by pbr0ck3r** [comment]
Yes I have a `CARGO` env variable set and my `PATH` contains it. I can not run `cargo metadata` just fine from a command line. If I start VsCode from the command line still get the same error.

**Comment by lnicola** [comment]
What is your `CARGO` environment variable set to? Does it work if you unset it?

**Comment by pbr0ck3r** [comment]
`~/.cargo/bin`

**Comment by pbr0ck3r** [comment]
Yes it still works if I unset it or remove it. When I check in the terminal `which cargo` it does point to my `~/.cargo/bin` folder.

**Comment by lnicola** [comment]
Yeah, don't do that. There's `CARGO_HOME` which is supposed to point at `~/.cargo/bin` and `CARGO` which we use as the `cargo` executable. See two posts above your first one for another instance.

**Comment by pbr0ck3r** [comment]
Interesting, brew automatically set up `CARGO` to point to the `~/.cargo/bin` folder. Do both of them need to go in my path? or just `CARGO_HOME`.

**Comment by pbr0ck3r** [comment]
Looks like that fixed my error, but now getting a error saying, but I do have a Cargo.toml file in the directory.
```
Error during execution of `cargo metadata`: error: could not execute process `rustc -vV` (never executed)
Caused by:
  No such file or directory (os error 2)
```

**Comment by lnicola** [comment]
Sounds like `rustc` is not in PATH.

**Comment by pbr0ck3r** [comment]
Yeah so I have resolved all my issues... I removed `CARGO_HOME` from my path and removed the `env` variable of it. And only have `CARGO` as a env variable pointing to the executable. All works now.

**Comment by pbr0ck3r** [comment]
So basically brew used `CARGO` as `CARGO_HOME` would be used. And this rust-analyzer relies on `CARGO` pointing to the executable. So changing it to do so fixed vsCode errors.

**Comment by pbr0ck3r** [comment]
Also I noticed if I have `CARGO` and `CARGO_HOME` it breaks things. So I have remove `CARGO_HOME` for now and it seems to be working fine both in terminal and vsCode.

**Comment by pbr0ck3r** [comment]
This project should really just rely on `CARGO` or `CARGO_HOME` pointing to the root cargo directory `~/.cargo/bin` and find the cargo executable from there.

**Comment by matklad** [comment]
We cleaned up toolchain discovery a while ago.
