### ISSUE TITLE
"inline variable" assist sometimes deletes statements.

### ISSUE THREAD

**Issue by omerbenamram** [rust-analyzer/rust-analyzer#2666]
It seems that the `inline variable` assist can potentially delete entire statements.
It triggered in this case with iterators:
![10bptKe64K](https://user-images.githubusercontent.com/2467993/71424856-098b4880-269f-11ea-8e68-aaf401c72392.gif)

It does behave nicely for simple bindings though.

**Comment by matklad** [comment]
Yeah, I guess the problem here is that we don't see usage inside the macro as usage, so the fix should go to the "find all references" functionality.

**Comment by TomasKralCZ** [comment]
So this is strange, the tests in `inline variable` work, but when I try to apply the assist on the test case myself, they just delete the statement. Is this expected or am I doing something wrong ?

**Comment by TomasKralCZ** [comment]
https://github.com/rust-analyzer/rust-analyzer/blob/87e1baf2421d80bf6d6acd776e29827196931a32/crates/ra_hir/src/source_analyzer.rs#L332-L350

I think the right thing to do here would be fixing the "general reference search infrastructure", since neither recognize usage in the macro and it's a non-trivial fix I think. But that would require moving the reference search infra into its own crate.

**Comment by matklad** [comment]
>But that would require moving the reference search infra into its own crate.

Yeah, I plan to reorganize things soonish, so that assist can make use of indexes. 

I think this particular issue can be closed though.
