### ISSUE TITLE
[VS Code] - Can the "workspace loaded" notification be off by default?

### ISSUE THREAD

**Issue by jasonwilliams** [rust-analyzer/rust-analyzer#2719]
This one here
![image](https://user-images.githubusercontent.com/936006/71646177-9e172b80-2cdb-11ea-8583-a2fb411ee0f8.png)

Or at least move it to the blue status bar underneath and show it for a few seconds. I find it distracting and often have to click it off.

I'm sure it's useful for debugging purposes, but having to close it every time a rust project is opened can become a bit laborious. 

It feels like the sort of thing that should be on if debugging mode is on, not for normal operation. Most other language servers don't show notifications unless i'm inspecting something.

**Comment by matklad** [comment]
This notification can be disabled via settings. I am OK with making it
disabled by default!

**Comment by jasonwilliams** [comment]
> This notification can be disabled via settings.
Which setting disables this?

**Comment by lnicola** [comment]
https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#settings.

**Comment by Veetaha** [comment]
Is this really specific to VS Code?

**Comment by jasonwilliams** [comment]
@Veetaha ive only been using rust analyser with vs code so I don’t know what it looks like on other IDEs, if it’s general then fair enough but the issue still remains the same .

**Comment by dsr085** [comment]
> 
> 
> > This notification can be disabled via settings.
> 
> Which setting disables this?

    "rust-analyzer.featureFlags": {
        "notifications.workspace-loaded": false
    }

**Comment by yoshuawuyts** [comment]
An alternative approach could be to follow the UX provided by the VS Code remote extensions, such as "WSL Remote". These extensions open a notification during initialization displaying progress while things are loading. Once the system is done loading, a "success" message is briefly flashed, and the notification is dismissed.

I like this flow because it allows people to visually track how far along the editor is with loading. And once it's done, all notifications are cleared and the editor is ready to be used. The _absence_ of overlays then signals "ready", which is an inversion of the current UX (and the topic of this issue). 

I opened https://github.com/rust-analyzer/rust-analyzer/issues/3283 earlier today to integrate this functionality into the VS Code extension.

**Comment by eminence** [comment]
I think this issue can be closed now (see #4253)
