### ISSUE TITLE
Macro-expansion of `*mut T` is missing a space

### ISSUE THREAD

**Issue by sinkuu** [rust-analyzer/rust-analyzer#2765]
Expanding `*mut T` from macro results in `*mutT`.

![Screenshot from 2020-01-08 21-15-10](https://user-images.githubusercontent.com/7091080/71977396-0924ad00-325c-11ea-8b5b-487f6af04473.png)

**Comment by kiljacken** [comment]
The issue presumable occurs because there's no whitespace in the macro generated syntax tree, and `ra_ide` function signature parsing uses original text layout from syntax tree. The code that generates this is [here](https://github.com/rust-analyzer/rust-analyzer/blob/cf5bdf464cad7ceb9a67e07985a3f4d3799ec0b6/crates/ra_ide/src/display/function_signature.rs#L164).

Maybe we should use hir display code instead of relying on original syntax tree text for this?

**Comment by flodiebold** [comment]
We don't have hir display code for complete function signatures, and to me it seems more robust to show the function signature as written. We could use the formatter infrastructure to insert spaces for macroexpanded text, once it exists...

**Comment by brundonsmith** [comment]
I believe I have a variation on this issue, but in my case it's around `&'a str`:

```rust

macro_rules! generate_parse_function {
    ($rule_name:ident, $parse_expr:tt) => {
        fn $rule_name<'a>(code: &'a str) -> (Option<Ast>, &'a str) {
            (Some(Ast::$rule_name), $parse_expr)
        }
    };
    () => {};
}

generate_parse_function!(nil, "NIL");
```

`rust-analyzer` shows this:
```rust
fn nil< 'a>(code: & 'astr) -> (Option<Ast>, & 'astr){
    (Some(Ast::nil),"NIL")
}
```

Note the `& 'astr` in the argument and return type. Also the rogue space in `< 'a>` (which doesn't cause a problem, but seems related.

`cargo-expand` shows this:
```rust
fn nil<'a>(code: &'a str) -> (Option<Ast>, &'a str) {
    (Some(Ast::nil), "NIL")
}
```

And the code does compile.

**Comment by kjeremy** [comment]
I think `cargo expand` runs it through `rustfmt` unless you specify `--ugly`

**Comment by oxalica** [comment]
@flodiebold 
What about keeping whitespace in TokenTree while expanding macros?
It should be easier to implement and can keep the original style in macro.
