### ISSUE TITLE
VS Code cannot start rust-analyzer when run on remote WSL Ubuntu

### ISSUE THREAD

**Issue by coriolinus** [rust-analyzer/rust-analyzer#2859]
- Built per https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#vs-code, including the Remote section.
- VS Code prompted to restart after installing
- Got this error message:

![image](https://user-images.githubusercontent.com/7822926/72518093-dcbcf200-3854-11ea-9d2c-97a813d1b45e.png)

- On a terminal within the remote session:

```sh
$ ra_lsp_server --version
Thu Jan 16 11:34:31 CET 2020
rust-analyzer c78d269
```

**Environment**

WSL:

```
$ uname -a
Thu Jan 16 11:40:39 CET 2020
Linux brute 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

VS Code:

![image](https://user-images.githubusercontent.com/7822926/72518256-37eee480-3855-11ea-96e6-b9938c847147.png)

**Comment by bjorn3** [comment]
I think ra_lsp_server needs to be installed locally instead of on the remote.

**Comment by coriolinus** [comment]
That appears to contradict Step 1 of the Remote section of instructions. Anyway, I don't _have_ a Rust environment set up on Windows, just on WSL.

**Comment by bjorn3** [comment]
It seems you are right that it does need to run om the remote.

**Comment by marcogroppo** [comment]
`ra_lsp_server` must be installed on the remote host. The extension must be installed on the remote, too (that is: you should click "Install VSIX" only AFTER you have opened the connection to WSL). `rust-analyzer` should be listed under "WSL: xxx - INSTALLED" in the Extensions view.

**Comment by coriolinus** [comment]
Yes, that was how it was configured.

**Comment by poga** [comment]
I had the same issue when using rust-analyzer in a remote container. 

The problem is my VSCode is opened on a path that doesn't exist in the remote container(because it's trying to open last opened file in the container). So, `ra_lsp_server` failed to start on the non-exist path.

Fixing the path resolve the issue.

**Comment by harrier-lcc** [comment]
Happens to me in using VS Code Remote with Ubuntu Server.
Seems the problem is when VS Code started the extension, it started it without loading some PATH settings (so it do not load up `~/.profile` etc), and do not find `~/.cargo/bin` thus cannot load up `ra_lsp_server`.

Even with `rust-analyzer.raLspServerPath` set to absolute path of `~/.cargo/bin/ra_lsp_server`, it started the LSP server, but cannot find cargo metadata (as it cannot run `cargo`, not having it in PATH).

Might be related to #1813.

**Comment by matklad** [comment]
Yeah, I think this is pretty likely caused by the fact that rust-analyzer is not in PATH. I've improved the diagnostic message to include the value of PATH.

**Comment by coriolinus** [comment]
The thread so far correctly identifies the problem, but not the solution. The solution which worked for me was to, within WSL:

```sh
mkdir -p ~/.vscode-server && echo 'PATH="$PATH":"$HOME"/.cargo/bin' >> ~/.vscode-server/server-env-setup
```

**Comment by maytees** [comment]
thanks

**Comment by quicknir** [comment]
Just to add yet another finding here. What corilolinus suggests is kind of correct but not completely, and the .bashrc snippet that rustup (I think?) adds when installed kind of shows why:

```
#!/bin/sh
# rustup shell setup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"$HOME/.cargo/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac
```
Note the emphasis on prepending. For me, with coriolinus' fix (thanks!), RA worked when I launched vscode from an interactive shell, but not otherwise, because I probably do have a system-installed rustc. I've changed my `~/.vscode-server/server-env-setup` to simply source the file above :  `. "$HOME/.cargo/env"` and now it works perfectly, no matter where I launch vscode from.

Hopefully that helps with some of the confused emojis!

**Comment by TTTPOB** [comment]
same error message here, but i am using wsl2, debian 13. .45 worked for me.
