### ISSUE TITLE
Conventional commits proposal

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#2866]
I'd like to propose all contributors to follow [the simple rules of conventions in their commit messages](https://www.conventionalcommits.org).

This unifies the format of describing changes to the project, allows for better mental parsing, sorting and filtering our commits.
This will also enable us to [generate automatic changelogs and also use tools to enforce conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#tooling-for-conventional-commits).

As a scope of the commit I propose using the relevant crate name where the change was introduced appended with additional subscopes delimited with a dot.
E.g:

```
refactor(ra_syntax.validation): removed code duplication from validate_literal() function
```
So what's your feedback, guys?

**Comment by matklad** [comment]
I personally don't find rigorous rules about commit messages useful, except that the title shall be <= 50 characters :-) 

I've followed [something like this](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md#commit-messages) in IntelliJ-Rust pretty rigorously in the past. rust-analyzer historically didn't have any rules for commit messages, and I personally don't perceive any difference as far as reading the history goes. I do feel less friction when composing commit messages, because I don't need to artistically shorten the title because of the tag. I also don't think about

**Comment by matklad** [comment]
... I also don't think about contributor's commit message format (it's impossible to *enforce* this rule without spending some significant effort). 

I also object pretty strongly to auto-generated changelogs. I think the *readers* of the change log would prefer something with the human touch, which emphasizes important changes and (what's no less important!) hides less trivial ones. For me, as the *writer* of the changelog, looking through `git log --merges --reversed` helps to build a better picture of the project in my head. It's also plainly satisfying, I don't want to handle that joy to a bot :)

**Comment by matklad** [comment]
On a more philosophical note, I feel that guidelines in programming fall into two categories:

* those which make code more robust/maintainable, etc
* those which can be formulated precisely and can be easily enforced

I feel that the folks usually place too much emphasis on the second one, which is in the limit: "if we can have a guideline, we should have a guideline for the sake of consistency". 

Sorry if this all sounds a bit too negative: I don't have anything against the idea per se, it's just that my *personal* experience with it tells me that it creates additional work for little to no benefit :)

**Comment by matklad** [comment]
@flodiebold how do you feel about commit messages guidelines?

**Comment by flodiebold** [comment]
I think good commit messages are important, but I don't feel these guidelines help a lot with that and would just add to the friction for contributions. If we wanted automatically generated changelogs, it might make sense, but I agree that human-written ones are nicer (and since I don't have to write them... :slightly_smiling_face: )

**Comment by lnicola** [comment]
I wouldn't bet on it, but once we have a `CHANGELOG.md` the contributors might update it themselves :smile_cat:.

**Comment by matklad** [comment]
I think we don't need `CHANGELOG.md`, our relases are two short. Closing this issue then!
