### ISSUE TITLE
caret jumps from the second-last character of variable, with type inlay hints

### ISSUE THREAD

**Issue by tigregalis** [rust-analyzer/rust-analyzer#2888]
Apologies for the messy issue title. Not sure how to phrase it. Example below applies to VS Code.

![type-inlay-hint-issue](https://user-images.githubusercontent.com/38416468/72807073-86efac00-3c91-11ea-9208-ed3d5454f0bb.gif)

With type inlay hints, when moving the caret, it jumps from between the second-last and last characters (`[len-1, len]`) of the variable name to the end of the inlay hint. That is, the caret never falls after the end of the variable name on the last character (`[len, len+1]`).

This is unintuitive. It would be more appropriate to have the type inlay hint "occupy" the whitespace afterwards instead.

The parameter inlay hint appears to behave intuitively.

**Comment by kiljacken** [comment]
The parameter inlay hint has the same theoretical issue, but seems better because it is a prefix instead of a suffix. We talked about it when we initially implemented the features and I think it's an inherent limit with what VSCode allows us to do the the editor. Unless something has changed since then, we can't really do anything about it.
Going to close it, hope you don't mind.

**Comment by tigregalis** [comment]
Ah alright. Thanks for the response. I should have checked closed issues. Feel free to close it.
