### ISSUE TITLE
"inline_local_variable" assist shouldn't be applicable if the variable is unused

### ISSUE THREAD

**Issue by TomasKralCZ** [rust-analyzer/rust-analyzer#2900]
![issue](https://user-images.githubusercontent.com/23663355/72990657-d7315000-3df0-11ea-9b7d-218b9caccba8.gif)

**Comment by flodiebold** [comment]
This should be easy to fix: [here](https://github.com/rust-analyzer/rust-analyzer/blob/8a4c248c48ad7bb9ad556717ee013129c190dbfa/crates/ra_assists/src/assists/inline_local_variable.rs#L53) we have a list of all references to the variable, so we just need to check whether there are any and `return None` otherwise.

**Comment by TomasKralCZ** [comment]
Yeah, I'll do that.
