### ISSUE TITLE
Trait method rename does not rename usages and implementations

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-analyzer/rust-analyzer#2977]
Consider the ImportsLocator trait from the ra_assists: https://github.com/rust-analyzer/rust-analyzer/blob/9be1ab7ff948d89334a8acbc309c8235d4ab374f/crates/ra_assists/src/lib.rs#L86

It has a single `find_imports` method, which is implemented in 2 structs and used in one module:

* https://github.com/rust-analyzer/rust-analyzer/blob/9be1ab7ff948d89334a8acbc309c8235d4ab374f/crates/ra_assists/src/lib.rs#L249
* https://github.com/rust-analyzer/rust-analyzer/blob/9be1ab7ff948d89334a8acbc309c8235d4ab374f/crates/ra_ide/src/imports_locator.rs#L44
* https://github.com/rust-analyzer/rust-analyzer/blob/9be1ab7ff948d89334a8acbc309c8235d4ab374f/crates/ra_assists/src/assists/auto_import.rs#L53

Try to rename the trait method in the trait declaration.

Expected: all 4 places are changed
Actual: only the trait declaration is changed

**Comment by tmcguire** [comment]
This sounds similar to https://github.com/rust-analyzer/rust-analyzer/issues/4201

**Comment by GopherJ** [comment]
similar to #6854

**Comment by jhgg** [comment]
I run into this issue often enough that I'm going to try to take this on in my free time. Does anyone have any pointers on where to start looking into this?

**Comment by Veykril** [comment]
So the problem here actually isn't really related to renaming but to usage searching. Small snippet to give a bit of insight of whats wrong here:
```rust
trait Foo {
    fn bar(&self) { // 1
        self.bar(); // 2
    }
}

impl Foo for () {
    fn bar(&self) { // 3
        self.bar(); // 4
    }
}
```
Here when searching for all usages of `1`, `2` or `4` we get `[1, 2, 4]` back as a result, when searching for usages of `3` we only get `[3]` back.

So for now to get this working we want all of the 4 defs/usages be found so that renaming works here properly. So basically we want to somehow included `[3]` in the found set and also include the others in the set for when searching for usages of `3`, so we got two problems here.

The first problem is that when looking for `1`, `2` or `4` we have the trait definitions function as our function def. That means the trait impl definition will just not be considered as we immediately discard it in here https://github.com/Veykril/rust-analyzer/blob/3f1a220f32220cd4a664ca1adac5eb36e9eb33b2\crates\ide_db\src\search.rs#L445-L474. 

The second problem is that when looking for usages of `3` we get the trait impls function as a definition to search for, but `1` and `2` are considered usages of the function of the trait *definition*. `4` wont be included due to the same reason as for problem 1.

**Comment by flodiebold** [comment]
For the second one, probably just have a condition in the beginning to rename the trait method if we're renaming a method in an impl?

**Comment by Veykril** [comment]
Ye actually that would be a simple fix for just renaming for now that should work.
