### ISSUE TITLE
No longer builds on stable cargo

### ISSUE THREAD

**Issue by djrenren** [rust-analyzer/rust-analyzer#3004]
I went to build the server and got the following error. Looks like it still builds fine on nightly. 
Not a huge issue but the README says to use stable rust/cargo.

```
➜  rust-analyzer git:(master) ✗ cargo xtask install
error: failed to parse manifest at `/Users/john/Documents/rust-analyzer/rust-analyzer/Cargo.toml`

Caused by:
  feature `profile-overrides` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["profile-overrides"]` to enable this feature
```

**Comment by sehz** [comment]
I was able to fix same issue by updating to latest version of rust
```rustup update```

**Comment by djrenren** [comment]
> I was able to fix same issue by updating to latest version of rust
> `rustup update`

That's embarrassing, you're totally right. Thanks!

**Comment by lnicola** [comment]
Ugh. We have a version test in `xtask`, but it never gets to run because `cargo` can't compile it :confused:.

**Comment by zoidbergwill** [comment]
I had a similar issue because I installed something on my MacOS with brew that installed Rust which started conflicting with my `rustup` managed stable Rust.

So I first tried `rustup update` and calling `$HOME/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo`, but that called a different cargo which then threw the error again.

I ended up uninstalling the brew formula which solved it. :tada:
