### ISSUE TITLE
'Fill match arms' should work with existing match arms

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#3039]
The documentation for the `fill_match_arms` assist actually says "Adds missing clauses to a match expression", but sadly it currently only works if there are no arms or just a default arm. It would be nice to support arbitrary matches with missing arms; this requires some kind of exhaustiveness check, which can get complicated, but maybe another smaller step would be to support matches on enums if some enum variants are missing completely.

**Comment by matklad** [comment]
The relevant code is here: 

https://github.com/rust-analyzer/rust-analyzer/blob/8337dcd9e277feac8e9cff621c752a3e86ba19e6/crates/ra_assists/src/assists/fill_match_arms.rs#L34

I think for starters we shouldn't bother with proper exhaustiveness analysis, and just implement some special cases directly in the assist's code.

**Comment by Geobert** [comment]
Even with no arms, I don't get the assists. I'm using the version downloaded by the vscode extension.
The enum I'm trying to match against is generated by `pest` (the `Rule` enum).

**Comment by matklad** [comment]
pest is proc macro iirc, we don't support proc macros yet.

**Comment by Geobert** [comment]
That's why then, thanks for the answer :D

**Comment by JoshMcguigan** [comment]
> but maybe another smaller step would be to support matches on enums if some enum variants are missing completely

This seems like it would be rather straight forward. I see where the existing code returns `None` if there is more than one existing arm, or if the existing arm is non-trivial. My thought was it should be possible to remove or modify that check, and when building the `new_arm_list`, if the arm already exists, use that one (you can't just skip existing arms, since the current implementation re-writes all arms).

The thing I am not sure about, is how to check if one of the enum variants is already covered. We have `variants` (the full list) and `existing_arms`, but they are different types and I'm not sure the best way to compare them. Is this the correct path to be heading down here?

**Comment by slyngbaek** [comment]
I gave this one a shot. Since this can get rather complicated, I followed a simpler set of rules which are hopefully intuitive (described in the PR). Tests should also help illustrate.

**Comment by lnicola** [comment]
This is fixed, right?
