### ISSUE TITLE
`use` completion of `std::sync::atomic::` will not yeild results like `AtomicBool`

### ISSUE THREAD

**Issue by kdelorey** [rust-analyzer/rust-analyzer#3082]
```rust
use std::sync::atomic::<|>
```

-or-

```rust
use core::sync::atomic::<|>
```

will not yield any of the atomic types as result. It does yield functions however.

**Comment by bjorn3** [comment]
Is `#[cfg(target_has_atomic_load_store = ...)]` implemented in rust-analyzer?

**Comment by ruabmbua** [comment]
https://github.com/rust-analyzer/rust-analyzer/blob/aff82cf7ac172f213cb5dcca637cb2c5332294c1/crates/ra_project_model/src/lib.rs#L490

Seems like is is supported. I also have no issues auto completing atomics.

Edit:
Is fixed by: https://github.com/rust-analyzer/rust-analyzer/commit/0bfebb8b2042e787c16bbfa26b1cbcd9425de2ab

**Comment by kdelorey** [comment]
@ruabmbua, confirmed, looks like it was fixed. Closing :tada:.
