### ISSUE TITLE
Extension doesn't download the language server binary

### ISSUE THREAD

**Issue by Aloso** [rust-analyzer/rust-analyzer#3095]
After installing rust-analyzer via the VS Code marketplace, I understand that a popup should appear that downloads the latest language server release. But for me, the popup doesn't appear. Instead, I see this error message:

> Couldn't start client Rust Analyzer Language Server

and a notification:

> A request has failed. See the output for more information.

The output is the following:

```
[Error - 21:14:13] Starting client failed
Launching server using command ra_lsp_server failed.
```

Below the notification, there's another error message:

> Unable to execute 'ra_lsp_server --version'

----

I use VSCodium 1.42.0, installed via the [Arch User Repository](https://aur.archlinux.org/packages/vscodium-bin) on Manjaro Linux.

## Workaround

EDIT: This happens when the old version of the extension is used. To make sure you use the latest version, delete it manually (it's probably in `~/.vscode/extensions`), and install it again.

**Comment by Veetaha** [comment]
Can you please open command palette with <kbd>Ctrl+Shift+P</kbd>, write `Toggle Developer Tools` and press enter to open the Developer Tools, then open Console tab and send its contents here?
Also please give the contents of `Help > About` window in VSCode?

**Comment by Veetaha** [comment]
This may be the same as #3096

**Comment by Aloso** [comment]
### Help → About

```Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-07T10:44:53.000Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.5.2-1-MANJARO
```

### Developer console

![ra](https://user-images.githubusercontent.com/15658558/74200601-b594ed00-4c67-11ea-911a-2effcbdb3df1.png)

**Comment by Aloso** [comment]
@Veetaha You were right, deleting the extension manually, as suggested in #3096 did the trick.

**Comment by Veetaha** [comment]
@Aloso, thank you for the feedback, I think we should mention this caveat in docs. @matklad we can close this issue

**Comment by Xymist** [comment]
Note for anyone else hitting this (cause might be different but symptom of failing to download the server is similar) - I had to uninstall, close VSCode, and then also delete `~/.config/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux` before reinstalling in order for the download to work.

**Comment by DC4JG** [comment]
Had notifications about downloading the language server on every start up of VS Code.
This issue was the top search result and helped me solve the problem, so for completeness sake (and other Windows users who might wonder where their `~/.config` is located) here are the steps I did to solve the issue.

1. Uninstall the extension
2. Close VS Code
3. Delete the extension folder in `C:\Users\USERNAME\.vscode\extensions`
4. Delete the extension folder in `C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage`
5. Open VS Code
6. Reinstall the extension

PS: The extension folder is named `matklad.rust-analyzer-[VERSION]` so don't look for the letter R in your list
