### ISSUE TITLE
Desugar doc comments to attributes

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3182]
At the moment, we have a dedicated query for docs:

https://github.com/rust-analyzer/rust-analyzer/blob/daffdd86749bc2d62b50ff9e0c869032d7932373/crates/ra_hir_def/src/db.rs#L106-L109

Internally, the query just looks at the `///` comments:

https://github.com/rust-analyzer/rust-analyzer/blob/daffdd86749bc2d62b50ff9e0c869032d7932373/crates/ra_hir_def/src/docs.rs#L44

The way to proper do this is to *desugar* doc comments into attributes, which should happen somewhere around here:

https://github.com/rust-analyzer/rust-analyzer/blob/953dbe3e02fa87bab2f12452746e6c50a47ac153/crates/ra_hir_def/src/attr.rs#L35

Then, the code to get the docs should be refactored to just call a method on the attrs

See also: 

* https://github.com/rust-analyzer/rust-analyzer/pull/1230/

* https://github.com/rust-analyzer/rust-analyzer/issues/2148#issuecomment-550519102

**Comment by matklad** [comment]
This should close #3180 as well

**Comment by djrenren** [comment]
Okay so I'm knee deep in this change. And I've routed it up through ra_hir with no problem. The issue is, there's lots of stuff in `ra_ide` that's trying to access doc comments through the AST which seems no bueno in this new world. I've cleaned up most, but there's one that's confusing me cuz I don't know the surrounding system that well:

https://github.com/rust-analyzer/rust-analyzer/blob/05981823bac91ba338110902fd435c6e3166f1d6/crates/ra_ide/src/display/navigation_target.rs#L396

This is the last major roadblock though so if we can clear it up this should be ready for review!

**Comment by djrenren** [comment]
Oh I forgot to mention this function is necessary because of this impl:

https://github.com/rust-analyzer/rust-analyzer/blob/05981823bac91ba338110902fd435c6e3166f1d6/crates/ra_ide/src/display/navigation_target.rs#L183

**Comment by matklad** [comment]
>there's lots of stuff in ra_ide that's trying to access doc comments through the AST which seems no bueno in this new world.

Lol yes, that's a recurring problem: some feature is implemented on top of AST cuz that's easier, than the feature grows to a huge file with call kinds of bells and whistles, and then we need to migrate it to HIR because using AST is just wrong. 

The `FileSymbol` is very fundamentally AST though -- it is created via map-reduce style text indexing, and just can't have access to semantic info. I think the best solution here is to just use `None` as the docs -- we only really use this for fallback for goto defnition, so it doesn't matter much.

Super long-term, we'll move the indexing itself over to HIR, so that we can, for example, index macro-expanded code.
