### ISSUE TITLE
Handling configuration

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3189]
Our story for configuration and settings is a mess at the moment. We should design something unified and user-friendly. Here are some problems we need to solve.

1. By design, rust-analyzer is not bound to LSP protocol, it should be usable as a library. There are some settings which make sense for the core library, for example "should completion automatically add `()`". There are also settings which make sense only for LSP server, like "show workspace loaded notification" or "display diagnostics". Ideally, we should keep them separate in the implementation, but unified in the LSP config UI for the user. 

2. One of the endemic IDE problems is features that you don't want/like. Ideally, every small feature should be hidden behind a feature toggle, such that users can disable all the annoying bits. 

3. The way LSP works, user generally needs to specify config in different places for each editor (in `settings.json` for VS Code and `init.el` for emacs). This is directly at odds with, for example, specifying rust-analyzer settings in the repository for all editors, and it also makes documenting settings a pain. 

4. LSP has a concept of "scoped" settings (withing the same workspace, different folders can have different settings). I am not sure if we need this flexibility right now, but we should at least look at it. 

5. We should make sure that documentation for features is auto-generated from the code that describes the features.

**Comment by SomeoneToIgnore** [comment]
More observations & random thoughts:

* Currently there are two types of settings: the ones related to the client, such as `rust-analyzer.displayInlayHints` for VSCode that make sense only in the editor itself and the ones related to the server, that are passed to the RA itself.
Additionally, different clients can have different settings. 
It would be nice to have a strict distinction in between those categories in the resulting design, to avoid the confusion.

* Ideally, RA should be able to handle configuration changes without restarts, not it's not true: https://github.com/rust-analyzer/rust-analyzer/issues/2857
It's even more confusing with the previous bullet: client-related settings like `rust-analyzer.displayInlayHints` are applied instantly and do not require restarts and currently it's impossible to tell which settings require the restart

* There's a strong need for a settings' hierarchies and various types of settings.
For example, inlay hints' settings include:
    * a setting to toggle them on and off (checkbox)
    * a setting to set their maximum size, including `null` as the value that turns this feature off (input)
    * a not implemented yet setting to have a particular types of hints enabled (a set of checkboxes?)

    Related issues:
    https://github.com/rust-analyzer/rust-analyzer/issues/2876
    https://github.com/rust-analyzer/rust-analyzer/issues/757

**Comment by Veetaha** [comment]
> currently it's impossible to tell which settings require the restart

Doesn't this list all of them? @SomeoneToIgnore 
https://github.com/rust-analyzer/rust-analyzer/blob/20252efb32bfdfe7392934a95a6c6d6b583d10e7/editors/code/src/config.ts#L21-L24

<hr>

It's apparent that we have 3 levels of interfacing:

## 1. `human/editor-plugin`

These interactions vary very much from editor to editor. Some support one options, others don't. The number of editor plugins is a variable value and each of them should have a special treatment.

In [this](conversation) @matklad proposed to use the same approach we have in [ast](https://github.com/rust-analyzer/rust-analyzer/blob/master/xtask/src/ast_src.rs) codegen. This approach implies that the logic for generating config schemas for all editors will be focused in one place and should be extended each time support for new editor is required. The main pros of this as noted by @matklad:
* faster compile times
* better overall simplicity

Another approach might be to use a universal IDL [(interface definition language)](https://en.wikipedia.org/wiki/Interface_description_language) like [`json schema`](https://json-schema.org/). This way codegen logic would be distributed, each plugin generates its own config by its own means using the single source of thruth - declared `editor-plugin/lsp-server` schema.
The pros:
* using codegen ecosystem that works with universal IDL ([e.g.](https://www.npmjs.com/package/json-schema-to-typescript))
* scalability, any new editor plugin manages codegen in its own way in its own repo


## 2. `editor-plugin/lsp-server`

This is where we don't care about which functionality is lsp-only and wich is core-lib-only. Lsp server accepts one blob of config values in any convenient structure (flat or nested, doesn't matter, or if matters just use more convenient structure). This is the entrypoint of `rust-analyzer` application config.

So from Rust code this looks roughly like this:
```rust
// crates/rust-analyzer/src/config/generated.rs
struct RustAnalyzerConfig {
    lsp_specific_option_n: String, // field names are made up
    lib_specific_option_n: String, // plugins don't know what is specific to what
}
```


## 3. `lsp-server/core-lib-component`

Each library component has its own purpose-oriented config struct:
```rust
// crates/ra_foo/src/config.rs
struct RaFooConfig { /* */ }

// crates/ra_bar/src/config.rs
struct RaBarConfig { /* */ }
```

In `rust-analyzer` crate we just need to setup bridge mappings of *the whole bag of settings* declared as `RustAnalyzerConfig` to config structs declared in each core library module.

Roughly it looks like this:
```rust
// crates/rust-analyzer/src/config_mappings.rs
impl From<RustAnalyzerConfig> for RaFooConfig {
     fn from(ra_config) {
          RaFooConfig { 
              lib_specific_option_n: ra_config.lib_specific_option_n
          }
     }
}
```

If needed `config_mappings.rs` boilerplate mappings and `crates/ra_foo/src/config.rs` structs can all be generated for convenience too, though at the end of the day `ra_foo` knows only about `RaFooConfig` and no `RustAnalyzerConfig` or `RaBarConfig`.

What are your thoughts?

**Comment by SomeoneToIgnore** [comment]
> Doesn't this list all of them? 

No, there's at least `maxInlayHintLength` that requires reload and is missing from the list.
Maybe there are more.

**Comment by SomeoneToIgnore** [comment]
> What are your thoughts?

For the 1st layer, I persnally like the ast codegen approach.
But that's very opinionated, I've just had enough issues with json schemas before.

I'm not entirely sure we need to have the 3rd layer due to a few reasons:

* it scales worse: when time passess, we might end up with a lot of `get*` methods and some of those we're forced to maintain (since RA is designed to be a library also, hence public API guarantees eventually will kick in and increase the maintenance cost)
* also, AFAIK, the librarification is not finished yet, having those methods around will require more code changes during library refactorings in comparison to simply handling the `&RustAnalyzerConfig` object in every library for now
* YAGNI — delivering settings to the RA components is not the problem currently, it just works™. Instead of complicating the code now, we'd better focus on the features we really need such as the auto reload interface and getting the settings from the external sources
* When the time comes and the `RustAnalyzerConfig` gets bloated, maybe instead of `get*` methods, we might want to use traits, something similar to the situation we have with the `RootDatabase`, `SourceDatabase`, `HirDatabase` etc.

**Comment by Veetaha** [comment]
The 3rd layer does need to exist. You don't want core library modules to depend on `RustAnalyzerConfig` declaration. Solving this through traits instead of mappings may also be an option. Sorry, I may not be too familiar with our high-leveler code organization yet...
And what is the librarification process happening, is it rustc?

**Comment by SomeoneToIgnore** [comment]
> You don't want core library modules to depend on RustAnalyzerConfig declaration. 

That's exactly want I want to now, for a simplicity.
Do not see any issues with that in general, since now we're able to get all the settings we need and I doubt that we won't be able later with that approach.

What are the issues that you see with that approach?
Also, how many library modules we're talking about now?

> what is the librarification process happening

RA itself, the API design is far from over.

**Comment by Veetaha** [comment]
> What are the issues that you see with that approach?

First of all, do we really have crates with `rust-analyzer` (previously RIP `ra_lsp_server`) as a dependency?
If yes, this is bad, because in theory we should be able to replace lsp server module with anything else, e.g. other communication protocol or direct editor integration module if such a need arises in the future. This means we need to separate **communication** logic from **business** logic.

**Comment by SomeoneToIgnore** [comment]
We can always move the config entity to a separate crate.
But maybe sharing the config object is the wrong way indeed.

What we need to understand is 

>  Also, how many library modules we're talking about now?

How many modules need the configuration now and what are the parameters that they require.

I've looked at the code briefly and so far it looks like the overwhelming majority of the properties are used in the `rust-analyzer` only.

So far, the external modules that need any configuration are:
* ra_ide (needs a config for inlay hints, currently 1 param, near future hints that there might be another one)
* ra_project_model (needs 2 params: sysroot, cargo features)
* ra_cargo_watch (needs the watch config)
* ra_vfs (needs 1 param: use_client_watching)

The rest of the config options are handled directly by the `rust-analyzer` module and even the ones that are passed to the external modules are either basic Rust types or the types taken from the dependencies, such as `CheckOptions` from `ra_cargo_watch`.

=================

Keeping this all in mind, it appears to me that sharing the whole config from 2), having `get*` methods or even implementing traits is a bit too much.

Maybe we shrink the 3) point to just

> Each library component has its own purpose-oriented config struct

Since it's the way it's done now already for some modules, we continue with it, keep those small structs in one big `RustAnalyzerConfig` (currently it's just `Config` and maybe it should stay this way)  in `rust-analyzer`.
Then, no getters, big config sharing or trait impls is needed: since we manage the config, its updates and propagation to the inner modules anyway, we just do that in `rust-analyzer`.

This way no dependency knows about the other configs and still get thir config propagated and updated.
Do I make sense?

**Comment by Veetaha** [comment]
Makes sense. Embedding (composing) each library component's purpose-oriented config struct in one big `Config` from `rust-analyzer` keeps things simple. If we **can** do this without explicit mapping we should prefer doing so to mappings and traits. 

Nevertheless, one flaw to this approach is that changes to library-specific configs will cause changes to `editor-plugin/lsp-server` interface edge, since this edge now embeds library-specific structs, but I think this will be fine until we don't have a stable API and once we cannot afford breaking changes adding an ad hoc mapping will solve this.

> We can always move the config entity to a separate crate.

I still don't think that having library crates depend on one big config declaration is good. In theory we can extract `ra_config` crate which declares a config all core modules. But since we go for libraryification it would mean that each library module won't be able to exist in isolation since it depends on a global struct that includes other components' configs too. But to relax this dependency library components would declare their own config traits as formerly proposed.

**Comment by matklad** [comment]
The new fine-grained config pattern we use I think covers most of the things here. I'll open a separate issue for generating docs.
