### ISSUE TITLE
Disable deduced types or make it on-hover only

### ISSUE THREAD

**Issue by shamatar** [rust-analyzer/rust-analyzer#3267]
May be it’s a question of getting used to something, but by-default displayed type annotations after “let var” statements are verbose and make it difficult to edit the variable name (cursor jumps to the end on the type hint if it’s past the last symbol). There is no place in the documentation how to disable it, and extension settings do not give any hint.

**Comment by SomeoneToIgnore** [comment]
I think you're looking for the `display inlay hints` setting.
Surprisingly, there's no documentation about that indeed, I'll add some shortly, thank you.

**Comment by matklad** [comment]
I'd also like to expand a bit on our philosophy for default settings: in general, we prefer to enable all bells and whistles by default, because that helps with **discoverability**. 

If a particular feature annoys you, it usually is straigforward to look at the docs for the way to disable it (if it is actually documented, oups :) )

OTOH, if you would love to use a feature, but do not know that it exists in the first place, you probably won't even try to find it in the docs.

I am contemplating (long-term) about having two presents for settings:

* new user, where everything is enabled by default and is displaied via GUI elements
* expert, where we keep everything accessible by a shortcut, but minize the amount  of GUI elements.

**Comment by shamatar** [comment]
@matklad Thank you for a response. The problem is while some “inlay” (maybe inline is more intuitive?) features are good such as parameter name hints, current implementation of type hints after “let x” statement provides very strange behavior when cursor jumps to the end of the type hint instead of the end of the variable name that makes a lot of distraction and visually misguiding.

**Comment by SomeoneToIgnore** [comment]
Yes, unfortunately, this is the best solution we have currently for the type hits, the reasoning behind it is described in the documentation now (see the PR that closed the issue).

We have [another issue](https://github.com/rust-analyzer/rust-analyzer/issues/2876) for toggling the different categories of hints separately, hope this will help you when gets implemented.

**Comment by timkofu** [comment]
In my case, I also unchecked `Whether to show function parameter name inlay hints at the call site.`

**Comment by randal923** [comment]
I also turned off `Enables the inlay hints in the editor.`

**Comment by hraftery** [comment]
Turning off `Inlay Hints > Parameter Hints` and `Inlay Hints > Type Hints` did the trick for me. Otherwise the jumpy x-alignment was too distracting as I tried to read and edit what I've just written.

But I'd like to call attention to the second part of the original issue: "or make it on-hover only". I'd hate to actually **lose** these hints, which are really valuable *when you want them*. Is there a way to display them without the associated cursor movement and text x-direction movement issues?

I think the existing hover text might actually be sufficient - hovering over the function shows the function parameter names, and hovering over a variable shows its type. So I _think_ nothing is lost, but I'm new here so I hope I haven't undone the great benefits of this plugin.

**Comment by Wxh16144** [comment]
@hraftery As far as I know this plugin is fully supported, here is my configuration:

```jsonc
// ...
"rust-analyzer.inlayHints.typeHints.enable": false, // 关闭类型提示
"rust-analyzer.inlayHints.parameterHints.enable": false, // 关闭参数提示
//..
```

**Comment by matklad** [comment]
https://code.visualstudio.com/updates/v1_67#_toggle-inlay-hints might help

**Comment by mrcampbell** [comment]
Perhaps related: the "7 Implementations" is from "Code Lens", and the VS Code Setting JSON key is `"rust-analyzer.lens.enable": false`, to disable it.
