### ISSUE TITLE
Editing a rust file from outside the current workspace entirely blocked by RA.

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#3286]
I had one particular folder open which contains a rust project. Then a beginner sent me a `main.rs` file of their attempt at a Rust version of some C++ code. I opened the single file from my downloads folder and I was unable to edit the file.

To be clear, I don't mean that RA failed to provide help and I had to continue without it (which would be acceptable). I mean that I couldn't even press "enter" and add a newline to the file because every single input triggered a new "Rust file outside current workspace is not supported yet." error. I had to disable the plugin entirely and reload the program with the plugin off just to be able to edit the `main.rs` file.

Please, in the mean time, at least make keyboard edits pass through to the file normally so that a person can at least edit the file they have open (even if RA can't provide any help while they do it).

**Comment by Veetaha** [comment]
Thanks for the issue! We are aware of the `onEnter` (enhanced typing) feature not working as intended (#3013). I am already investigating the ways to reintegrate it with vscode so that it fits naturally. In the meantime you might want to remove the enter keybinding as described by me in the linked issue.
