### ISSUE TITLE
Establish cron-based nightly releases

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3402]
We have a [release](https://github.com/rust-analyzer/rust-analyzer/blob/96eca8a1abd79840b9040250db9d1e65ec663b0e/.github/workflows/release.yaml) workflow which is kicked "manually" when I push to the `release` branch. We should supplement it with a nightly workflow that runs at midnight. There are two goals here:

* make it easier for users to follow the bleeding edge,
* make sure that release process "just works" and doesn't require manual intervention; running releases once per week is not frequent enough to address regressions. 

Some notes:

* we should share the same workflow file for both nightly & weekly releases
* VS Code extensions don't have nightly/stable channels, so we should just publish a separate `rust-analyzer-nightly` extension
* we ideally, we should have just one tag for nightly releases
* however `create-release` action can't `delete-release`, d'oh. There was a fork of it that could though, we should use it (pinning the action with SHA hash or forking it, because actions are not frozen by default).

**Comment by Veetaha** [comment]
I know `cpp-tools` extension has a nightly release channel, we could learn from them...

**Comment by Veetaha** [comment]
[They download `.vsix`](https://github.com/microsoft/vscode-cpptools/blob/e0253a5f157d6aeb474dbdc973fa00aad1a03399/Extension/src/LanguageServer/extension.ts#L839) according to the updates channel and [replace it with the extension itself I guess](https://github.com/microsoft/vscode-cpptools/blob/e0253a5f157d6aeb474dbdc973fa00aad1a03399/Extension/src/LanguageServer/extension.ts#L623)
Also, note that they have platform-specific `.vsix` releases (i.e. binaries are bundled inside of `.vsix`)

**Comment by Veetaha** [comment]
@matklad should we use only one github release for nightly build? I.e. we delete the release and create it once again but from current master branch? Also do we put a `git tag nightly` on commits?

**Comment by matklad** [comment]
I think it makes sense to have one release, and one moving tag

**Comment by matklad** [comment]
Yeah, as much as I hate it, I guess we'll need to implement the "download vsix and update yourself" trick: you can't publish plugins with `proposedApi: true`, but a major benefit of nightlies is using propsed apis....

**Comment by Veetaha** [comment]
Okay, this is the VSCode's fault, the workaround is what we are left with

**Comment by matklad** [comment]
Status: nightly releases work, we now need support in the front-end to actually **use** those nightlies without installinng them manually.

**Comment by Veetaha** [comment]
Sure thing, I'd like to drive this on frontend!

**Comment by Veetaha** [comment]
# Investigation
Having looked at `vscode-cpptools` releases I see the following:
* `cpptools` [publishes their `insiders` outside of any fixed schedule](https://github.com/microsoft/vscode-cpptools/releases)
* `cpptools` [relies on semver version when selecting the `insiders` build](https://github.com/microsoft/vscode-cpptools/blob/d3020a39e99bbfdd2ef4ce86e963aef954d30466/Extension/src/githubAPI.ts#L183-L185)
* `cpptools` [suggests the user to use `insiders` if she doesn't already and polls for updates each hour](https://github.com/microsoft/vscode-cpptools/blob/d3020a39e99bbfdd2ef4ce86e963aef954d30466/Extension/src/LanguageServer/extension.ts#L465-L470)
* `cpptools` [self-overrides the extension via downloading `.vsix` and installing it](https://github.com/microsoft/vscode-cpptools/blob/d3020a39e99bbfdd2ef4ce86e963aef954d30466/Extension/src/LanguageServer/extension.ts#L828)

I would also want to elaborate on some invariants I suppose we need to maintain (according to my experience at `rust-analyzer`)
* The extension **never** issues requests via the network without notifying the user (`cpptools` trespasses this)
* `rust-analyzer` uses date-based version naming

# Proposal
## Selecting the update channel and/or binary path
I suggest two options
* We contribute `"rust-analyzer.updateChannel": "stable" | "nightly"` config to `settings.json`
  This way we maintain backward-compat and provide good UX (i.e. the setting is declared as an enum so the user is aware of the two possible values).
  However, this means that `updateChannel` and `serverPath` are mutually exclusive (that @matklad proposed to avoid https://github.com/rust-analyzer/rust-analyzer/issues/3073#issuecomment-585249928) or otherwise just consider explicit `serverPath` to take precedence.
* We reuse `"rust-analyzer.serverPath"` and make it three-state, namely
    * `stable` (default) - we ensure the stable release extension and prebuilt binary version installation
   * `nightly` - we ensure the nightly extension and prebuilt binary version installation
   * `/explicit/path` - we use the binary supplied by the user disregarding anything else
However, I can't think of the best name for this config property, since calling it just `rust-analyzer.server` seems odd since this determines not only the version of the server but the frontend altogether.

## Pop-up message
* We contribute `"rust-analyzer.alwaysDownloadUpdate": true | false` config to `settings.json` that determines whether we show the `Download now` pop-up dialog each time before downloading the binary/vsix and use its value as an answer.
* The pop-up now additionally proposes `Download now (nightly)`. We persist this choice to the global `settings.json`.
* We could add `Download now (nightly) (always)`, `Download now (always)` and `No (always)` buttons to the pop-up message and modify the global `settings.json` but it complicates the UI with 6 buttons instead of 3 (I wish we could add a checkbox here, but there is no API for that...)

## Frontend versioning
* To detect the `nightlyness` of the frontend I suggest two options:
    * We check for `"useProposedApi": true` in `package.json` (not very evident and stable)
    * We add `-nightly` suffix to the version in `package.json`. I also suppose we have to ensure that the version of `nightly` is greater than the one available in the marketplace. I guess we can change `dev` to `nightly` suffix in `package.json` and ship it as is for nightly releases.
https://github.com/rust-analyzer/rust-analyzer/blob/aff82cf7ac172f213cb5dcca637cb2c5332294c1/editors/code/package.json#L8-L9

## Implementation details
* We save not only the release name, but the `published_at` date to the `globalStorage`
* When we detected that the frontend is `nightly` we need to check if there is a new nightly release available. The easiest solution is to fetch release info from `github.com` and compare its date with the one saved to `globalStorage`, however, this might mean using the network without user's permission or spamming info messages about checking for updates each time the extension is started which also adds some overhead (maybe another `dontAskMeAgain` option).
* Another option would be to ship the nightly binaries in `.vsix` itself, but that would mean that the `nightly` frontend implementation would deviate from `stable`. And we would need to duplicate the binaries in `.vsix` packages and outside of them in the `nightly` release in order to let users of non-vscode editors download them apart from `.vsix` .

## Downgrading from nightly to stable
Once the user changed from `nightly` to `stable` we propose her to uninstall the extension and install it again, maybe even use one of 
* `workbench.extensions.action.reinstall`
* `workbench.extensions.action.install.specificVersion`
(I am not sure they are public, will need to investigate, but that's not very important)

@matklad do you have some thoughts on the preferred options above or maybe other approaches in mind?

**Comment by Veetaha** [comment]
Some more thoughts:
`Download now (nightly)` button would be deceiving to some degree, because it won't install the nightly server binary right away, it will install the nightly extension that in turn will propose to install the binary.

**Comment by matklad** [comment]
>"rust-analyzer.updateChannel": "stable" | "nightly"

I like this

>We add -nightly suffix to the version in package.json

I like this as well. Since we are not publishing nightly, we can actually do this now

>To avoid requests we may heuristically propose to update the currently nightly if the current nightly version was published more than 25 hours ago 

I like this: I wondn't worry about false positves until users complain :D

>The pop-up now additionally proposes Download now (nightly).

Why do we need it? It think just having a config in settings.json for channel should be enough?

**Comment by Veetaha** [comment]
Agree on not having the `Download now (nightly)`. I was just trying to mimic `vscode-cpptools` behaviour. [They propose to switch to nightlies and if the user rejects they never ask again](https://github.com/microsoft/vscode-cpptools/blob/d3020a39e99bbfdd2ef4ce86e963aef954d30466/Extension/src/LanguageServer/extension.ts#L768-L787). I guess this is unnecessary as per you.
