### ISSUE TITLE
Should we look at async for rust-analyzer?

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3421]
I ran across https://github.com/ebkalderon/tower-lsp from https://github.com/gluon-lang/gluon_language-server/issues/26#issuecomment-592558512 and it looks intriguing.

**Comment by matklad** [comment]
No, we have dozens requests per second at most, there's no reason to not use blocking APIs.

**Comment by ebkalderon** [comment]
For context, `tower-lsp` only uses async Rust because it is a generic LSP library which aims to eventually expand to include a TCP transport in addition to `stdio`, which is another popular transport used by some language servers. If `rust-analyzer` aims to stick with a `stdio` transport for the forseeable future, then there is indeed no reason to adopt a non-blocking API.

**Comment by matklad** [comment]
Yeah, rust-analyzer is a client, and we deliberately choose to work with with studio. But even if we chose tcp, I think that wouldn’t be different? Like, we would just do blocking calls on the socket.

**Comment by ebkalderon** [comment]
Sure, you definitely could, and there's nothing wrong with that! I chose to use async/await since it provides an ergonomic way to write synchronous-looking code that doesn't immediately block the server from processing new requests or notifications while an RPC handler is awaiting a response to some other unrelated server-to-client request. You can also achieve the exact same level of responsiveness with no async/await using a few dedicated threads, no problems there either. 😄 

Other factors specific to `tower-lsp`: we build on the `tower-service` abstraction to make the language server more composable and transport-agnostic, and the API is pretty firmly futures-based. The underlying `jsonrpc-core` library is asynchronous as well, so exposing async/await for user-provided RPC handlers in `tower-lsp` is also a convenient fit there.
