### ISSUE TITLE
Inlay hints confuse matching bracket highligher

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#3453]
tldr:
![wasmtime-1583336971580](https://user-images.githubusercontent.com/3784017/75897133-a3732c80-5e6a-11ea-96b4-f01a9ba393d2.gif)

Also note that its currently impossible to put the cursor right after `(`, for example, to add another parameter before current one. If it's not related to this issue then I'd file another one specifically for cursor movement.

Revision 66ec6bd.

**Comment by SomeoneToIgnore** [comment]
This is a limitation we have due to the hints being implemented via VSCode [`decorations`](https://vscode.rocks/decorations/).

Before your issue, we had a number of reports (for example https://github.com/rust-analyzer/rust-analyzer/issues/1623) about the weird caret positioning, but this is the first about the highlighting.

Is it true that the `Match Brackets` setting and functionality is something that VS Code implements and provides?

If so, we should report the highlighting issue to their repo.
As for the caret position and improving inlay hints in general, here's the proper (long and demanding) way to do this: https://github.com/rust-analyzer/rust-analyzer/issues/2797

I've created a PR to update the docs describing the limitations: https://github.com/rust-analyzer/rust-analyzer/pull/3468

**Comment by bjorn3** [comment]
> but this is the first about the highlighting.

I noticed this too, but didn't consider this important enough to create an issue.

**Comment by Veykril** [comment]
Works fine with the native inlay hints now
