### ISSUE TITLE
Allow to disable `N implementations` header on data types

### ISSUE THREAD

**Issue by suhr** [rust-analyzer/rust-analyzer#3511]
It is quite annoying.

**Comment by matklad** [comment]
https://stackoverflow.com/a/34371578

**Comment by nepp2** [comment]
@matklad This solution isn't great for me, because disabling code lens also gets rid of the `Debug | Run` option that appears above the main function. I can't find any other way to invoke these commands, without trying to recreate them as tasks or launch configurations.

Am I missing something? Thanks.

**Comment by matklad** [comment]
> I can't find any other way to invoke these commands, without trying to recreate them as tasks or launch configurations.

There's an action for this:

![image](https://user-images.githubusercontent.com/1711539/81431173-0336ce00-9161-11ea-82d8-9ee7be3f1fcd.png)

FWIW, I think it's fine to have `rust-analyzer.lens` config section which switches each specific lens on or off.
