### ISSUE TITLE
No completetion for HashSet with _

### ISSUE THREAD

**Issue by davemilter** [rust-analyzer/rust-analyzer#3547]
For such code:
```rust
use std::collections::HashSet;

fn main() {
    let x  = vec![1, 2];
    let mut y = HashSet::<i32>::new();
    y.insert(2);
    let x: HashSet<_> = x.iter().map(|x| x +1).collect();
    x.d<CURSOR_HERE>
}
```

I can not see "difference" completetion:
![hash_set_with_](https://user-images.githubusercontent.com/26097083/76322800-e1ea6a80-62f4-11ea-97af-7b0837d6ec42.png)

But if I specify type via:
```rust
let x: HashSet<i32> = x.iter().map(|x| x +1).collect();
```
all works just fine.

`_` instead of type not implemented yet?

**Comment by kiljacken** [comment]
We probably can't infer the type of the value in the HashSet due to rust-lang/chalk#234

**Comment by flodiebold** [comment]
That shouldn't prevent us from providing completions for `HashSet` methods :thinking:

**Comment by kiljacken** [comment]
We might not be hint-ing properly when there's a placeholder inside the type hint?

**Comment by flodiebold** [comment]
The placeholder just introduces a type variable, which we should be handling fine. If I had to guess, it might be that since we're more strict about matching the self type for the impl recently, it might not be matching because there's an unknown type in there when we're doing completion (during type inference, it will still be a variable).
