### ISSUE TITLE
Uncommenting doesn't update syntax highlighting

### ISSUE THREAD

**Issue by jkelleyrtp** [rust-analyzer/rust-analyzer#3590]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/10237910/76674580-766bfb80-6587-11ea-9ae2-9c7361b4d0e5.png">

Happens to me consistently

**Comment by jkelleyrtp** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/10237910/76674604-afa46b80-6587-11ea-9ea4-eee8088f3d10.png">
And cloning the line downwards is really unhappy.

**Comment by max-frai** [comment]
I had the same issue, all this problems are resolved with new syntax highlighting feature. Just search issues for it.

**Comment by Veetaha** [comment]
Unfortunately we don't support `highlightingOn` feature anymore. It is deprecated in favour of the new, but not yet stable `semantic tokens` LSP feature. To use it [add](https://github.com/rust-analyzer/rust-analyzer/issues/3452#issuecomment-594613065) the following to your `settings.json`:
```json
{
    "rust-analyzer.highlighting.semanticTokens": true
}
```
However, note that you will need to run `vscode-insiders` to be able to use this feature. Otherwise, if you are on stable `vscode` you might turn off the old highlighting and wait untill `semantic tokens` are stabilized.

**Comment by matklad** [comment]
Yup, this probably won't be fixed in the old engine.
