### ISSUE TITLE
Nightly releases shouldn't be out of date with stable

### ISSUE THREAD

**Issue by DianaNites** [rust-analyzer/rust-analyzer#3609]
Right now the nightly auto-update channel can't be used because the nightly is out of date. Right now, including auto-update, 3 of the features/fixes in the changelog were merged after the last nightly release, and this this could be a weekly problem where nightly users are a day out of step with (newly released) stable ones, depending on when stuff is merged.

I propose that either a new nightly be released when a stable is, separate from the normal daily schedule, or a more recent stable be considered "nightly" for auto-update purposes

**Comment by matklad** [comment]
Yeah, ideally a weekly release should be just an upgraded nightly. The problem is that (due to vscode marketplace not supporting channels and proposed features for published extensions) the relases for nighlies and stable differ, so we can't just do an upgrade. 

Doing the reverse, and publishing nightly when we publish stable should in theory work, but it practice it will run afoul of our versioning scheme (we use date as a version). We probably need to look into using build counter as a version...

**Comment by Veetaha** [comment]
Just making nightlies to be published the same (`hour:minute`) or at least close to weekly release time will alleviate the problem by shortening the gap.

The workaround of publishing the weekly release as nightly will break our 25 hours heuristics :sweat_smile: 

Anyway, I believe that the perfect solution is artifacts promotion. Maybe we should not build the weekly release from the fresh `master` but instead copy the current nightly (though this is not how it is done in real life ;0)?

**Comment by matklad** [comment]
We've switch from hacky date based versions to build number based versions, so now we can build nightlies faster than once per day.

**Comment by TimoFreiberg** [comment]
I think this can be closed with #3875?
