### ISSUE TITLE
"Fill match arms" assist removes comments

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#3687]
We need to preserve the useful trivia already located in the `match` body, otherwise, the assist totally erases it.
![bug](https://user-images.githubusercontent.com/36276403/77271051-54c0f180-6cb6-11ea-828b-8d63d9748000.gif)

Also, as a side note, it would be better if the match arms body were curly braces because I frequently find myself changing the parentheses to curlies in order to start writing the match arm body.

**Comment by matklad** [comment]
Impl notes: instead of [replacing](https://github.com/rust-analyzer/rust-analyzer/blob/baa11d52f45fed76a65863c64938e43443bb9bb8/crates/ra_assists/src/handlers/fill_match_arms.rs#L70-L73) the whole `MatchArmList`, we should "append" new arms. This should works similar to [ItemList::append_items](https://github.com/rust-analyzer/rust-analyzer/blob/baa11d52f45fed76a65863c64938e43443bb9bb8/crates/ra_syntax/src/ast/edit.rs#L49-L58). 

That is, in that edit.rs file we should add

```rust
impl ast::MatchArmList {
    #[must_use]
    pub fn append_arms(&self, arms: impl IntoIterator<Item = ast::MatchArm>) -> ast::MatchArmList {

    }
}
```

**Comment by matklad** [comment]
(As a general design note, all assists should prefer to copy/move/append existing ranges of syntax nodes, written out by the user, rather than trying to construct fresh nodes)
