### ISSUE TITLE
{unknown} type deduced for a function pointer with omitted return type stored in a struct

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#3852]
rust-analyzer version: nightly (e300e1e)

Reporduction:
```rust
struct Vtable {
    method: fn()
}

fn main() {
    let vtable = Vtable {
        method: || {}
    };
    let m = vtable.method;
}

```
<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/36276403/78473459-95eee200-7749-11ea-9f7f-b12d83de2256.png)

</details>

**Comment by flodiebold** [comment]
The relevant code is here:
https://github.com/rust-analyzer/rust-analyzer/blob/e300e1e8d8f4de273d52fa62762ed14e8a7f96bb/crates/ra_hir_def/src/type_ref.rs#L96
Instead of using `from_ast_opt`, we should use `TypeRef::Tuple(Vec::new())` in the `None` case. We can add a test for this [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir_ty/src/tests/simple.rs).
