### ISSUE TITLE
Code completion doesn't work in match guards

### ISSUE THREAD

**Issue by DianaNites** [rust-analyzer/rust-analyzer#3980]
Example:

```rust
let c: char = 'a';
match c {
    a if c.<|>
};
```

**Comment by matklad** [comment]
Don't know immediately what would be the problem here -- we do process guards during lowering and type-inference. I'd probably start debugging this with placing `dbg!` when [creating context](https://github.com/rust-analyzer/rust-analyzer/blob/b495e56b0d3f7a72494d002a69440563e8394574/crates/ra_ide/src/completion/completion_context.rs#L60-L64)  and doing [completion itself](https://github.com/rust-analyzer/rust-analyzer/blob/b495e56b0d3f7a72494d002a69440563e8394574/crates/ra_ide/src/completion/complete_dot.rs).
