### ISSUE TITLE
Syntax highlighting malfunctions with raw string literals

### ISSUE THREAD

**Issue by ExoticMatter** [rust-analyzer/rust-analyzer#4048]
When raw string literals that use ##s appear in attributes, syntax highlighting gets messed up. Example:
![Screenshot_20200420_000443](https://user-images.githubusercontent.com/7787686/79710171-8f5c8080-829a-11ea-9d3c-d84770132b34.png)

Literals outside of attributes are not affected.

Editor: VSCode

**Comment by matklad** [comment]
Hm, can't trivially reproduce this:

![image](https://user-images.githubusercontent.com/1711539/79726028-7085da80-82ea-11ea-9206-0294b953b883.png)

Not sure what might be the problem.

**Comment by ExoticMatter** [comment]
@matklad It seems that it only occurs when the literal contains an odd number of quotes.
![Screenshot_20200420_130314](https://user-images.githubusercontent.com/7787686/79773093-5efefb80-8307-11ea-9a86-5d2746b07082.png)

**Comment by matklad** [comment]
Mystery solved! 

The problem is with the build-in textmate grammar for rust:

https://github.com/microsoft/vscode/blob/master/extensions/rust/syntaxes/rust.tmLanguage.json

I get the following if I disable rust-analyzer plugin:

![image](https://user-images.githubusercontent.com/1711539/79849374-aa2a1480-83c2-11ea-807a-741077f55dbd.png)

OTOH, if i enable rust-analyer and [minimal rust](https://github.com/rust-analyzer/minimal-rust) (empty grammar for rust), I get the following:

![image](https://user-images.githubusercontent.com/1711539/79849477-d180e180-83c2-11ea-8074-3555b7c82351.png)

So I believe the issue should be reported upstream, against vscode repository.
