### ISSUE TITLE
Format string literal syntax highlighting is broken for escapes and interpolations simultaneously

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#4138]
cc #4006, @ltentrup

![image](https://user-images.githubusercontent.com/36276403/80282441-2ce00600-871a-11ea-9e9c-9d620d334411.png)

As you can see, the string is bold starting from the escape sequence up until the first placeholder symbol.

This happens only inside of format strings as far as I can tell
![image](https://user-images.githubusercontent.com/36276403/80282487-7cbecd00-871a-11ea-99fb-78233861f6ef.png)

**Comment by ltentrup** [comment]
Where does the highlighting for the escape string come from? It is not implemented in https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide/src/syntax_highlighting.rs where the logic for the format specifier is implemented.

**Comment by Veetaha** [comment]
Hmm, this is strange, if you take a look with the inspector you won't see where the bold styling comes from... Can't it be vscode bug? Can you reproduce it in your editor?
![image](https://user-images.githubusercontent.com/36276403/80282889-8f3a0600-871c-11ea-8040-8dcb90dbbfe8.png)

**Comment by ltentrup** [comment]
I just checked with the latest nightly, there is no escape sequence highlighting on my machine:
<img width="246" alt="Bildschirmfoto 2020-04-28 um 09 25 01" src="https://user-images.githubusercontent.com/201808/80459245-60957880-8932-11ea-95b8-0f133346c825.png">
Maybe this is related to another extension or VSCode setting?

**Comment by ian-h-chamberlain** [comment]
I have been experiencing a similar issue, which I thought was caused by some interaction between rust-analyzer and another extension I have installed. However, I can reproduce when rust-analyzer is the only extension enabled as well.

Initial state while window loads and rust-analyzer still starting up looks like this
![Screen Shot 2020-06-15 at 18 46 33](https://user-images.githubusercontent.com/11131775/84713336-c5d01800-af38-11ea-9fe1-92868e1118ed.png)

This is expected, I think, as the semantic highlight has not been initialized yet?

Then, once it loads and I type a bit, this happens:

![recording](https://user-images.githubusercontent.com/11131775/84713629-75a58580-af39-11ea-96a3-5d81b545a4a4.gif)

It seems like once semantic highlighting starts something changes. Strangely, all the output from the inspector window seems to be unchanged:


## Escape before
![escape_before](https://user-images.githubusercontent.com/11131775/84713971-4d6a5680-af3a-11ea-93e4-55ab95211372.png)

## Escape after
![escape_after](https://user-images.githubusercontent.com/11131775/84713968-4d6a5680-af3a-11ea-9833-d8415fb22ee3.png)

## Format string before
![format_before](https://user-images.githubusercontent.com/11131775/84713973-4e02ed00-af3a-11ea-9f8a-8f8498748a0e.png)

## Format string after
![format_after](https://user-images.githubusercontent.com/11131775/84713972-4e02ed00-af3a-11ea-9807-8755e223b072.png)

**Comment by ltentrup** [comment]
Does this issue persist in the latest nightly? There is now support for highlighting escape sequences (although it has to be enabled manually)

**Comment by ian-h-chamberlain** [comment]
@ltentrup yes, it works as expected for me now, thank you! I didn't have to enable anything specific, it seemed to activate alongside the rest of semantic syntax highlighting. Is that expected?

**Comment by ltentrup** [comment]
No, I did not expect escape sequences to be highlighted as we introduced a custom/non-standard semantic token `escapeSequence`.
If you do not style `escapeSequence` manually in your settings.json it should just style as a string.

**Comment by ian-h-chamberlain** [comment]
It looks like the `escapeSequence` allows the default semantic highlighting to kick in, instead of just treating the token as as string?
Compare this inspector output to the one I posted above:
![Screen Shot 2020-06-18 at 12 42 07](https://user-images.githubusercontent.com/11131775/85048456-54bf7900-b161-11ea-86a5-a58dfa03f7ab.png)

In any case it now looks like it did before, so I would consider this issue resolved. Thanks again!

**Comment by lnicola** [comment]
Sounds like this was resolved, please shout if there's still something to do here.
