### ISSUE TITLE
Rust-Analyzer in VsCode Obstructs View

### ISSUE THREAD

**Issue by mitsuhiko** [rust-analyzer/rust-analyzer#4164]
I'm not sure how to best describe the problem but rust-analyzer is really hard to use with vscode in many situations because as I type I keep getting hints I really do not care about. Best to be explained here:

![image](https://user-images.githubusercontent.com/7396/80320978-fa1d3700-8819-11ea-9a56-3ad9891bae8e.png)

The `new_with_span` is from a function call surrounding a match expression. I do not care about it at all here. Code in question simplified:

```rust
return Some(Event::new_with_span(match ... { ... }));
```

(Using vscode with the vim extension)

**Comment by matklad** [comment]
The following settings might help:

```json
// don't render the whole `pub fn` header
"rust-analyzer.callInfo.full": false,
// don't activate parameterHints automatically
"editor.parameterHints.enabled": false,
```

This is the settings I personally use, because the default UI for hints in VS Code is [pretty horrible](https://github.com/microsoft/vscode/issues/92174). 

However, I've noticed that I still do get hints on completion, when we forcefully trigger them. Seems like we should honor the `editor.parameterHints.enabled` setting, or have a separate toggle here...

**Comment by lnicola** [comment]
These depend on the client and are all configurable in Code. Closing.
