### ISSUE TITLE
VSCode plugin only works in main.rs

### ISSUE THREAD

**Issue by aecorredor** [rust-analyzer/rust-analyzer#4177]
I'm going through https://github.com/LukeMathWalker/build-your-own-jira-with-rust and had been previously using RLS. I just switched to rust-analyzer and the plugin is only working in the `main.rs` file. In any other file it doesn't work at all. The `run` links are in the file, but there is no auto-completion nor hints (hover or inlay).

I went through the manual and first uninstalled RLS and restarted VSCode before even installing `rust-analyzer`.

**Comment by lnicola** [comment]
It works for me in most files:

![image](https://user-images.githubusercontent.com/308347/80452802-aef54800-892f-11ea-9cd5-5639e94badf3.png)

![image](https://user-images.githubusercontent.com/308347/80452886-de0bb980-892f-11ea-952c-ab9182ae87a0.png)

But not in `jira-wip/src/koans`, because those files are not in the project structure, so `rust-analyzer` doesn't know about them. It looks like `koans-framework` fills in the initially empty `path_to_enlightenment.rs` with `include!` directives like `include!("koans/00_greetings/00_greetings.rs");`. We might have some bugs in our handling of `include!`, because that doesn't work great, CC @edwin0cheng.

A workaround is to replace the `include!` with something like

```rust
#[path = "koans/00_greetings/00_greetings.rs"]
mod greetings;
```

![image](https://user-images.githubusercontent.com/308347/80453604-44dda280-8931-11ea-8041-e9d2b6edc03d.png)

This doesn't seem to break the `koans` tool, so it still works.

**Comment by lnicola** [comment]
More clearly, the issue with `include!` is that you can have:

```rust
//- lib.rs
mod m1 {
    struct S {
        foo: i32,
    }

    include!("fun.rs");
}

mod m2 {
    struct S {
        foo: String,
    }

    include!("fun.rs");
}

//- fun.rs
fn frob(s: S) {
    let _ = s.foo; // what type does this have?
}
```

**Comment by lnicola** [comment]
Filed https://github.com/LukeMathWalker/build-your-own-jira-with-rust/issues/33.

**Comment by matklad** [comment]
Yeah, supporting code *inside* includes properly is kinda hard. That's on the radar, but is not a top priority at the moment. I am going to close this issue, as there's nothing immediatelly actionable here.

**Comment by ycjcl868** [comment]
same issue + 1

**Comment by maxfetz** [comment]
still the same issue

**Comment by curiouscod3** [comment]
same issue here. It only works in main.rs!

**Comment by danielarcini** [comment]
I would really like it if it also worked outside of my main.rs file. Did anyone find a work around to this? been 2 years and still no fix.

**Comment by lnicola** [comment]
You need to set up a proper module structure. If your code compiles, please provide an example.

**Comment by matklad** [comment]
Idea: we can switch ra status to red if the currently opened file is .rs unknown to ra? Would also help https://github.com/rust-lang/rust-analyzer/issues/13226

**Comment by ben-xshen** [comment]
not so difficulte i found directly declare the mod, and keep the mod name same as the filename, then u the mod can get the code intelligence again.... to tell the truth i don't know why the plugin is designed like such, or they just wanna to reduce the possibility of the no-used-declaration and tell u "hey buddy, u need to use it first or i cannot provide the support for u"?

![image](https://github.com/rust-lang/rust-analyzer/assets/144872680/eb364a38-1c87-4190-97fd-b18846950885)

![image](https://github.com/rust-lang/rust-analyzer/assets/144872680/147f86f0-9957-4b4b-a5ee-5fd4ad7b7343)
