### ISSUE TITLE
Finding references/callers of associated functions doesn't work across module boundaries

### ISSUE THREAD

**Issue by sdroege** [rust-analyzer/rust-analyzer#4188]
```rust
mod foo {
    pub struct Foo;

    impl Foo {
        pub fn new() -> Foo {
            Foo
        }
    }
}

fn main() {
    let _f = foo::Foo::new();
}
```

"Go to definition" on the `new()` call inside `main()` correctly jumps to the definition of the function. From there finding references (i.e. callers) doesn't yield any results though.

When removing the `foo` module it finds the caller correctly. Similarly the same works fine for non-associated, free-standing functions inside the `foo` module.

**Comment by matklad** [comment]
I *think* this is because our privacy handling in find usages is just wrong. The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/da1f316b0246ce41d7cb8560181e294089f06ef3/crates/ra_ide_db/src/search.rs#L128-L152

it might have some other root cause, but visibility being broken would be my first guess.

**Comment by kjeremy** [comment]
This is also the reason behind #2889 and#3869

**Comment by matklad** [comment]
And likely #4237
