### ISSUE TITLE
change visibility asssit should work for fields of tuple structs

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4206]
This works:

![image](https://user-images.githubusercontent.com/1711539/80592063-1807b900-8a1f-11ea-9b58-ac8fa82ee21f.png)

This doesn't, but it should:

![image](https://user-images.githubusercontent.com/1711539/80592105-2c4bb600-8a1f-11ea-8b34-29828b90c6c2.png)

Relevant code is here: https://github.com/rust-analyzer/rust-analyzer/blob/c3dfeba165e4d13821bba34d21cdc5242ea2fa71/crates/ra_assists/src/handlers/change_visibility.rs#L32

**Comment by Jesse-Bakker** [comment]
While looking into this, I did not fully understand something.

The current assist only works when triggered from the name of a struct field and not from its type. What is the reason for looking up the ast node as an `ast::Name` instead of `ast::RecordFieldDef` and using `field.name()?.syntax().text_range()` as assist target? If I understand correctly the latter would allow the assist to be triggered from anywhere in the field definition.

**Comment by matklad** [comment]
In general, it's better to trigger assists in as narrow context as possible, as irrelevant assits are harmful. Seeing a pop-up with 100 assists is pretty useless! For visibility on named fields, name seems the appropriate narrow context. 

We also use the size of context when sorting assists -- more narrow assits are sorted first.

**Comment by matklad** [comment]
(for tuple, we don't have a better choice than to trigger assist on the whole type.

**Comment by Jesse-Bakker** [comment]
That makes sense. Thank you!
