### ISSUE TITLE
`bitflags!`-generated struct is not completed

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#4213]
For example here:

```rust
use bitflags::bitflags;

macro_rules! m {
    ($v:vis struct $name:ident : $t:ty {
        $( const $valname:ident = $val:expr; )*
    }) => {
        $v struct $name($t);

        impl $name {
            fn new() -> $name {
                $name(0)
            }
        }
    };
}

m!(
    struct Flags: u16 {
        const V = 0;
    }
);

bitflags!(
    struct Flags2: u16 {
        const V = 0;
    }
);

fn main() {
    Fl<|>
}
```

Only `Flags` shows up, not `Flags2`.

**Comment by jonas-schievink** [comment]
Maybe due to `#[macro_export(local_inner_macros)]`?

**Comment by edwin0cheng** [comment]
Yes, `local_inner_macros` is not supported yet. We need some kind of call-site hygiene to implement it.

**Comment by edwin0cheng** [comment]
cc #3712

**Comment by edwin0cheng** [comment]
After #4234 landed, `bitflags!` are correctly inferred. however, However, bit operations (e.g. |, >>) on these flags still infer incorrectly, since we still not implemented for binary operations traits yet.

The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/fb8fb65131c8d3e6335efd401e4e83287be49357/crates/ra_hir_ty/src/infer/expr.rs#L369-L384

**Comment by lnicola** [comment]
This seems to work now. The inference problem is probably https://github.com/rust-analyzer/rust-analyzer/issues/5685.
