### ISSUE TITLE
VSCode plugin doesn't find rust-analyzer on path?

### ISSUE THREAD

**Issue by btrepp** [rust-analyzer/rust-analyzer#4262]
Hi All,

Using an arm based laptop (no native binary, and the headmelted code-oss version of vscode), the plugin installs and then suggests I compile from source.

Running the task to install the server succeeds, and it is on the path for the machine.

However, that doesn't seem to change the behaviour of the plugin, it always complains it's an unsupported platform. It implies that having the server installed should fix it, but it still complains?.

Do we need to also install the plugin from source too?. If so, might be worth updating the docs, if not, is there anyway of configuring the plugin to tell it where rust-analyzer is?. It's in the cargo bin folder, but if it's confused and I can tell it what to do that would at least get it working :)

Thanks,
Beau

**Comment by btrepp** [comment]
Almost instantly after posting I found the setting

`
{
    "rust-analyzer.serverPath": "~/.cargo/bin/rust-analyzer"
}
`
Which when set kicks it all off. Hopefully that helps someone else.

**Comment by pawurb** [comment]
FWIW for anyone finding this issue 4 years later, it's now: `"rust-analyzer.server.path"`

**Comment by albibenni** [comment]
In case it is needed a new post I'll open but since it's related I'll try.
I had the same problem, Path not synced, added the path to the settings like so:
`"rust-analyzer.server.path": "~/.cargo/bin/rust-analyzer"`
but the server is crashing, I've tried to update everything with no luck.
Just for context I do have the rust-analyzer inside the bin folder with execution privileges and on vim the completion is working fine, same rust-analyzer

**Comment by lnicola** [comment]
@albibenni you normally don't need to set that path, the server is built into the extension.

**Comment by albibenni** [comment]
@lnicola do you mean I don't have to set the path even if `Not synced`?

**Comment by lnicola** [comment]
@albibenni that sounds like something related to the VS Code Settings Sync, which doesn't have a lot of relevance to rust-analyzer.
