### ISSUE TITLE
`workspace/configuration` clarification

### ISSUE THREAD

**Issue by bstaletic** [rust-analyzer/rust-analyzer#4267]
According to [this](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/rust-analyzer/src/main_loop.rs#L626-L627), rust-analyzer basically requires `workspace/configuration` to be supported.

According to [LSP discussion](https://github.com/microsoft/language-server-protocol/issues/676), assuming I understand the comments correctly:

- The client fires a `didChangeConfiguration` notification
- The server then makes a `workspace/configuration` request

So the client side should look something like this:

    result = []
    for queried_config in request[ 'params' ][ 'items' ]:
        config_key = queried_config.get( 'section', '' )
        result.append( new_config.get( 'config_key' ) )

The request I got from rust-analyzer was:

    2020-05-02 19:33:36,178 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":2,"method":"workspace/configuration","params":{"items":[{"section":"rust-analyzer"}]}}'

1. Is this aligned with what rust-analyzer expects?
2. If so, where can I see the RA configuration options?

**Comment by kjeremy** [comment]
This is the answer I received in how this should all work (your point 1): https://github.com/microsoft/language-server-protocol/issues/676

**Comment by bstaletic** [comment]
Okay, so we're on the same page.

If I receive something like

    {"jsonrpc":"2.0","id":2,"method":"workspace/configuration","params":{"items":[{"section":"rust-analyzer"}]}}

what would be possible values for this? To be clear, this isn't asking for *complete* configuration dictionary?

**Comment by matklad** [comment]
The spec is super unclear about this, but what VS Code does is that returns all config keys nested under rust-analyzer key:

```
[Trace - 12:25:53 AM] Received request 'workspace/configuration - (8)'.
Params: {
    "items": [
        {
            "section": "rust-analyzer"
        }
    ]
}


[Trace - 12:25:53 AM] Sending response 'workspace/configuration - (8)'. Processing request took 2ms
Result: [
    {
        "diagnostics": {
            "enable": true
        },
        "lruCapacity": null,
        "files": {
            "watcher": "client",
            "exclude": []
        },
        "notifications": {
            "workspaceLoaded": true,
            "cargoTomlNotFound": true
        },
        "cargo": {
            "noDefaultFeatures": false,
            "allFeatures": true,
            "features": [],
            "loadOutDirsFromCheck": false
        },
        "rustfmt": {
            "extraArgs": [],
            "overrideCommand": null
        },
        "checkOnSave": {
            "enable": true,
            "extraArgs": [],
            "command": "check",
            "overrideCommand": null,
            "allTargets": true
        },
        "inlayHints": {
            "typeHints": true,
            "chainingHints": true,
            "parameterHints": true,
            "maxLength": 20
        },
        "completion": {
            "addCallParenthesis": true,
            "addCallArgumentSnippets": false,
            "postfix": {
                "enable": true
            }
        },
        "callInfo": {
            "full": false
        },
        "updates": {
            "channel": "stable",
            "askBeforeDownload": true
        },
        "serverPath": null,
        "trace": {
            "server": "verbose",
            "extension": false
        },
        "procMacro": {
            "enable": false
        },
        "debug": {
            "engine": "auto",
            "sourceFileMap": {
                "/rustc/<id>": "${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust"
            }
        },
        "cargo-watch": {
            "enable": true
        }
    }
]
```

So, it kinda is complete configuration dictionary. It even includes client-side specified default values, which is actively harmful, as we had to duplicate defaults between the server and the client (if we omit defaults on the client, the client fills them with type-based defaults, like false, 0, empty array, etc, instead of fully ommiting them, and this "defaults" override our defaults) . 

Also note that, although in VS Code config settings are specified using dotted keys like `"rust-analyzer.foo.bar"`, the response from vscode uses nested structs: `rust-analyzer: { foo: { bar: ... } }`

**Comment by matklad** [comment]
>If so, where can I see the RA configuration options?

I believe you don't need to know the set of all options, you need to just forward whatever user has written in the config. Unfortunatelly, there's no way to specify "config schema" in the LSP. For VS Code, we list the options [here](https://github.com/rust-analyzer/rust-analyzer/blob/89e1f97515c36ab97bd378d972cabec0feb6d77e/editors/code/package.json#L175-L410), though this list contains both options specific to typescript extension (ie, which rust-analyzer binary to use) and the options which affect the server. VS Code sends them all to the server, and we just ignore extra ones.

**Comment by bstaletic** [comment]
@matklad Thanks for the info, though this raises more questions.

> what VS Code does is that returns all config keys nested under rust-analyzer key:

Did I understand you correctly, that VSCode responds with `[ config[ 'rust-analyzer' ] ]`? If so, then I can implement that.

From what I'm reading, I'm allowed to omit whatever fields the user didn't care about and rust-analyzer will just use its defaults. In case the user didn't care about any configuration, I would only have `{}` as settings, so `setting.get( 'rust-analyzer' )` would return `None`, which gets serialized as `null`. The protocol allowed this, but is rust-analyzer okay with that?

**Comment by puremourning** [comment]
> I believe you don't need to know the set of all options, you need to just forward whatever user has written in the config.

yeah, sure, but the user needs to know, and we need to test. Where do they find out? Are they expected to read some json file in order to know what to configure?

In fairness, rust-analyser is not the only server that doesn't docuemnt its configuration. Most of the others don't either, so we have to do it for them.

New tool idea: Something which scrapes all theses irritating json files that vscode requires and actually makes human-readable docs out of them. Who's with me?!

**Comment by matklad** [comment]
>The protocol allowed this, but is rust-analyzer okay with that?

Yeah, we should handle this fine (although I didn't test this). 

>New tool idea: Something which scrapes all theses irritating json files that vscode requires and actually makes human-readable docs out of them. Who's with me?!

This ideally should be a part of the protocol I think. Something like `.configurationSchema`  in `ServerCapabilities` or something like that, so that clients can render documentation themselves:

![image](https://user-images.githubusercontent.com/1711539/80910469-ef8a0280-8d2f-11ea-82a4-1d3f66be6c44.png)

Though, generated docs would also be a nice addition. Generate config from *something* has been on my todo list for some time... Though, I'd rather make Rust struct than json file a source of truth.

**Comment by bstaletic** [comment]
> Yeah, we should handle this fine (although I didn't test this).

At the very least, rust-analyzer didn't complain about `{"result":[null]}`. For the record, I got the answers I came here for. As far as I'm concerned, the issue can be closed.

    <rant>

The protocol is so frustrating at times...
Everything we've said here, completely disagrees with the go server (for the curious, check my other opened issue with the same title). Yes, I know rust-analyzer shouldn't be concerned about gopls.

    </rant>
