### ISSUE TITLE
rust-analyzer works only in main.rs 

### ISSUE THREAD

**Issue by majiayu000** [rust-analyzer/rust-analyzer#4336]

**Comment by majiayu000** [comment]
HI!
    I have some problem with using rust-analyzer.When i write some code in the main.rs, the code completion and color works right.But when i create a lib.rs and edit it, code completion is nolonger
userful.What should I do to make it work in not only main.rs?
  Thanks!

just like the picture.
![1](https://user-images.githubusercontent.com/19658300/81149262-75b47c00-8fb0-11ea-81c7-2ecc6fe5291b.jpg)
![2](https://user-images.githubusercontent.com/19658300/81149271-79480300-8fb0-11ea-81f2-4c7ec17d8210.jpg)

**Comment by bjorn3** [comment]
Did you create `lib.rs` while the vscode window was open? If so you will need to restart it. rust-analyzer currently doesn't support dynamically adapting to changes in the workspace like adding `lib.rs` or adding a dependency.

**Comment by majiayu000** [comment]
> Did you create `lib.rs` while the vscode window was open? If so you will need to restart it. rust-analyzer currently doesn't support dynamically adapting to changes in the workspace like adding `lib.rs` or adding a dependency.

Thank you very much！It is really useful.

**Comment by vijay-pedalsup** [comment]
@bjorn3 can you explain it again in details I am facing same issue

**Comment by CaneMandarinesco** [comment]
for me, restarting vscode is not useful. even when creating files inside vscode (code-oss) i can't get intellisense to work. only main.rs has intellisense

**Comment by yo1956** [comment]
> for me, restarting vscode is not useful. even when creating files inside vscode (code-oss) i can't get intellisense to work. only main.rs has intellisense

Me too

**Comment by e1pupper** [comment]
same issue here

**Comment by MyGodItsFull0fStars** [comment]
A solution could be that in order to show code completion etc. in VSCode you need to include the files in the cargo project. Rust-analyzer does not work for all files in a directory, but works for projects (usually a Cargo project).

To include your files/directories in a Cargo project, you need to follow the [Cargo conventions](https://doc.rust-lang.org/cargo/guide/project-layout.html), and once I did that, code completion, etc did work also for other files than main.rs.

Random rust files in the same directories seem to not be part of the project, so are not analysed by the language server (which is what provides completions to the editor).
