### ISSUE TITLE
Add a test codelens for function when we detect unit tests

### ISSUE THREAD

**Issue by bnjjj** [rust-analyzer/rust-analyzer#4422]
I really would like to add a new feature to rust-analyzer. For example imagine we have a function:
```rust
fn add(a: usize, b: usize) -> usize {
    a + b
}
```

and a unit test: 
```rust
#[test]
fn test_add(a: usize, b: usize) -> usize {
    a + b
}
```

I really would love to see a codelens to let me run this unit test under the hood. But I don't know if it's feasible. I thought about 2 different ways to detect if we have a test linked to a function.

+ If functions are named like `test_thefunctionname*` with the `test` attribute we can easily consider it's a test for this function.
+ Or we can also browse in which test functions our function is used but I think it could be very heavy to compute ?

It's a proposal I don't have strong ideas or what we could do here but the fact is I'm bored each time to make some back and forth with the function and tests when I'm making some TDD. Maybe I don't know a magic shortcut to do that ? Or maybe we can find together a good solution and several iterations to solve this kind of issue.

**Comment by edwin0cheng** [comment]
> . Maybe I don't know a magic shortcut to do that 

In vscode, there is a "Rerun Last Task" command. Personally I just bind this command with a keyboard shortcut and it works quit well with TDD.

**Comment by matklad** [comment]
IntelliJ has a feature for this, "GotoRelaedSymbol", which mostly checks if the name of one class is substring of another. This works ok for Java, because everything is a class. For rust, I feel like this would be hit and miss, becuase we don't group tests into classes. 

So what I'd do here is use **Goto symbol** to navigate to test, **Run** shortcut to run it once, than **Back** to go back to function, than **Run** again to re-run, as @edwin0cheng said. 


The proposal for searching for usages is interesting, but I think is a little bit too futuristic for our current state of affairs. So, I am going to close this, as it doesn't seem immediatelly actionable, and I don't find keeping just interesting ideas to useful (though the idea is indeed a nice one!)

**Comment by bnjjj** [comment]
Ok thanks to clarify this :) and thanks @edwin0cheng for your idea, it will fit my need I think. Sorry for the noise, @matklad do you think this kind of thoughts have more their place on Zulip chat ?

**Comment by matklad** [comment]
That's not noise, that's useful, and "find all the tests that use the function" is definitelly cool and not somthing I've previously thought about :-) 

I think zulip and/or issues would work equivalently in terms of attention :)
