### ISSUE TITLE
Using Self with enum shows {unknown} type even in the simplest case.

### ISSUE THREAD

**Issue by rossmacarthur** [rust-analyzer/rust-analyzer#4454]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/17109887/81911528-bd00c500-95cd-11ea-9291-d16fb0502f98.png">

vs 

<img width="486" alt="image" src="https://user-images.githubusercontent.com/17109887/81911642-e588bf00-95cd-11ea-9d15-dd28413c8c06.png">

**Comment by matklad** [comment]
Yeah, seems like we don't handle `Self` properly. For patterns, I think the problem is here:

https://github.com/rust-analyzer/rust-analyzer/blob/62730ae30db453f53eb0c37647b5c76058eafca0/crates/ra_hir_ty/src/infer.rs#L441

Here, we want to resolve `Self::This` fully, without using type information.

For similar cases in expression context (`let _ = Self(92)` where `Self` is a tuple struct), the problem is similar:

https://github.com/rust-analyzer/rust-analyzer/blob/62730ae30db453f53eb0c37647b5c76058eafca0/crates/ra_hir_ty/src/infer/path.rs#L51

Here, `resolve_path_in_value_ns` does not understand that `Self` can be a value
