### ISSUE TITLE
[vscode] Support workbench.action.debug.start and workbench.action.debug.run

### ISSUE THREAD

**Issue by teohhanhui** [rust-analyzer/rust-analyzer#4475]
Currently, there is `Run | Debug` above `fn main() {`, which works well, but is kind of annoying as it is always visible.

It would be better if the built-in commands could be used (without configuring `launch.json`), same as what was described in https://github.com/rust-lang/rls-vscode/issues/557#issuecomment-479969903

**Comment by vsrs** [comment]
`"editor.codeLens"` in `settings.json` will disable `Run | Debug` (and `X implementations` lens for structs as well) 

It's wrong to use `workbench.action.debug.start` or `workbench.action.debug.run` since it is private vscode API. Public one is [startDebugging](https://github.com/microsoft/vscode/blob/0c4fa8a7b5f8ef2b59663b20d79df7776a697609/src/vs/vscode.d.ts#L8326) and it is used in the Debug Lens internally.

BTW, https://github.com/rust-analyzer/rust-analyzer/pull/4448 made `launch.json` configuration pretty trivial. Might be it will work for you?

**Comment by teohhanhui** [comment]
> "editor.codeLens" in settings.json will disable Run | Debug

That's the nuclear option. I do want code lens, just not this code lens (because running / debugging the program is something that the debug / run commands are for, I don't see why they should be triggered through a code lens). But it's a minor thing that I can live with.

> It's wrong to use workbench.action.debug.start or workbench.action.debug.run since it is private vscode API. Public one is startDebugging and it is used in the Debug Lens internally.

That's not what I meant at all. Let me clarify. There are different providers (I don't know what the correct term is) when you try to use the debug / run commands, including Node.js (built-in one). I understand that "debugger extensions" can add providers to that list: https://code.visualstudio.com/api/extension-guides/debugger-extension - for example, the C/C++ extension adds a provider there - it's the same idea mentioned in https://github.com/rust-lang/rls-vscode/issues/557#issuecomment-479969903

**Comment by vsrs** [comment]
> That's the nuclear option.

Agreed. We can have a separate configuration option to hide `Run | Debug`. Easy to add.

>  There are different providers...

I see. You are talking about  DebugConfigurationProvider (DCP) . There are two difficulties with them:
1. At the moment there is no way to export a debug configuration from a DCP to the launch.json.

2. There might be numerous debug targets (hundreds of tests for example) and it takes significant time to find them all and make available via the DCP. The current solution, on the other side, looks for runnables only in the current file. It is much faster.

The former scheduled to be fixed in the next vscode milestone. But the latter stops me from implementing DCP.

**Comment by vsrs** [comment]
Hmm, though it should be possible to dynamically update DCP and show only runnables from the current file. It's a DCP new feature from the April vscode (version 1.45). I'll take a stab at this.

**Comment by teohhanhui** [comment]
I'm very new to Rust, but is it not possible to just support `cargo run`? For an end user like me, it seems correct that that's what the debug / run commands should do.

**Comment by vsrs** [comment]
>  just support `cargo run`

This is exactly what `rust-analyzer.run` command does (obviously it uses `cargo test` for tests). `rust-analyzer.debug` is a bit trickier, but in the end it also uses cargo commands.

**Comment by vsrs** [comment]
> We can have a separate configuration option to hide `Run | Debug`. Easy to add.

Done in #4499

**Comment by matklad** [comment]
I believe we need API from LSP/VS Code to make this work really nice: https://github.com/microsoft/language-server-protocol/issues/944
