### ISSUE TITLE
Type inference not applied to arguments to boxed functions.

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#4481]
```
#[derive(Default)]
struct S;

fn main() {
    let s = Default::default();
    let f: Box<dyn Fn(&S)> = Box::new(|ps| {});
    f(&s)
}
```

This is valid Rust -- `s` has type `S`.

However, rust-analyzer (latest master 9322790066fe86056965332078bed74ff7f77293) cannot infer the type of `s`.

**Comment by flodiebold** [comment]
Yeah, calling closures in general isn't implemented yet -- the relevant code is here:
https://github.com/rust-analyzer/rust-analyzer/blob/9322790066fe86056965332078bed74ff7f77293/crates/ra_hir_ty/src/infer/expr.rs#L178-L191
Basically, we have to check whether the callee implements `FnOnce` and infer the signature from that if it is the case.

**Comment by adamrk** [comment]
Looks like the relevant code in rustc is here: https://github.com/rust-lang/rust/blob/4b1f86adbe41e8dd4864ca2315f43953dd503bb5/src/librustc_typeck/check/callee.rs#L60. I can take a stab at this if no one else is working on it?

**Comment by adamrk** [comment]
When digging into this I think I've come across a related, but different issue. I couldn't put @umanwizard's original code in a unit test since it needs `Box` (is there some way to get around this that I'm not aware of?), but I came up with this test exhibits the same problem:
```rust
    #[test]
    fn infer_dyn_fn_arg() {
        check_hover_result(
            "
            //- /lib.rs
            enum Option<T> {
                None,
                Some(T)
            }

            fn apply<T, F>(f: &F, x: T)
            where
                F: Fn(T),
            {
                f(x)
            }

            fn dummy(x: Option<i32>) {}

            fn main() {
                let s<|> = Option::None;
                apply(&dummy, s)
            }

        ",
            &["Option<i32>"],
        );
    }
```
When inferring the type of `apply(&dummy, s)`, the method https://github.com/rust-analyzer/rust-analyzer/blob/02f7b5d7abbab829c2a0f66cdcbb6678afb412a4/crates/ra_hir_ty/src/infer/expr.rs#L786 fails to get an obligation from `F: Fn(T)`. I think this is because resolving the path `Fn` in https://github.com/rust-analyzer/rust-analyzer/blob/02f7b5d7abbab829c2a0f66cdcbb6678afb412a4/crates/ra_hir_def/src/resolver.rs#L147 fails.

Is there somewhere we pre-load the builtin traits that's missing `Fn` and friends? Or should I maybe be adding some extra logic somewhere in `ra_hir_def` to handle them?

**Comment by flodiebold** [comment]
Sorry, I forgot to answer here -- traits like `Fn` don't exist in unit tests if you don't define them; you need to define them and put the lang attribute on them (there's some examples of this in the hir_ty tests).

**Comment by adamrk** [comment]
Cool thanks, also sorry for not updating this recently. I got distracted with some things, but I'm still working on it.

**Comment by adamrk** [comment]
I think we can close this?

**Comment by flodiebold** [comment]
Yeah.
