### ISSUE TITLE
cargo-asm integration

### ISSUE THREAD

**Issue by extrawurst** [rust-analyzer/rust-analyzer#4647]
it would be awesome if `cargo asm` could be integrated to get the `asm` of a selected function: https://github.com/gnzlbg/cargo-asm

**Comment by matklad** [comment]
I see how it would be useful for many people, but  I'd say that this is generally out of scope. rust-analyzer is focused on static analysis of code, and does not integrate with 3rd party tooling, the exceptions being:

* `rustfmt`, because we haven't yet implemented formatter on top of rust-analyzer.
* `cargo check`, because we haven't yet implmented all semantic checks correctly in rust-analyzer.
* `cargo`, because that's a de-facto build system, and we need it to start semantic analysis. 


`cargo asm` integration could be implemented on top of rust-analyzer however. I think the only thing rust-analyzer can help with here is answering "what is the current function?" question, and for that, `DocumentSymbol` request should can be used. That might require us to expose vscode extension API (basically, making the `client` pub), and we should do that, if there's need. 

Finally, based on amount of :+1: this issue has, I would accept a PR adding `cargo asm` integration in core, provided that:

* It works by literally shelling out to `cargo asm` as a binary, it doens't use it as a library
* The implementation is simple (low sloc, preferably doesn't introduce LSP extensions)

That said, I'm going to close this issue as out of scope nonetheless :-)
