### ISSUE TITLE
Please provide Windows arm64 binaries

### ISSUE THREAD

**Issue by glandium** [rust-analyzer/rust-analyzer#4677]
VSCode recently started shipping binaries for Windows arm64 https://twitter.com/joaomoreno/status/1266005299661545474

It would be useful for rust-analyzer to be available as well.

**Comment by bjorn3** [comment]
You can build rust-analyzer yourself for now.

**Comment by matklad** [comment]
rust-analyzer is now available via rustup, that I think should build more platforms.

**Comment by smj389** [comment]
Windows arm64 is now supported at Tier 2 as a host environment. It would be good to make it a supported environment here as well.

**Comment by lnicola** [comment]
Hopefully implemented in #7148, #7151, #7155, but we'll see tomorrow.

**Comment by smj389** [comment]
Thanks - do you know when those changes will go live? The nightly extension I just downloaded still has the old code which does not accept aarch64. @lnicola

**Comment by lnicola** [comment]
The builds are triggered at 00:00 UTC and take about an hour, probably due to the scarcity of the MacOS 11 runners.. The latest nightly is at https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly.

Also, the message was shown only when trying to download there server binary, and that was fine since there were no binaries for this platform. But the extension still worked fine if you built your own server binary and set `rust-analyzer.serverPath` to point to it.
