### ISSUE TITLE
Incorrect truncated macro expansion

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#4777]
This code results in a wrong expansion of the macro, where the resulting enum only has the first specified variant:

```rust
macro_rules! enum_with_unknown {
    (
        enum $name:ident {
            $(
              $variant:ident $(,)*
            ),*
        }
    ) => {
        enum $name {
            $(
              $variant,
            )*
        }
    }
}

enum_with_unknown! {
    enum ControlOpcode {
        ConnectionUpdateReq,
        ChannelMapReq,
    }
}
```

Resulting code according to "Expand macro recursively":

```rust
enum ControlOpcode {
  ConnectionUpdateReq,
}
```

(EDIT: Reduced)

**Comment by lnicola** [comment]
Triage: this still happens, now with a "leftover tokens" warning.

@edwin0cheng you might want to take a look?

**Comment by edwin0cheng** [comment]
I know what's the problem now, and I think currently we can't fix it without using another macro parsing algorithm.

Here is a simpler example for the same problem :
```rust
macro_rules! foo {
    ($($i:ident $(,)*),*) => {};
}
foo!(a,b);
```

It is because our current mbe parser is eager matching, when it matches the middle comma by `$(,)*`, the outer seperator `,` could not be matched.  Of course we could hack and fix this bug but I think an proper solution is rewriten it as Earley parser. 

cc @matklad
