### ISSUE TITLE
Struct instantiation as a completion

### ISSUE THREAD

**Issue by DJMcNab** [rust-analyzer/rust-analyzer#480]
Poached (https://github.com/rust-analyzer/rust-analyzer/issues/479) from https://github.com/rust-lang/rls/issues/1180 

How I envision this feature working is in the limited set of cases where the `struct` instantiation is allowed (i.e. just after a struct name identified), we give a completion with a label of `instantiate struct` and the body as seen in the linked issue.

There are a few cases we need to be careful however - `forbid_structs` on Restrictions:

https://github.com/rust-analyzer/rust-analyzer/blob/c2b8aa1ce5e5398d981387079e86ff67a5b7e8c0/crates/ra_syntax/src/grammar/expressions.rs#L125-L129

is set in the places where structs are a parsing error.

Additionally, even if the struct is available in the current scope we should ensure that all of the fields are too (e.g. `pub(crate)`/no visibility modifier). However, at the moment I don't think we check visibility, so a good heuristic is probably checking if each field has a `VISIBILITY` or it originates in the same crate.

**Comment by matklad** [comment]
This shouldn't be a completion, this should be (as it is in IntelliJ) a diagnostics with a fix:

If we detect that not fields in the struct expression are present, we should give a red light bulb suggesting to "auto-fill" the fields, using the following logic:

* fields are added in roughly the definition order (existing fields may screw this up, but we shouldn't reorder them)
* if there's a local variable with matching type & name in scope, the field is initialized using shorthand, otherwise it is initialized with a "Default" value for a type.

**Comment by matklad** [comment]
We have this as an intention now. Will look into making this a diagnostics...
