### ISSUE TITLE
Go to definition on function definition points to usage

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#4807]
```rust
enum E {
    Foo { x: i32 },
}

fn foo(e: E) {
    match e {
        E::Foo { x } => bar(x),
    }
}

fn bar(x: i32) {}
```

Trigger go to definition on `bar` in `fn bar` and the cursor will go to `bar` in bar(x).

**Comment by lnicola** [comment]
CC @unexge, you might want to take this.

**Comment by unexge** [comment]
I did some debugging and it turns out this is a VSCode feature :) There is already a [test case](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide/src/goto_definition.rs#L640) for go to definitions on definition itself and correct positions propagated to VSCode extension. But VSCode uses an [alternative action](https://github.com/microsoft/vscode/blob/74bc00fd6c4c3ad16a11c18f2585f6fbd2b6b472/src/vs/editor/common/config/editorOptions.ts#L1533) (which [defaults](https://github.com/microsoft/vscode/blob/74bc00fd6c4c3ad16a11c18f2585f6fbd2b6b472/src/vs/editor/common/config/editorOptions.ts#L1491) to go to references) if go to definition returns current position.

**Comment by lnicola** [comment]
Damn :-). Indeed, I can't reproduce this in Vim. Thanks!
