### ISSUE TITLE
Relative paths for root_module in rust-project.json

### ISSUE THREAD

**Issue by tweksteen** [rust-analyzer/rust-analyzer#4816]
Currently, if relative paths are used within the `root_module` attributes of `rust-project.json`, they are interpreted as relative to the current directory (cwd). They should be interpreted as relative to either: 
- the location of `rust-project.json` (preferred); or
- rootPath, as provided during initialize.

I can send a pull request for this, but first I want to make sure there is no reason behind the current behaviour. Thanks.

**Comment by matklad** [comment]
Yeah, the current behavior is random, the paths should be relative to the rust-proejct.json file. I *think* this should be handled near serialization layer. Probably, we should remove `derive(Serialize)` from `JsonProject`, and instead have a method like `impl JsonProject { fn deserialize(abs_path: &Path, data: json::Value)` or some such (haven't thought about interface a lot).

**Comment by woody77** [comment]
Is the Cargo.toml-based workflow using all relative paths?  Normalizing all the JsonProject paths based on the location of the rust-project.json file seems like a good thing to do.  Either as a part of deserialization, or in the creation of the `ProjectWorkspace::Json` from the `ProjectManifest::ProjectJson` in `ProjectWorkspace::load()`.  I think, it would make more sense in the `load()` method, so that the `JsonProject` struct is more narrowly focused on the schema, and not the contents itself.

**Comment by matklad** [comment]
>Is the Cargo.toml-based workflow using all relative paths

I *think* paths in from Cargo-toml we get are absolutized by `cargo metadata`.

> so that the JsonProject struct is more narrowly focused on the schema, and not the contents itself.

I think the public API should make it impossible to not pass the root for relative paths. Perhaps the best solution is to have two structs `JsonProjectData` which is a straigforward `#[derive(Serialize)]` struct, and `JsonProject`, which is a more high-level thing, which enforces that all paths are absolute (and maybe also uses `CfgOptions`). 

That's standard pattern for serializaton -- domain model is lowered to a POD struct, and that is serialized with default settings.
