### ISSUE TITLE
"Replace qualified path with use" should replace all paths in the module

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#4836]
When running assists like "Implement missing members" or "Fill match arms", rust-analyzer will qualify all paths in the inserted code as necessary for them to resolve correctly. However, this can create rather long paths, which require many uses of the "Replace qualified path with use" assist to make the code more readable.

This could be fixed by having the "Replace qualified path with use" assist not just replace the path it is invoked on, but *all* paths in the module that refer to the imported item.

For example:

```rust
fn f(e: m::n::Enum) {
    match e {
        m::n::E<|>num::A => {}
        m::n::Enum::B => {}
        m::n::Enum::C => {}
        m::n::Enum::D => {}
    }
}
```

Invoking "Replace qualified path with use" *once* at this point should result in the code below:

```rust
fn f(e: Enum) {
    match e {
        Enum::A => {}
        Enum::B => {}
        Enum::C => {}
        Enum::D => {}
    }
}
```

**Comment by SuperFluffy** [comment]
Commenting here because it seems relevant (should I open a new issue?).

`replace_qualified_path_with_use` does not work for paths to the same type constructor but with different type parameter. In the example below `std::pin::Pin<T>` only gets replaced for those instances where `T` is the same. However, for `U != T` nothing changes.

### Before running `replace_qualified_path_with_use`:

```rust
use futures::FutureExt;
use std::{
    future::Future,
    task::{
        Context,
        Poll,
    },
    time::Duration,
};
use tokio::time::Sleep;

struct MyFuture {
    sleep: std::pin::Pin<Box<Sleep>>,
}

impl Future for MyFuture {
    type Output = ();

    fn poll(mut self: std::pin::Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        println!("MyFuture::poll()");
        self.sleep.poll_unpin(cx)
    }
}
```

### After having run `replace_qualified_path_with_use` on either occurence of `Pin` (second one for demonstration purposes; similar result for the first one):

```rust
use futures::FutureExt;
use std::{future::Future, pin::Pin, task::{
        Context,
        Poll,
    }, time::Duration};
use tokio::time::Sleep;

struct MyFuture {
    sleep: std::pin::Pin<Box<Sleep>>,
}

impl Future for MyFuture {
    type Output = ();

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        println!("MyFuture::poll()");
        self.sleep.poll_unpin(cx)
    }
}
```

You can see that `std::pin::Pin<Box<Sleep>>` was not changed. Not shown here: a second instance of `std::pin::Pin<&mut Self>` would have been correctly truncated to `Pin<&mut Self>`.

**Comment by flodiebold** [comment]
@SuperFluffy since this is closed, I think it'd be better to open a new issue :slightly_smiling_face:
