### ISSUE TITLE
Workspace symbol search returns no results when query includes dependencies

### ISSUE THREAD

**Issue by jbalint** [rust-analyzer/rust-analyzer#4881]
If I search for `*HashSet`, VS Code (1.46, also observed in 1.45 before updating), it says "No matching workspace symbols", but I see non-empty results from the request

<details>
<summary>request trace</summary>

```
[Trace - 3:27:48 PM] Sending request 'workspace/symbol - (41)'.
Params: {
    "query": "*HashSet"
}


[Trace - 3:27:48 PM] Received response 'workspace/symbol - (41)' in 42ms.
Result: [
    {
        "kind": 26,
        "location": {
            "range": {
                "end": {
                    "character": 52,
                    "line": 135
                },
                "start": {
                    "character": 0,
                    "line": 133
                }
            },
            "uri": "file:///home/jbalint/.cargo/registry/src/github.com-1ecc6299db9ec823/fnv-1.0.7/lib.rs"
        },
        "name": "FnvHashSet"
    },
    {
        "kind": 26,
        "location": {
            "range": {
                "end": {
                    "character": 65,
                    "line": 46
                },
                "start": {
                    "character": 0,
                    "line": 44
                }
            },
            "uri": "file:///home/jbalint/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-hash-1.1.0/src/lib.rs"
        },
        "name": "FxHashSet"
    },
    {
        "kind": 23,
        "location": {
            "range": {
                "end": {
                    "character": 1,
                    "line": 111
                },
                "start": {
                    "character": 0,
                    "line": 16
                }
            },
            "uri": "file:///home/jbalint/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/collections/hash/set.rs"
        },
        "name": "HashSet"
    }
]
```
</details>

**Comment by matklad** [comment]
The issue here is that VS Code now interprets `*` as a special symbol and does some helpful client-side filtering. They' added an ability to chain queries like `foo.rs @ bar` recently, and that's what causing this.

The fix here is to change our `*` and `#` symbols to something which doesn't conflict with VS Code new handling.

**Comment by matklad** [comment]
Also, this is a pretty important thing to fix, so help here is greatly appreciated :)

**Comment by SomeoneToIgnore** [comment]
Should [FST + `ImportMap` approach](https://github.com/rust-analyzer/rust-analyzer/pull/4819/files) be used here also?

**Comment by matklad** [comment]
Yes, but this is somewhat orthogonal, this issue is purely an editor UI problem.

**Comment by jpochyla** [comment]
Hi! I'd gladly help with this, as it pains me regularly. The thing to do would be to find new symbols to replace `#` and `@`, correct?

**Comment by lnicola** [comment]
Sounds like it. `#Foo` seems to work for me (though the manual shows `Foo#`, which doesn't work), but `*Foo` and `Foo*` don't.

**Comment by alcroito** [comment]
### Investigation
So I poked a bit at this and here are my findings.

The filtering that discards queries like `Foo*` happens here https://github.com/microsoft/vscode/blob/d22941af5d75800591770e69fd6ef08593cf1d75/src/vs/workbench/contrib/search/browser/symbolsQuickAccess.ts#L155

`scoreFuzzy2` compares the returned value from rust-analyzer, returns a non-numeric score and skips the result with `continue`.
I wasn't able to figure out why scoreFuzzy2 returns a non-numeric score because debugging a release VScode instance using typescript source maps wasn't tenable (the instruction pointer jumps all over place).

I tried replacing `*` with other characters, but that didn't convince the fuzzy score to change. I tried replacing `*` with a whole word like `dep_symbols`, adapting the code appropriately in https://github.com/rust-analyzer/rust-analyzer/blob/c9672a0539a59b626619724092077f57c70e6ffe/crates/rust-analyzer/src/handlers.rs#L362
then entering `#Foo dep_symbols` into the quick search, but `doGetSymbolPicks` only considers the first word as the query parameter and discards the second one.

### Proposed workaround
Would the alternative of always searching in dependency crates be acceptable? Aka always call `q.libs()`.

That bypasses requiring a marker in the search query (thus bypassing the above fuzzy search problem), while providing a better UX to developers that would expect non-local types to appear.

I'm not sure if that has any performance gotchas like always building a bigger index. Afaik it's already populated will all crate types?
