### ISSUE TITLE
publish to openvsx

### ISSUE THREAD

**Issue by rohan-sircar** [rust-analyzer/rust-analyzer#4936]
Please consider publishing the vscode extension to open-vsx.org

The latest version of [VSCodium](https://github.com/VSCodium/vscodium) has switched to using openvsx as the extensions provider. (VSCodium is a project which seeks to provide a 100% open source version of VSCode).

You can read more about openvsx [here](https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php).

**Comment by bjorn3** [comment]
> 1. Register on open-vsx.org through GitHub OAuth.
> 2. Create an access token and copy it.
> 3. Run npx ovsx create-namespace <publisher> --pat <token> with the publisher name specified in the extension’s package.json.
> 4. Run npx ovsx publish --pat <token> in the directory of the extension you want to publish.

The publish itself shouldn't be too hard to setup. However I don't know if https://github.com/open-vsx/publish-extensions/issues/41 ([matklad.rust-analyzer] error TS2307: Cannot find module 'vscode' or its corresponding type declarations.) is a problem with rust-analyzer or the specific setup at open-vsx/publish-extensions.

**Comment by matklad** [comment]
We don't have bandwidth to publish to more than one marketplace. People are encouraged to re-publish from Microsoft's store to open-vsx though.

**Comment by jankeromnes** [comment]
> publishing requires non-trivial amount of maintenance work from developers.

I don't think this cost is very high: Publishing to OpenVSX uses the same tech as publishing to Microsoft marketplace (i.e. both use `vsce`).

So, you could imagine adding one extra line to your existing Microsoft publishing script, and that line is:

```
npx ovsx publish
```

That's it. (It also requires a `OVSX_PAT` token that you can get from [here](https://open-vsx.org/user-settings/tokens), but otherwise there is no additional maintenance cost.)

**Comment by matklad** [comment]
The biggest cost here is maintaining a separate trusted identity (token) for a openvsx store. Some additional smaller costs are:

* having one more failure point during release process (if open vsx is down, release process breaks)
* having one more npm external dependency (`ovsx`) which needs to be versioned, updated, etc. 


More generally, anything that touches build and/or release process, in my experience, is a big cost, even if the actual diff is small.

**Comment by jankeromnes** [comment]
Good points, thanks for explaining them.

> The biggest cost here is maintaining a separate trusted identity (token) for a openvsx store.

This still doesn't seem significant to me (i.e. visit https://open-vsx.org/user-settings/tokens once, generate a token, save it in GitHub Secrets, done). But maybe you're considering things like regular secret rotations?

> - having one more failure point during release process (if open vsx is down, release process breaks)

True, but since it's non-critical, `npx ovsx publish` errors could simply be ignored (e.g. with something like `npx ovsx publish || true`).

> - having one more npm external dependency (`ovsx`) which needs to be versioned, updated, etc.

Actually, `npx` just fetches the latest release of a NPM package (here `ovsx`) to run it on-the-fly, so there is no need to add a dependency (other than `npx`, which comes built-in to `npm`) or to care about its version.

**Comment by est31** [comment]
FYI it's being [republished now as a daily job](https://github.com/open-vsx/publish-extensions/commit/37cc8a43745fe0ac7b7d9989b672fc61a53017d5), but that means that updates are reaching users delayed by up to a day.
