### ISSUE TITLE
Wrong Argument Name Preview When Passing a Tuple Into a Function and Destructuring it

### ISSUE THREAD

**Issue by JosephTLyons** [rust-analyzer/rust-analyzer#4960]
I'm not sure if this is the intended behavior, or a bug, consider the following code:

```rust
fn main() {
    let range = (3, 5);
    test_1(range);
}

fn test_1((start_range, end_range): (u32, u32)) {
    println!("{} - {}", start_range, end_range);
}
```

When you pass a tuple into a function and that function destructures the tuple, the argument name preview shows the first item in the tuple list for the name of the whole tuple.

In this example, its using "start_range" as the argument name preview for the whole tuple (which doesn't have a name):

<img width="423" alt="Screen Shot 2020-06-19 at 7 34 04 PM" src="https://user-images.githubusercontent.com/19867440/85185940-53c34000-b264-11ea-98b6-188fc297c6b3.png">

I'm not sure how else this could even be handled, but it technically isn't correct since the name refers to part of the tuple and not the whole tuple.

Maybe the preview could just be "(start_range, end_range)" in this specific example, or more generally "(x, y ,z ...)".

**Comment by SomeoneToIgnore** [comment]
There seems to be two bugs related to the issue indeed, thanks for the report.

The main issue is that the `FunctionSignature` data we use to build the inlay hints (I presume, that's what you meant under the "argument name previews") need to contain better data in the `parameter_names` field at least.

Here's the data for your example:

```
[crates/ra_ide/src/inlay_hints.rs:160] &fn_signature = FunctionSignature {
    kind: Function,
    visibility: None,
    qualifier: FunctionQualifier {
        is_async: false,
        is_const: false,
        is_unsafe: false,
        extern_abi: None,
    },
    name: Some(
        "test_1",
    ),
    doc: None,
    generic_parameters: [],
    parameters: [
        "(start_range, end_range): (u32, u32)",
    ],
    parameter_names: [
        "start_range",
    ],
    parameter_types: [
        "(u32, u32)",
    ],
    ret_type: None,
    where_predicates: [],
    has_self_param: false,
}
```

That should be fixed in the [`param_name_list`](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide/src/display/function_signature.rs#L231) function.
[These lines](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide/src/display/function_signature.rs#L243) should be adjusted, keep in mind that there might be a lot of various destructuring patterns, not only tuples.

And then, another issue is in the way we construct the hints in the [`get_param_name_hints`](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide/src/inlay_hints.rs#L160) function also needs some adjustments, since even if the `FunctionSignature.parameter_names` field contents would have contained all parameter names, the `.zip(args)` still omits the extra parameters.

I personally don't think we should display such hints at all: we have [an issue](https://github.com/rust-analyzer/rust-analyzer/issues/3138) with the inlay hints length already and adding more hints won't help the issue. 
It also appears to me that semantically the destructured argument names do not mean anything in the place that calls the function with the argument being destructured, so we don't bring any value by displaying them.
