### ISSUE TITLE
Consider migrating from arrayvec and smallvec to tinyvec

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#4973]
I haven't looked at this too close but `tinyvec` provides a safe alternative to both and it would be nice to consolidate if we can. The downside is that it requires things to implement `Default`.

**Comment by kjeremy** [comment]
https://docs.rs/tinyvec/0.3.3/tinyvec/index.html

**Comment by p-avital** [comment]
Are `arrayvec` and `smallvec` really unsafe ? With millions of downloads each I would assume they have withstood trial by fire.
`tinyvec` could be useful if we need growable yet expectedly small vectors, but my guess is that if the former crates are used, growability isn't that much of an issue.
Oddly enough, I haven't found any crates implementing short string/vector optimization like C++ strings or fbstring do; even though if growable short-optimized collections were a need, that's probably what I'd suggest instead of `tinyvec`'s enum.

**Comment by kjeremy** [comment]
I think in practice they're fine. I was approaching this from the "squash two dependencies into one" angle.

**Comment by matklad** [comment]
I think other crates in the crate graph already use `smallvec` and `arrayvec`, so it's unlickely that we'll have any actual win here. 

More generally, I think it's ok to use unsafe for the *right* API of fundamental data strucutres. It would take a lot of effort to fix all the bugs, but I believe it is doable.
