### ISSUE TITLE
Associated types are not resolved in the IDE layer

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#5003]
Like the `T::S` here:

```rust
trait D {}

trait Foo {
    type S;
}

trait Bar<T>
where
    T: Foo,
    T::S: D,
{
}

fn main() {}
```

CC #4991

Another one:

```rust
trait Foo {
    type Bar;

    fn foo(_: Self::Bar);
}

struct S;

impl Foo for S {
    type Bar = i32;

    fn foo(_: Self::Bar) {
        todo!()
    }
}
```

**Comment by flodiebold** [comment]
Not sure what you mean by "not resolved" here -- as far as I can see, e.g. within methods in `Bar` we can call methods of `D` on any `T::S`.

**Comment by lnicola** [comment]
Hmm, that's interesting. Yeah, it seems to work, but `T::S` shows up as `unresolvedReference`:

![image](https://user-images.githubusercontent.com/308347/86513745-6d908580-be15-11ea-9116-60237285e35d.png)

**Comment by lnicola** [comment]
Another issue: the type hint here seems wrong:

![image](https://user-images.githubusercontent.com/308347/86513970-0ecc0b80-be17-11ea-968a-db3856c1443f.png)

**Comment by flodiebold** [comment]
We don't handle this correctly in the IDE layer, that's true. Resolving `T::S` to the associated type happens during type lowering, which the IDE layer doesn't really access yet.

The type hint is correct, though we might consider displaying it differently. Since `T::S` doesn't normalize to any concrete type, it's represented as an associated type placeholder, which looks like this; but maybe we should display it as the projection `<T as Foo>::S` instead.

Actually both of these are a bit related to the type IR I've been working on slowly for a while, because I think it might also be the correct way to represent types for the IDE layer -- it would have `T::S` resolved, and it wouldn't have a representation of associated type placeholders (instead going back to it would convert them to projections)... :thinking:

**Comment by mouse07410** [comment]
Thank you for working on this!  Any idea what the time-frame for the incremental solution steps might be?

**Comment by lnicola** [comment]
#6387 fixed https://github.com/rust-analyzer/rust-analyzer/issues/5003#issuecomment-653769287, CC @bnjjj:

![image](https://user-images.githubusercontent.com/308347/97457773-bdee9e80-1942-11eb-90fb-4fbb9cc322f4.png)
