### ISSUE TITLE
please support aarch64 Linux with binaries

### ISSUE THREAD

**Issue by tidux** [rust-analyzer/rust-analyzer#5256]
This is useful as most of the LSP-supporting editors, including Emacs, Vim, and various VSCode builds, all work on the platform, and would allow either cheap cloud instances or Raspberry Pi >=4 boards to be useful Rust development hardware.

**Comment by Veetaha** [comment]
See #4746, github actions don't provide native arm hosted runners, we have to setup cross-compilation for this

**Comment by matklad** [comment]
This is out of scope for build process in this repository. You can, however, do

```
 rustup component add --toolchain nightly rust-analyzer-preview
```

with today's nightly, and that should have more platforms (I think).

**Comment by Lokathor** [comment]
Since aarch64 is on track to be a Tier 1 target, this should be something that the repo re-considers. Particularly since it's your own error message that directs people to come here and file issues about additional platforms to support.

I did try the `rustup` command you suggested, and it did not seem to provide a rust-analyzer binary that the rust-analyzer VS Code plugin recognized.

**Comment by bjorn3** [comment]
You need to explicitly specify the path to the rust-analyzer binary using `rust-analyzer.serverPath` if you want to use the rustup component. It should be somewhere in `~/.rustup/toolchains/nightly-*`.
