### ISSUE TITLE
Module path in on-hover message doesn't normalize dashes to underscores (regression)

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#5343]
This worked before, but now it doesn't (cc @SomeoneToIgnore):

![image](https://user-images.githubusercontent.com/36276403/87316963-0cf8fb00-c52f-11ea-91c3-fd61b3641c83.png)

**Comment by SomeoneToIgnore** [comment]
This is the place where we select the crate name: https://github.com/rust-analyzer/rust-analyzer/blob/c668121/crates/ra_ide/src/hover.rs#L269-L270

The `display_name` comes from https://github.com/rust-analyzer/rust-analyzer/blob/c668121/crates/ra_db/src/input.rs#L127 and used to be `CrateName` up until it got removed recently: https://github.com/rust-analyzer/rust-analyzer/pull/5158

I think `display_name` should be of type `CrateName`, but maybe the field name should be different.
Maybe @matklad can share some more insights about the correctness from the PR.

**Comment by matklad** [comment]
It definitely should be String. The semantics of CrateName is not “string without dashes”, it is “string you can put into extern crate”. This is not true about display_name, we should make it very clear that it doesn’t affect semantics, and using String for that achieves that purpose. 

We should normalize dashes when adding a new crate.


In other words, this is the case where *implementation* of two different things happen to be the same, out of pure accident, but the things are actually different.

**Comment by SomeoneToIgnore** [comment]
The crate name resolution is somewhat twofold and needs a slightly different name resolution depending on the hover source and target crates:

* if we hover over a type from a dependent crate (we hover over `Vec` in any project that's not an stdlib), then we have a field `dependencies` in the `CrateData` struct where we can look up a normalized **dependency** name and use that in the pop-up. For `Vec`, that's `std` coming from one of the sysroots.

* if we hover over a type from the same crate (we hover over `Foo` in the project where `Foo` is declared somewhere), then we need to get the crate name somehow.
This is not a dependency name, this is the crate name itself.

For Cargo projects, it's this:
```
[package]
edition = "2018"
name = "ra_hir"
```

This is the only place that gives us troubles, due to `cargo metadata` not normalizing the dashes here.
We used to store this normalized name in the `display_name` field of the `CrateData` and now we've lost it after a few perturbations in the PRs, but we still need it somewhere.

I think it should still go to `CrateData` and somehow united with the `display_name` contents too, what do you think, Aleksey?
Should we maybe add another method to `CrateName` to return the unnormalized name for cases where it's needed, if there are any?

**Comment by SomeoneToIgnore** [comment]
And yes, the current implementation is wrong because it does not consider dependencies at all, I can submit a PR after we agree on how to deal with the crate root names.

An alternative to storing the actual name would be to use `crate` instead, but that is not that useful and does not look good IMO.

**Comment by flodiebold** [comment]
Note that there's no guarantee that the type you're hovering is from either the crate or a direct dependency. It could come from a transitive dependency as well, in which case you don't have a dependency name that makes sense either.

**Comment by SomeoneToIgnore** [comment]
Not sure I follow. 

If we open a transitive dependency's code, it still should comply to the importing rules (cannot import the external definitions if the crate is not in the dependencies).
And since we're storing the data about all crates in the `CrateGraph` and good with the "Go to definition" in the transitive dependencies' code already, we're should be good with the hovers too.
The same logic for the local code should apply for the transitive dependencies' code:

1. get the crate id of the file we're hovering in
2. resolve the definition we've hovered onto
3.1. if the definition crate matches the current crate id, get the normalized crate name from somewhere (used to be the `display_name`)
3.2 otherwise, look up the name in the dependencies

**Comment by flodiebold** [comment]
Step 3.2 is not guaranteed to find the crate. Say you have crates A -> B -> C, then you can have a function in B that returns a type from C, so you can have code in A using a type from C without having a direct dependency on it.

**Comment by SomeoneToIgnore** [comment]
Great point.

Luckily, we consider only Name and NameRef: https://github.com/rust-analyzer/rust-analyzer/blob/c668121/crates/ra_ide/src/hover.rs#L87

and show the qualified paths to those, so we might be good with the basic algorithm for the hover case?

**Comment by flodiebold** [comment]
I don't think so, B could still be re-exporting a type from C. Also, when hovering methods we can possibly show the qualified path to a struct that isn't even importable.
```rust
// c
pub struct S;
impl S {
  pub fn foo(&self) {}
}
// b
pub fn s() -> S {}
// a
fn test() {
    b::s().foo(); // <- hover foo
}
```

**Comment by SomeoneToIgnore** [comment]
My initial idea was to display a name that could be placed into the code without issues (hence the normalization & thoughts about the relative naming), but for the transitive case, the relative naming does not help the user at all.

Might it make more sense to always display the crate name then?
Preferrably normalized after all, which returns us back to 

>  We used to store this normalized name in the display_name field of the CrateData and now we've lost it after a few perturbations in the PRs, but we still need it somewhere.

and the question on where to store it better.

**Comment by flodiebold** [comment]
Yeah, I would always display the crate name. The rest of the path is not necessarily the right one for importing either.

**Comment by SomeoneToIgnore** [comment]
In that case, does it matter if a path is normalizer or not?
Current way may be even better for the crate discovery.

**Comment by flodiebold** [comment]
I'd say it's just a bit confusing, and it messes up the coloring apparently...

**Comment by SomeoneToIgnore** [comment]
I'm trying to come up with a test to cover this with no avail, but I cannot get the idea what exactly am I doing wrong.

Test:
```rust
#[test]
    fn zz() {
        check(
            r#"
//- /lib.rs crate:dep
pub mod wrapper {
    pub struct Thing { x: u32 }

    impl Thing {
        pub fn new() -> Thing { Thing { x: 0 } }
    }
}

//- /main.rs crate:main deps:dep
fn main() { let foo_test = dep::wrapper::Thing::new<|>(); }
"#,
            expect![[r#"
                *new*
                ```rust
                dep::wrapper::Thing
                ```

                ```rust
                pub fn new() -> Thing
                ```
            "#]],
        )
    }
```

Instead of an expected outcome, I get
```
Actual:
----
*dep::wrapper::Thing::new*
{unknown}
```

When I merge everything into a single fixture, it works.
When I reproduce the same example in a real cargo project, the hover works:
![zz](https://user-images.githubusercontent.com/2690773/87935301-821d8080-ca99-11ea-8023-e4f9c7febdc8.png)

I've tried comparing it with a single fixture test to see the difference and dig down to `source_analyzer.rs` and `new_for_body` method, it seems to produce a different outcome for each case, but I think I've missed something obvious, as if some data is incorrectly filled in the test.

Any ideas on what to check or any other approaches to try?
