### ISSUE TITLE
Fill struct fields assist behaves badly inside of vec![] macro

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#5393]
![demo](https://user-images.githubusercontent.com/36276403/87549592-af8fb600-c6b6-11ea-847c-7e88b08d6397.gif)

**Comment by kiljacken** [comment]
Similar to #2799. Seemingly another case of not properly translating the span from inside the macro expansion to an actual file position.

**Comment by TimoFreiberg** [comment]
So the fix is constructed [here](https://github.com/rust-analyzer/rust-analyzer/blob/e72c6220cda30ebe2bde4e0bd7d344c248332ecc/crates/ra_ide/src/diagnostics.rs#L90).
`d.ast(db).syntax()` needs to be translated as kiljacken said.
I found `hir::original_range` which is used in the linked issue to get the correct `FileRange`, but I have no idea how to get the corresponding `SyntaxNode`  (nor whether this is the correct approach)

Also, this issue existing sounds like translating macro-expanded syntax back for applying fixes and such is a bit fragile, it would be cool to make constructing TextEdits always translate back from macro-expanded code...

**Comment by flodiebold** [comment]
See https://github.com/rust-analyzer/rust-analyzer/pull/7468.

**Comment by lf-** [comment]
Minimized example of a broken case:

```rust
macro_rules! id {
    ($i:expr) => {
        $i
    };
}

struct A {
    x: u32,
    y: u32,
}

fn main() {
    id!(A {});
    // fill-struct-fields here to screw up
}
```
