### ISSUE TITLE
request: also publish to OpenVSX for VSCodium users

### ISSUE THREAD

**Issue by Phrohdoh** [rust-analyzer/rust-analyzer#5688]
https://open-vsx.org/extension/matklad/rust-analyzer
https://github.com/open-vsx/publish-extensions

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4936

At this stage, our approach is not likely to change due to the reasons described in the same issue, here's the main point, in my opinion:

https://github.com/rust-analyzer/rust-analyzer/issues/4936#issuecomment-646635025

I propose to continue the discussion there, if you have anything to add.

**Comment by Phrohdoh** [comment]
Apologies for filing a duplicate issue.
