### ISSUE TITLE
Type inference tests are unreasonable slow

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#5792]
Many type inference tests take on the order of 100 ms:

```rust
0.088s test tests::regression::issue_2683_chars_impl ...
0.089s test tests::traits::argument_impl_trait_type_args_1 ...
0.090s test tests::traits::generic_param_env_1 ...
0.091s test tests::traits::argument_impl_trait ...
0.092s test syntax_highlighting::tests::test_highlighting ...
0.094s test tests::simple::infer_generic_chain ...
0.094s test tests::traits::proc_macro_server_types ...
0.095s test inlay_hints::tests::omitted_parameters_hints_heuristics ...
0.095s test tests::regression::issue_4053_diesel_where_clauses ...
0.095s test tests::simple::infer_argument_autoderef ...
0.095s test tests::simple::infer_method_argument_autoderef ...
0.096s test tests::regression::issue_4966 ...
0.097s test tests::traits::infer_box_fn_arg ...
```

It seems unreasonable that we take almost 100ms (even in debug) for this:

```rust
#[test]
fn generic_param_env_1() {
    check_types(
        r#"
trait Clone {}
trait Trait { fn foo(self) -> u128; }
struct S;
impl Clone for S {}
impl<T> Trait for T where T: Clone {}
fn test<T: Clone>(t: T) { t.foo(); }
                             //^ u128
"#,
    );
}
```

Full results are here:

https://gist.github.com/matklad/07260b610e05b4815c9c4993abc1cdf5

**Comment by matklad** [comment]
Aha, @hawkw, @davidbarsky, seems like this is another case of "@matklad complains about tracing being slow in weird scenarios": seems like tracing makes `debug` code slow, which adds up to substantial overhead when running tests. 

See this commit for a reproducible example: https://github.com/matklad/rust-analyzer/commit/363d821958c0b7d96b0dcac08025ad4cb6084164

To be clear, I'm absolutely ok with this being "won't fix, not an explicit design goal", b/c optimizing debug perf does seems a bit weird. But I thought you might want to be aware.

**Comment by matklad** [comment]
EDIT: hm, let me check if this just amortizes over many tests...

**Comment by matklad** [comment]
Some more numbers:

For the whole test-suite of ~300 tests , the difference 2.87s vs 2.16ms. This is much less of a difference, but still, 25% overhead is bigger than what I'd naively expect to see. 

The overhead for single test in release seems even bigger:

844.55µs vs  5.77ms

The results for the whole suite in `--release` is

0.51s vs 0.35s

which is perhaps the most worrying bit

Finally, if I manually check if env-var is set before enabling tracing, the overhead goes away:

https://github.com/rust-analyzer/rust-analyzer/commit/8115bef76a4ef5bd82ad7b33261f6f2e50855af4

TO be clear, the `CHALK_DEBUG` var is **not** set, the observed overheads are from disabled tracing.

**Comment by matklad** [comment]
Also, I can not help by notice that `EnvFilter::from_env` calls a whole bunch of generic code, which slows down consumer's compile times. It might be a good idea to delegate from generic functions to non-generic ones :)

**Comment by davidbarsky** [comment]
Thanks for digging into this! Acknowledging that I saw this and making this reproducible. I haven't had the time do dig into this yet.

**Comment by hawkw** [comment]
Hmm, this is definitely worth digging into. Thanks for tagging me! 

> For the whole test-suite of ~300 tests , the difference 2.87s vs 2.16ms. This is much less of a difference, but still, 25% overhead is bigger than what I'd naively expect to see.

I *think* the 2.16 _ms_ is a typo, but just to be sure, are we actually taking the test suite's runtime from milliseconds to seconds? If that's the case, this seems really incredibly bad...

I checked the lockfile, and it looks like `rust-analyzer` _is_ on the latest `tracing` version, that's a bummer --- I was hoping this could be solved by saying "just update to the latest".

> Finally, if I manually check if env-var is set before enabling tracing, the overhead goes away:

This is somewhat surprising; the fast path for "no subscriber" and the fast path for "disabled by the subscriber's max level filter" should be only a couple of instructions different...I'll have to do a quick disassembly to make sure that's the case...

Alternatively, I wonder how much of the overhead is constructing the filter/subscriber, as you pointed out. We should look into that, as well.

**Comment by matklad** [comment]
@hawkw oops, that should be `s`, not `ms` of course.

**Comment by hawkw** [comment]
Okay, that, at least, is a little bit less scary. :)

I'm working on digging into some generated assembly for the macros, and I may have some changes for you to try out in a bit!

**Comment by matklad** [comment]
@hawkw I'll probably won't be able to try them out today (next ~8 hours), but https://github.com/matklad/rust-analyzer/commit/363d821958c0b7d96b0dcac08025ad4cb6084164 contains all the required repro instructions (rust-analyzer is easy to build)

**Comment by hawkw** [comment]
I did some playing around with your reproduction, and it looks like basically all the overhead here is from constructing the subscriber `Registry` itself. 

On my machine, running the tests with `setup_tracing` commented out entirely gets me:
```
running 1 test
total: 15.986421ms
test tests::traits::generic_param_env_1 ... ok
```
and if I don't comment it out, I get
```
running 1 test
total: 43.29042ms
test tests::traits::generic_param_env_1 ... ok
```

Now here's where it gets interesting: if I comment out the construction of the `HierarchicalLayer` and the `EnvFilter`, so that `setup_tracing` looks like this:
```rust
fn setup_tracing() -> tracing::subscriber::DefaultGuard {
    use tracing_subscriber::{layer::SubscriberExt, EnvFilter, Registry};
    use tracing_tree::HierarchicalLayer;
    // let filter = EnvFilter::from_env("CHALK_DEBUG");
    // let layer = HierarchicalLayer::default()
    //     .with_indent_lines(true)
    //     .with_ansi(false)
    //     .with_indent_amount(2)
    //     .with_writer(std::io::stderr);
    let subscriber = Registry::default() /* .with(filter).with(layer) */;
    tracing::subscriber::set_default(subscriber)
}
```
...the test takes just as long:
```
running 1 test
total: 43.691158ms
test tests::traits::generic_param_env_1 ... ok
```
On the other hand, if I don't construct a `Registry`, but still construct the filter and `HierarchicalLayer`, _and_ still call `set_default` with a clone of the current (no-op) default subscriber, like this:
```rust 
fn setup_tracing() -> tracing::subscriber::DefaultGuard {
    use tracing_subscriber::{layer::SubscriberExt, EnvFilter, Registry};
    use tracing_tree::HierarchicalLayer;
    let filter = EnvFilter::from_env("CHALK_DEBUG");
    let layer = HierarchicalLayer::default()
        .with_indent_lines(true)
        .with_ansi(false)
        .with_indent_amount(2)
        .with_writer(std::io::stderr);
    drop(filter);
    drop(layer);
    // let subscriber = Registry::default().with(filter).with(layer);
    tracing::dispatcher::set_default(&tracing::Dispatch::default())
}
```
it's only a teensy bit slower than when we were not calling `setup_tracing` at all (and that may be noise!):
```
running 1 test
total: 16.625329ms
test tests::traits::generic_param_env_1 ... ok
```

So, this strongly suggests that we are spending the remaining ~26ms constructing the `Registry` itself. Which is definitely not great!

Optimizing the performance of _constructing_ a `Registry` is not really something we've prioritized so far. They tend to be long-lived and constructed near when the program starts, so constructing one is not generally a hot path. However, I hadn't really thought about unit tests where each test constructs its own subscriber, because a single `Registry` construction at the beginning of the test suddenly has a _much_ bigger impact!

We should probably try to improve the performance of registry construction for other folks who are building a subscriber per test...especially since that's what I generally tend to recommend for using `tracing` in tests. It could be worth opening an issue against the `tracing` issue tracker for this.

**Comment by hawkw** [comment]
My guess is that this line probably dominates `Registry` construction pretty significantly: https://github.com/hawkw/sharded-slab/blob/8c84f7beb78b20a30aa043da9022364dffff5a1a/src/lib.rs#L268

I think there are potential upstream changes to `sharded-slab` we can make to improve this. Right now, each shard is initialized eagerly, which wastes a lot of time. We could improve that by initially allocating a `MaybeUninit` and incrementally initializing new shards as new threads access the slab.  Or, perhaps, we could construct an empty `Vec` using `with_capacity`, and `push` new shards to it when they're needed, so that `Vec` manages the uninitialized memory for us. However, the downside of that approach is that `Vec::push` does [an unsynchronized add](https://doc.rust-lang.org/src/alloc/vec.rs.html#1206) to the vec's length field, so we'd need to add locking here, which is probably a non-starter...

**Comment by matklad** [comment]
I guess there's maybe a simpler fix here? The filter is trivial, so I think
the `Register` itself can be patched to only actually do something after it
saw the filter? Not sure how the types are set-up here, but it seems like
it should be possible to delay all the actual work until the call to
`set_default`, where we can say: "oops, the Filter is trivial, guess we
have nothing to do"?
