### ISSUE TITLE
Starting client failed

### ISSUE THREAD

**Issue by johncrane** [rust-analyzer/rust-analyzer#5840]
OS: Ubuntu 18.0.4LTS
rustc: 1.45.2
vscode: 1.48.1
Rust extension: 0.7.8
rust-analyzer: 0.2.281

Error output:
[Error - 11:38:12 AM] Starting client failed
Launching server using command /home/john/.config/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux failed.

It didn't provide any further failure reason.
I tried to manually run the "rust-analyzer-linux", it just block there without any output, and does not return to the command prompt. I have to hit Ctrl+c to kill it.

I also tried recent older version of rust-analyzer, all failed with the same error
Tied to clean up the extension and downloaded rls sever from disk. Nothing helped.

**Comment by to266** [comment]
I've encountered this as well.

The actual rust-analyzer-linux binary seems to be ok though:
```bash
$ /home/tomas/.config/Code\ -\ OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux --version
rust-analyzer 3ca97b0
```

**Comment by to266** [comment]
Aaaargh, ok - for me the issue was that the VSCode workspace contained rust projects (with own `Cargo.toml` etc)  that got deleted. I guess `rust-analyzer` then tried to run it in those folders, but since they no longer exist, that of course fails.

Simply removing those deleted folders from the workspace fixes the issue.

**Comment by flodiebold** [comment]
@johncrane are you still having this problem?
