### ISSUE TITLE
Links in documentation don't have the crate name normalized

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#5932]
When hovering over a symbol imported from crate `foo-bar` the links in the on-hover documentation lead to 
```
https://docs.rs/foo-bar/*/foo-bar/struct.FooBar.html
```
instead of
```
https://docs.rs/foo-bar/*/foo_bar/struct.FooBar.html
```

(notice replacing the dash with an underscore after `*`. This is important because docs.rs returns 404 for the first variant as of now

**Comment by SomeoneToIgnore** [comment]
Looks like it's caused by the same issue as in https://github.com/rust-analyzer/rust-analyzer/issues/5343

If we want to fix this properly, we need some way to make the test from https://github.com/rust-analyzer/rust-analyzer/issues/5343#issuecomment-660984896 to work.

If we just want to fix it and are fine with the potential future regressions, we need to revert the changes described in  https://github.com/rust-analyzer/rust-analyzer/issues/5343#issuecomment-657613138 and name the `display_name` field better.
