### ISSUE TITLE
Auto-import should not rewrite existing imports

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#6047]
![image](https://user-images.githubusercontent.com/1711539/93753318-42415980-fc00-11ea-9044-4b28759bc48c.png)

->

![image](https://user-images.githubusercontent.com/1711539/93753338-4c635800-fc00-11ea-9734-70a88ec0835d.png)

Ideally, we should avoid doing that... cc @Veykril

**Comment by Veykril** [comment]
I assume you mean the order of the imports shouldn't change right? Didn't think of the possiblity that some people would like to order them themselves, I guess this could also be a configuration option. And of course the formatting shouldn't break like this, which I unfortunately expected to happen in some cases.

**Comment by matklad** [comment]
I think changing the order would be ok-ish, but we should try to preserve whitespace. In general, it's better to do "surgical edits" rather than "rewrites".  How to actually do that in a nice way is an open question though :0)

**Comment by Veykril** [comment]
Ah yes, doing that with small edits might prove tricky, I'm gonna see what I can do there. A rewrite of the tree in general was just nicer since I was focusing on keeping the entire tree ordered and I obviously can't assume the tree being ordered before the merge.

**Comment by Veykril** [comment]
They way I see it is, that not reordering isn't really an option, as that would mean we would always have to insert into the last line potentially making it too long, or after the last line potentially having a lot of single items on each line.
With Reordering keeping the whitespace seems difficult on the other hand, as there might be a lot of cases too handle, if I'm not mistaken. Would it be feasible to format the merged tree ourselves? If I remember correctly I already saw someone talking about the possibility of a future `ra_fmt` module so that would probably go in line with it?

**Comment by matklad** [comment]
> that would mean we would always have to insert into the last line potentially making it too long, or after the last line potentially having a lot of single items on each line.

Without thinking to much about it, could we *maintain* the sorted order? Ie, instead of appending and re-sorting everything, we just try to find a reasonable place in the middle? if the list is already sorted, than we preserve sortedness, if it is not, we insert the thing somewhere? But, really, any approach would work, as long as end result is not too surprising :)

**Comment by Veykril** [comment]
That might also be an option. I'll see what I can do :)

**Comment by Veykril** [comment]
After thinking about it for a bit this seems to give me more trouble than I hoped for 😅 I tried doing surgical inserts but I'm running in a lot of problems I'm really not sure how to tackle properly. If this problem is severe I would probably say to maybe roll back my changes for now and use the old merging logic.

**Comment by matklad** [comment]
I believe this is fixed!

I am positively delighted how our auto-import workd, thanks @Veykril  @SomeoneToIgnore for turning this from something which is possible into a polished product feature!
