### ISSUE TITLE
Insert explicit type removes coercion to raw pointer

### ISSUE THREAD

**Issue by bluss** [rust-analyzer/rust-analyzer#6107]
In the following code:

```rust
fn foo<T>(mask_buf: &T) { 
    let mut ab: *const _ = mask_buf;
    ...
}
```

The insert explicit type assist produces `let mut ab: &T = mask_buf;`  which makes the rest of the code in the function invalid (pointer arithmetic).

Version: 0.2.328

**Comment by flodiebold** [comment]
:thinking: There should be no "insert explicit type" assist if there's already an explicit type annotation. That should be easy to fix?

**Comment by lnicola** [comment]
It might make sense for the assist to replace a placeholder (`_`) with the correct type.

**Comment by Veykril** [comment]
It already seems to do that for some types, see the test here:
https://github.com/rust-analyzer/rust-analyzer/blob/3f4e9914ff77c76ad3cbdebe1e4e2c0a78818d63/crates/assists/src/handlers/add_explicit_type.rs#L101-L124

So maybe non `PathType`s are problematic.

**Comment by bluss** [comment]
I don't know if this needs solving, but it's an interesting limitation. It's a good point that it will not handle any type of coercion (including unsizing etc).

**Comment by flodiebold** [comment]
We should be able to record the coerced type here (we need to add a new map to `InferenceResult` for this):
https://github.com/rust-analyzer/rust-analyzer/blob/3f4e9914ff77c76ad3cbdebe1e4e2c0a78818d63/crates/hir_ty/src/infer/expr.rs#L50
and then use that instead of the type of the right-hand expression. (It'll need some more plumbing to make the type accessible through the HIR facade, I think.)
