### ISSUE TITLE
Give associated functions the ‘static’ semantic token modifier

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#6194]
In some other languages these are referred to as ‘static methods’. This has precedent, since semantic token modifiers that assume certain language features (e.g. interfaces and namespaces) are applied by rust-analyzer to the closest Rust equivalents (e.g. traits and modules). ‘static’ isn’t something people in the Rust community would characterise associated functions as, though, so it’s just an idea.

**Comment by matklad** [comment]
The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/ide/src/syntax_highlighting.rs#L803-L810

**Comment by p3achyjr** [comment]
Hey--first time contributor here. If no one is taking this up, can I give this a stab?

**Comment by Veykril** [comment]
No one claimed it so far so go for it!

**Comment by p3achyjr** [comment]
thanks @Veykril! I've just spent a bit of time working on this, and naively adding static won't work, because this also includes functions that aren't associated with any impl/traits.

Looking at item_tree.rs, it looks like we can get AssocItems when we are looking at an impl/trait object, but we cannot get the enclosing impl/trait when we are looking at a function. From this, I think we can either:

a) Pass the innermost impl/trait object, or some kind of flag indicating we are inside an impl/trait object.
b) Consider all functions without a self_param as static.

What do you guys think? Some code pointers:

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/hir_def/src/item_tree.rs#L503-L514

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/hir_def/src/item_tree.rs#L573-L580

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/hir_def/src/item_tree.rs#L583-L590

**Comment by Veykril** [comment]
I think you can get away by fetching the `ast::Fn` node from the `hir::Function` and then checking if the parent node is an impl or not actually. Something along these lines:

```rust
let ast_fn = func.source(db).value;
if ast_fn.syntax().parent().and_then(|s| s.parent()).and_then(ast::Impl::cast).is_some() { ...
```

Note we have to take the parent's parent here cause the immediate parent is an `AssocItemList` and the parent of that would be the `Impl` we want to check for.

**Comment by p3achyjr** [comment]
Thanks @Veykril! just made a PR :)

Another qq--this PR simply adds "static" to the class attributes for static function names--is it up to the client to color to color those names appropriately?

**Comment by arzg** [comment]
> Another qq--this PR simply adds "static" to the class attributes for static function names--is it up to the client to color to color those names appropriately?

@p3achyjr yes, the client decides what colour tokens with `function.static` have, or whether to give them a colour at all. All language servers do is tell the client what scopes and modifiers tokens get.
