### ISSUE TITLE
structs in included files are marked as "unresolved imports"

### ISSUE THREAD

**Issue by sidkshatriya** [rust-analyzer/rust-analyzer#6289]
How can I ask rust-analyzer to look at the contents of rust code I have `include!`-ed?

- I have a lot of unresolved imports for which I cannot use Goto definition 
- Also I don't get suggestions for imports from these included files

(I am not using VSCode though I guess that is not relevant here most probably. Also these files will compile properly -- its just that rust analyzer needs to be made aware of these included files)

Interestingly CLion will allow you to goto definitions in included source and I believe it also gives import suggestions from included files.

**Comment by bjorn3** [comment]
Do you use `env!("OUT_DIR")`? If so you need to set `"rust-analyzer.cargo.loadOutDirsFromCheck": true`.

**Comment by sidkshatriya** [comment]
Thank you. I believe this would need to go into `settings.json` perhaps? Where do I put this `settings.json` so that rust analyzer picks it up? (I'm not using VSCode)

**Comment by flodiebold** [comment]
The place where you have to put settings depends on your editor, so I'd recommend consulting the documentation of (the LSP integration of) that editor.

**Comment by dfarley1** [comment]
Sorry if I should create a new issue instead of necroing this one, but I'm running into this issue using VSCode v1.51.1 and Rust-Analyzer v0.2.408.

I'm using rust-bindgen with a wrapper file `bindings.rs`: 
```rust
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/rust_bindgen.rs"));
```

I'm getting unresolved imports from this line in another source file: 
```rust
use crate::bindings::{foo, bar};
```
Specifically the `foo` and `bar` parts are failing, `bindings` resolves properly. I have `"rust-analyzer.cargo.loadOutDirsFromCheck": true,` in my workspace file and `cargo build` passes when run from the shell.

Interestingly, if I Ctrl+Click (go to definition) on `foo` it will open up `rust_bindgen.rs` at the correct location.

**Comment by flodiebold** [comment]
@dfarley1 A new issue would probably be better, and it'd be great if you could provide a full example reproduction of the problem.

**Comment by dfarley1** [comment]
@flodiebold Turns out I didn't have `"rust-analyzer.procMacro.enable": true` set, I got the hint from the list of known issues in the "New Issue" template, thanks!
