### ISSUE TITLE
[VSCode] Allow customisation of inlay hint styling

### ISSUE THREAD

**Issue by matthewsanetra** [rust-analyzer/rust-analyzer#6405]
I personally don't like the new smaller inlay hints, and I think it would be great to be able to customise it.

It was introduced here: #6394 
Discussion of customising was held here: #6380

**Comment by staninprague** [comment]
If there are any options like Regular, Small, Smallest, I'd consider the current inlays being the "Smallest" - really hurts an eye in the reading glasses. Never thought I'll be crying out for some "accessibility".

**Comment by gdmachado** [comment]
would also be nice to be able to configure the font size directly, as well as color. I'd like to take a crack at this

**Comment by lnicola** [comment]
Code might support these natively at some point, so we might throw away your work, though.

**Comment by SomeoneToIgnore** [comment]
Also note, that this feature is 100% about VSCode plugin *.ts files in https://github.com/rust-analyzer/rust-analyzer/tree/master/editors/code directory, no `*.rs` files are expected to be changed in the PR closing this issue.

But in case you still want to do that, here's a very related PR that changed hint styles: https://github.com/rust-analyzer/rust-analyzer/pull/8617
that you can use as a base and maybe even replace the old font configuration with yours?

Anyway, you have to do something essentially similar: adjust editor related decorations' styles [here](https://github.com/rust-analyzer/rust-analyzer/pull/8617/files#diff-a829d219176e4fa1844fdf86badacb15387a8179b97cb941373c9e0534fa3f2eL64)

Also consider:
 * adding simple to adjust settings with good defaults (adjust extension's package.json directly)
 * VSCode-related performance implications: currently for our small-big hint style toggle we keep [two separate collections](https://github.com/rust-analyzer/rust-analyzer/pull/8617/files#diff-a829d219176e4fa1844fdf86badacb15387a8179b97cb941373c9e0534fa3f2eR84) otherwise the hint style update lags noticeably on the setting toggle.

**Comment by ian-h-chamberlain** [comment]
With the changes of #11445 is this no longer an issue? I came looking to see if anyone had tips for customizing inlay hints but ended up just finding them myself... leaving this here in case others come looking, these are the various VSCode settings I have found related to inlay hint styling:

* `editor.inlayHints.enabled`
* `editor.inlayHints.fontFamily`
* `editor.inlayHints.fontSize`
* `workbench.colorCustomizations` (these appear to support RGBA colors like `#00000000` if you want e.g. transparent background)
    * `editorInlayHint.background`
    * `editorInlayHint.foreground`
    * `editorInlayHint.parameterBackground`
    * `editorInlayHint.parameterForeground`
    * `editorInlayHint.typeBackground`
    * `editorInlayHint.typeForeground`

I _think_ this means this issue can be closed, but perhaps is helpful for others looking for the settings to customize their hints as they wish. Maybe there could be a documentation change that could point people to the right settings that would be a little more discoverable?

**Comment by lnicola** [comment]
@ian-h-chamberlain good summary. Do you want to file a PR to the manual (it's in this repository, under `docs/user`)?

**Comment by ian-h-chamberlain** [comment]
> @ian-h-chamberlain good summary. Do you want to file a PR to the manual (it's in this repository, under `docs/user`)?

Sure, I'll see if I have some time to do this soon

**Comment by Veykril** [comment]
We have changed to the native inlay hints of VSCode, changing font and font size is now possible via `editor.inlayHints.fontSize` and `editor.inlayHints.font` respectively.
