### ISSUE TITLE
How do I automatically close the Angle brackets?

### ISSUE THREAD

**Issue by junknet** [rust-analyzer/rust-analyzer#6451]
RLS has this function.

**Comment by matklad** [comment]
In terms of how to do this properly, we should introduce an LSP extension for this, similar to the "matching brace". 

To fix this VS Code way, I think the best approach is to contribute https://code.visualstudio.com/api/language-extensions/language-configuration-guide upstream.

**Comment by junknet** [comment]
![image](https://user-images.githubusercontent.com/55597646/98317082-c320ad00-2016-11eb-93f3-5e60021eede3.png)
Well, I added some configuration.But it only not working under this extension.

**Comment by tigregalis** [comment]
For what it's worth, I use these two custom keybindings in `keybindings.json` in VS Code:
```javascript
  { // wraps selection in angle brackets
    "key": "shift+,", // should be `<` key
    "command": "editor.action.insertSnippet",
    "args": {
      "snippet": "<${1:${TM_SELECTED_TEXT}}>"
    },
    "when": "editorHasSelection && editorLangId == 'rust'"
  },
  { // wraps blinking cursor in angle brackets
    "key": "shift+,", // should be `<` key
    "command": "editor.action.insertSnippet",
    "args": {
      "snippet": "<$0>"
    },
    "when": "editorTextFocus && !editorHasSelection && editorLangId == 'rust'"
  },
```

The first only takes effect when something (or many somethings) is selected. The second takes effect if you've got nothing selected (just a blinking cursor or multiple). This does have the unintended effect however, of  writing `if a <>` when you actually wanted to write `if a <`, but I've figured that I'm far more often writing type parameters in Rust than numerical comparisons.

**Comment by dustypomerleau** [comment]
For VS Code specifically, this is very easy to contribute via the Rust Syntax extension. I have been considering doing this with the following pairs:

```json
    "autoClosingPairs": [
        { "open": "{", "close": "}" },
        { "open": "[", "close": "]" },
        { "open": "(", "close": ")" },
        { "open": "<", "close": ">" },
        { "open": "\"", "close": "\"", "notIn": ["string"] },
        { "open": "/*", "close": " */" }
    ],
```

There are 2 issues with doing it this way.

1. The first has already been mentioned, which is that you need to perform an extra deletion step to get the `<` comparison operator. That's why I planned to leave out `'`, so you don't end up needing a deletion step for every lifetime annotation. I think, on balance, it's probably worth it for `<`, given the amount of angle bracket use in Rust. 
1. The other issue is that VS Code will not automatically upstream the language definition when they upstream the Rust Syntax grammar, which means that I'll need to investigate whether we can get that shipped as well. At least initially, it would only be available via the Rust Syntax extension.

**Comment by junknet** [comment]
![Uploading image.png…]()
