### ISSUE TITLE
extract_struct_from_enum_variant assist doesn't work with multiple files

### ISSUE THREAD

**Issue by ArifRoktim** [rust-analyzer/rust-analyzer#6459]
After #6287 given the following files, running "Extract struct from enum variant" on `A::One` will do nothing:

```rust
// lib.rs
pub enum A {
    One(u32, u32)
}
pub fn func() {
    let _a = A::One(1, 2);
}

pub mod another;
```
```rust
// another.rs
use super::*;

pub fn func() {
    let _b = A::One(3, 4);
}
```
If you comment out `pub mod another` and try again, it will work as intended just for `lib.rs`.

---
I think this is the cause:
https://github.com/rust-analyzer/rust-analyzer/blob/060c8b2c96a0de4a131c4d780d2aac80afe13de8/crates/assists/src/handlers/extract_struct_from_enum_variant.rs#L84-L87
From my perusal of `AssistBuilder`, calling `edit_file` in a loop doesn't do much. The builder's `file_id` is only used later on when finishing the builder.
cc @Veykril 

---
Note: This assist was also bugged before #6287, but in a different way. It would apply both files' changes to `lib.rs` and leave `another.rs` unchanged:
<details>
<summary>lib.rs</summary>

```rust
pub struct One(pub u32, pub u32);

pub enumOne(3, 4)
    One(One)
}
pub fn func() {
    let _a = A::One(One(1, 2));
}

pub mod another;

```
</details>

**Comment by Veykril** [comment]
Hm, `edit_file` really doesn't do anything aside from setting the file id, so in this case it does indeed try to apply **all** changes to one file still, but it panics again now due to [overlapping edits](https://github.com/rust-analyzer/rust-analyzer/blob/7c94f1cb5e86739864871dc56fcbd7a6de116315/crates/text_edit/src/lib.rs#L187) which causes this to fail overall instead of only editing one file incorrectly.
In general assists seem to be able to only edit one file only, another example that only edits one file is `remove_unused_param`.

So we should probably allow AssistBuilder to edits to different files, this is technically already [supported](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/assists/src/assist_context.rs#L225-L232) but just not public api.

@matklad thoughts?

**Comment by matklad** [comment]
Yeah, assists should totally allow editing multiple files. I think We had this functionality, but maybe I am remembering things? 

The API challenge here is to:

* make the common case of editing one file simple
* but make the rare case of editing multiple files possible

I think `edit_file` stateful API is the right one, but we probably should actually fix it to commit edits to previous files.

**Comment by matklad** [comment]
That is, I think `edit_file`  should call `.commit` automatically if the current edit is not empty.

**Comment by Veykril** [comment]
I believe most if not all tests only edit one file in their fixtures which is why they all still pass, given you can only hand the expected output of one edited file in the assist checks. So multi-file testing isn't doable currently.
