### ISSUE TITLE
Hovering over `std::env` shows `()`

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#652]
Completions work fine with `std::env` but hovering over it returns `()` which is suspicious.

**Comment by flodiebold** [comment]
Do you have an example?

**Comment by kjeremy** [comment]
```rust
fn main() {
    std::env
}
```

Hover over the `env`.

**Comment by flodiebold** [comment]
Oh, that's just because we can't resolve `std::env` to a value, so we basically assume it has to be `()` if you're returning it from a function with that return type :wink:  If you add a semicolon, you'll see that it now has unknown type. Or if you write `let y: usize = std::env;`, we'll think it has type `usize` :smile:

**Comment by kjeremy** [comment]
Shouldn't it resolve to a module like it does for completions? Or am I just making that up? :)

**Comment by flodiebold** [comment]
The module is in the type namespace, it doesn't have a value :) See here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=29e709ab155592585e1f839cdd37b21a rustc says
```
error[E0423]: expected value, found module `std::env`
 --> src/main.rs:2:5
  |
2 |     std::env;
  |     ^^^^^^^^ not a value
```

**Comment by matklad** [comment]
Yeah, I think that's intended behavior!
