### ISSUE TITLE
Treat crates.io and git dependencies as immutable

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#6623]
Refactorings like "rename symbol" should not attempt to change their source. Also if possible opening them through for example "goto definition" should open a read-only editor.

**Comment by kjeremy** [comment]
There's no support in LSP for opening documents in a read-only mode (maybe we could hijack the document URI?) but we can at least change what we return for edits.

**Comment by tech6hutch** [comment]
I just got bitten by this. I tried to rename my import of something from the std library...and instead rust-analyzer seems to have _renamed it in the std library itself_, since I then got an error inside std. (Running `rustup install stable` seems to have fixed it, despite it saying "unchanged", unless it just fixed itself.)

**Comment by matklad** [comment]
closed by #8540
