### ISSUE TITLE
Fails to identify type of vec![] macro

### ISSUE THREAD

**Issue by thirdsgames** [rust-analyzer/rust-analyzer#6837]
In an empty (latest rust-analyzer, nightly rust) VSCode project, I am getting the following (related) errors to do with the `vec!` macro.
![image](https://user-images.githubusercontent.com/50671761/101955389-9bb09780-3bf5-11eb-95b7-783ab28dd90c.png)
It seems as if rust-analyzer is maybe unable to resolve the second type parameter related to the new allocator API, and that error stops it from filling in the first parameter. Weirdly, it semi-correctly identifies a `char` in the following image, but thinks that it is part of an array.
![image](https://user-images.githubusercontent.com/50671761/101955513-de726f80-3bf5-11eb-8675-45c40f83f2c5.png)
It also identifies `vec!["];` to be a `Vec<[&str; _]>`.

This is probably not a direct repeat of #6668 - I'm using a nightly version of rust-analyzer released after that issue was patched. Also, using the normal `Vec` constructor, and adding elements in afterwards, works fine thanks to type inference - it's only a problem with the macro, it seems.

**Comment by flodiebold** [comment]
I can't reproduce this with current rust-analyzer. Can you check whether it's still happening?

**Comment by thirdsgames** [comment]
Yes, I've just updated rust-analyzer vscode plugin, the language server, and rustup. The issue is still here. If it's relevant, I'm using `x86_64-pc-windows-msvc`.

**Comment by flodiebold** [comment]
Ah wait, I missed that this is with nightly rust.

**Comment by thirdsgames** [comment]
Yeah, I'm pretty sure it's to do with the new allocator API adding extra type parameters to `Vec`.

**Comment by flodiebold** [comment]
Ah, `vec![1i32]` now expands to `<[_]>::into_vec(box [1i32])`, and we're having problems either with the `Box` self type or with something about the new allocator parameter.

**Comment by Pawel82S** [comment]
I've got the same problem but with stable rust v 1.50

**Comment by detrumi** [comment]
It's the `box_syntax` feature:
```
let a = <[_]>::into_vec(Box::new([1i32])); // Vec<i32, Global>
let a = <[_]>::into_vec(box [1i32]); // Vec<{unknown}, {unknown}>
```

**Comment by flodiebold** [comment]
How does `box` interact with the allocator parameter? Does it always use the default?

**Comment by detrumi** [comment]
According to [rust#58457)](https://github.com/rust-lang/rust/pull/58457):
> Ideally, inherent methods like Box::new would be applied to
Box<T, A: Alloc + Default>, but as of now, that would be backwards
incompatible because it would require type annotations in places where
they currently aren't required.

So at the moment `Box::new` always uses `std::alloc::Global`, but that may change in the future.
I think box_syntax already supports custom allocators, and defaults to the `Global` (like how `Vec` does for example, but in this case built into the syntax instead of as a default type param).

**Comment by detrumi** [comment]
Tried it out, and turns out that box_syntax currently always uses `std::alloc::Global` ([playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=515c6da90e25e8ed6ba15e7aa52e41dd))
So I think rust-analyzer has to set that default somewhere, instead of trying to infer it.

**Comment by flodiebold** [comment]
Ok, that's probably the reason it doesn't work then. The handling for the box syntax is here:
https://github.com/rust-analyzer/rust-analyzer/blob/803ff2e55eeb6bd1d9028fbbffe34721f0e6d459/crates/hir_ty/src/infer/expr.rs#L509-L512
Currently we just fill it with a type variable; we could instead look up the generic defaults (using `db.generic_defaults`) and put them there.
