### ISSUE TITLE
Auto rustdoc prefix insertion

### ISSUE THREAD

**Issue by UebelAndre** [rust-analyzer/rust-analyzer#6936]
I'm not sure if this is an existing feature request, but i'd be awesome to have the vscode extension auto-add a rustdoc comment block prefix to the next line when typing documentation.

Example:

Say I have some function and you want to write documentation for it.
```rust
pub fn hello() {
    println!("hello");
}
```

I start by adding my comment block
```rust
/// A function that prints hello
pub fn hello() {
    println!("hello");
}
```

But when I go to write a second line, I must manually type `///` to continue the block
```rust
/// A function that prints hello
and is always followed by a new line
pub fn hello() {
    println!("hello");
}
```

I would like the editor to recognize I'm writing a rustdoc block and auto fill the next line for me so my code would like like the following:
```rust
/// A function that prints hello
/// and is always followed by a new line
pub fn hello() {
    println!("hello");
}
```

I'm happy to close this if it's a duplicate, but if not it'd be a nice addition 😄 🙏

**Comment by lnicola** [comment]
Which editor are you using? In code you can do this: https://rust-analyzer.github.io/manual.html#on-enter.

**Comment by UebelAndre** [comment]
Oh nice! I am using vscode and that's exactly what I want. Why isn't this enabled by default? I think that's the same behavior the previous vscode rust extension had.

**Comment by lnicola** [comment]
Because each Enter keypress will have to go to the extension (there's no way to do that only when the cursor is on a comment line) and if the extension is busy or stuck, you won't be able to type any more, which made a lot of users complain loudly.

This can even happen if another extension is busy: there's a single extension host process for all of them, and it's single-threaded. So another extension can delay the `rust-analyzer` Enter handler indefinitely.

**Comment by lnicola** [comment]
Closing this to keep the issue tracker (relatively) tidy.
