### ISSUE TITLE
Go to definition doesn't work for unqualified function-like proc macros

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#7073]
```rust
// using the unzip-n crate

use unzip_n::unzip_n;

unzip_n!(3); // trigger go to def here
unzip_n::unzip_n!(4); // this one works

fn main() {}
```

**Comment by AdnoC** [comment]
Issue is that `hir::MacroDef` does not have an ast-node when it is for a proc-macro. (See https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/proc-macro.20no.20ast-node). When doing `unzip_n::unzip_n!(4)` we classify it as a function rather than a macro. And this for some reason works.

Specifically, the `NameRefClass` for `unzip_n!(3)` is

`Definition(Macro(MacroDef { id: MacroDefId { krate: CrateId(53), ast_id: None, kind: ProcMacro(ProcMacroExpander { krate: CrateId(53), proc_macro_id: None }), local_inner: false } }))`

and the `NameRefClass` for `unizp_n::unzip_n!(4)` is

`Definition(ModuleDef(Function(Function { id: FunctionId(1115) })))`

**Comment by jonas-schievink** [comment]
This was fixed by https://github.com/rust-analyzer/rust-analyzer/pull/8088, I'll try to add a test
