### ISSUE TITLE
`#![allow(clippy::` incorrectly completes with a leading `clippy::`

### ISSUE THREAD

**Issue by RDambrosio016** [rust-analyzer/rust-analyzer#7144]
### Reproducible code

```rs
#![allow(clippy::
```

Select any of the lints, it will be completed as `#![allow(clippy::clippy::or_fun_call)]` for example, which is incorrect.

I presume this is because vsc does not consider `clippy::` to be a full ident per the rust grammar, therefore it thinks the completion should go after it because the first part isnt part of it

**Comment by bnjjj** [comment]
I take the point

**Comment by crumblingstatue** [comment]
I noticed that what the user typed so far is highlighted in the completion hints
![image](https://user-images.githubusercontent.com/1521976/124822472-372d9f00-df70-11eb-8ae4-5d0a54249cb4.png)
However, if `::` is typed after `clippy`, the highlighting stops working.
![image](https://user-images.githubusercontent.com/1521976/124822606-63e1b680-df70-11eb-8546-8b8c440f40c3.png)
Is the above assessment correct in this being a fault of visual studio code? Should it be fixed there, or can it be fixed in rust-analyzer?

**Comment by bjorn3** [comment]
Something similar happens with `pub(crate)` which turns into `pub(pub(crate))`.

**Comment by crumblingstatue** [comment]
Looks like the attribute is being parsed as
```
ATTR@0..18
      POUND@0..1 "#"
      L_BRACK@1..2 "["
      META@2..17
        PATH@2..7
          PATH_SEGMENT@2..7
            NAME_REF@2..7
              IDENT@2..7 "allow"
        TOKEN_TREE@7..17
          L_PAREN@7..8 "("
          IDENT@8..14 "clippy"
          COLON@14..15 ":"
          COLON@15..16 ":"
          R_PAREN@16..17 ")"
      R_BRACK@17..18 "]"
 ```

Shouldn't that bet a `COLON2` instead of 2 `COLON`s?

**Comment by RDambrosio016** [comment]
Macro invocations are raw token trees, so no tokens are joined because there is no "semantic meaning"

**Comment by crumblingstatue** [comment]
Welp, I give up for now, haha. I have no idea how to debug this.

**Comment by RDambrosio016** [comment]
I think this is just an issue with vsc not thinking the colons form a full ident and therefore putting the completion just after the colons, while RA should be telling it to replace everything in the completion

**Comment by Veykril** [comment]
The problem here is that we do not recognize the `clippy::` prefix in the completion building process. So when we insert the completion we insert if after the already existing `clippy::` instead of replacing it.

Basically the `ctx.source_range()` call here is incorrect, instead we need to fetch the ranges of the `clippy` and `::` token as `ctx.source_range()` returns the range of the current identifier we are completing, which isn't correct in this case. https://github.com/rust-analyzer/rust-analyzer/blob/9f24cc7126f6508dcc9e429a33bd12975873d3e4/crates/ide_completion/src/completions/attribute/lint.rs#L24

**Comment by Veykril** [comment]
Fixing this is rather tricky as we have to basically manually reparse the input we are expecting. It would be great if we could reuse that path completion infra here but inputs to attributes are just random tokens to us.
