### ISSUE TITLE
autocomplete for use statements fills in function parameters when function name starts with `impl`

### ISSUE THREAD

**Issue by lopopolo** [rust-analyzer/rust-analyzer#7222]
When autocompleting a `use` statement for a free function at the root of a module, if the function name starts with `impl`, the autocomplete suggestion fills in placeholders for the function parameters.

## Screenshots

<img width="1422" alt="Screen Shot 2021-01-09 at 10 45 36 AM" src="https://user-images.githubusercontent.com/860434/104106127-2a9de780-5268-11eb-9965-8c9ad6474537.png">

<img width="1422" alt="Screen Shot 2021-01-09 at 10 45 39 AM" src="https://user-images.githubusercontent.com/860434/104106129-32f62280-5268-11eb-81f1-24a97d1c51a5.png">

**Comment by Veykril** [comment]
The problem seems to be that we immediately stop parsing the use statement and start parsing an impl block which then breaks the call parens check here https://github.com/rust-analyzer/rust-analyzer/blob/927657432e77bc971f2b853dec7b98b909351541/crates/completion/src/render/builder_ext.rs#L32-L35.
For `pub use self::pri::impl;` we get the following RAST
```
  USE@325..344
    VISIBILITY@325..328
      PUB_KW@325..328 "pub"
    WHITESPACE@328..329 " "
    USE_KW@329..332 "use"
    WHITESPACE@332..333 " "
    USE_TREE@333..344
      PATH@333..344
        PATH@333..342
          PATH@333..337
            PATH_SEGMENT@333..337
              SELF_KW@333..337 "self"
          COLON2@337..339 "::"
          PATH_SEGMENT@339..342
            NAME_REF@339..342
              IDENT@339..342 "pri"
        COLON2@342..344 "::"
  IMPL@344..349
    IMPL_KW@344..348 "impl"
    ERROR@348..349
      SEMICOLON@348..349 ";"
```
