### ISSUE TITLE
[code] rust-analyzer failed to discover workspace

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#7268]
I just discovered that rust extensions seems activated accidently in my cpp project, it shows this:

![image](https://user-images.githubusercontent.com/33961674/104596629-860b1380-5674-11eb-97c9-3a6fdd8cf908.png)

**Comment by lnicola** [comment]
Can you upload it somewhere? Or trim it down to see what's triggering it?

Is it a mixed Rust/C++ project?

**Comment by GopherJ** [comment]
> Can you upload it somewhere? Or trim it down to see what's triggering it?
> 
> Is it a mixed Rust/C++ project? Do you have a `Cargo.toml` in there?

I'll try to do it, it's a pure c++/nodejs/vuejs project, there aren't any rust related things

**Comment by heaths** [comment]
I'm seeing this in a large monorepo full of file extensions, namely https://github.com/azure/azure-sdk-for-net. Perhaps this error doesn't need to display an error dialog but just trace to its associated output?

**Comment by heaths** [comment]
Not sure it helps, but this was the only message I saw printed to the "Rust Analyzer Language Server" output window:

```text
[ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("c:\\src\\azure-sdk-for-net")]
```

**Comment by JonnyBGod** [comment]
I am also getting this error message on mostly every non rust project. And also see rust-analyser running for these projects where it should be ignore.

![image](https://user-images.githubusercontent.com/405206/107125289-dc98f580-68a0-11eb-822b-0661ed22bcdf.png)

**Comment by lnicola** [comment]
> I'm seeing this in a large monorepo full of file extensions, namely https://github.com/azure/azure-sdk-for-net. Perhaps this error doesn't need to display an error dialog but just trace to its associated output?

Are you opening any file? I can't reproduce:

![image](https://user-images.githubusercontent.com/308347/107389350-634b0e00-6aff-11eb-88cc-9b5cf11b2571.png)

**Comment by GopherJ** [comment]
@lnicola no I just ran `code .`

**Comment by ishowta** [comment]
Probably the same issue as https://github.com/rust-analyzer/rust-analyzer/issues/2533#issuecomment-622930182.

If so, it's because VSCode forces run the extension at scan directory timeout (https://github.com/microsoft/vscode/issues/73656).

**Comment by lnicola** [comment]
This was actually mentioned in the Code release notes: https://github.com/microsoft/vscode/issues/110510#issuecomment-770133700. Unfortunately, that fix does nothing for us because we set `workspaceContains:**/Cargo.toml`.

**Comment by heaths** [comment]
There's another issue open on the performance of this depth search, and I [proposed](https://github.com/microsoft/vscode-azurefunctions/issues/2659#issuecomment-783525759) a max-depth setting that could help this. We did this for VSIX extension discovery in VS and a max depth of, IIRC, 3 made a huge difference. For this extension, perhaps taking a look at some popular repos and determining depth would be handy. For one project I'm working on, 4 would be sufficient.

**Comment by heaths** [comment]
I should've read the whole URL in the address bar. Wrong repo, but a workaround was suggested that accomplishes what I mentioned above:

```json
workspaceContains:*/example.txt
workspaceContains:*/*/example.txt
workspaceContains:*/*/*/example.txt
```

**Comment by lnicola** [comment]
No, that's a good idea, thanks for posting.

**Comment by bugadani** [comment]
I have a mixed C/CMake/Rust project, where I would very much appreciate if rust-analyzer worked properly. Unfortunately, I'm greeted with the message:

```
[ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("<...>")]
```

I'm using the `linkedProjects` setting as a workaround but it's far from ideal (for example, I have no idea how to add `std` as a dependency, or why the `test` cfg is disabled even if it shouldn't be?) as I don't know how I can make RA realize it is a cargo project but buried deep in the workspace.

**Comment by bjorn3** [comment]
Are you pointing `linkedProjects` to the `Cargo.toml` file or a rust source file? If you point it to the `Cargo.toml` file libstd should work.

**Comment by bugadani** [comment]
Thanks, I didn't know I can do that.

**Comment by inaryart** [comment]
+1 pure cpp project

**Comment by HuskyNator** [comment]
I don't consider this a fix, but a workaround.
This breaks the entire extension for way too many folder structures and workspace setups.

If possible please reopen this.

**Comment by flodiebold** [comment]
@HuskyNator can you provide an example use case / workspace setup where this doesn't work?

**Comment by jwarlander** [comment]
> @HuskyNator can you provide an example use case / workspace setup where this doesn't work?

I can chime in here a bit, as I ran across this issue just now.. I was forced to move a Rust workspace to the top level of our monorepo (that includes a lot of Python stuff, infrastructure setup, etc etc) in order to make it work with the analyzer.

It's "fine" in my particular case, but breaks a bit with how we have some other bits organized, and I definitely imagine cases where it could be harder to work around.

**Comment by bjorn3** [comment]
You can point the `rust-analyzer.linkedProjects` config to the workspace `Cargo.toml`.

**Comment by lnicola** [comment]
Counter-point: I happen to have an unrelated Code extension that goes through the open projects trying to see if it should enable its features. Supposedly, it's depth-restricted, but still manages to run out of memory and crash my extension host every couple of minutes.

I really don't think extensions should be doing this.

**Comment by flodiebold** [comment]
AFAIU, there are two separate questions here. 

One is, in which workspaces should rust-analyzer be activated at all. This is the question that this issue is about. If we wrongly activate in workspaces that have nothing to do with Rust, people get annoyed, and as @lnicola mentions it can lead to instability and other problems. Hence why we now limit this to workspaces where we find a Cargo.toml relatively shallowly. I think setting `linkedProjects` doesn't influence this, but maybe it could? I.e. if there's a `linkedProjects` set and the linked Cargo.toml does exist then we should always activate?

The other question is about discovering the actual Cargo projects. Currently AFAIK we only look for projects in the top-level folder and one level down. So if there's a Cargo workspace two levels down somewhere, we do activate the extension, but don't automatically find and load the Cargo workspace, I think? This is a performance consideration, since we don't want to eagerly load all Cargo workspaces in a big monorepo for example. The `linkedProjects` setting helps here, and we've discussed lazily loading Cargo workspaces when you open a file from them and suggesting adding them to the `linkedProjects` in that case.

**Comment by jwarlander** [comment]
Is the workspace activation issue so "static"? Can't rust-analyzer simply be activated if I open a `.rs` file, and then check if it finds a `Cargo.toml` file a few steps back up (until it hits the workspace root at least I guess)?

**Comment by HuskyNator** [comment]
> Is the workspace activation issue so "static"? Can't rust-analyzer simply be activated if I open a `.rs` file, and then check if it finds a `Cargo.toml` file a few steps back up (until it hits the workspace root at least I guess)?

This is how code-d (Dlang) works as well I believe. Heck, every extension that provides languages support I ever used provided this 'feature'. I believe most of those in a similar way @jwarlander describes.

**Comment by DavidZyy** [comment]
I also get this problem

**Comment by typetetris** [comment]
Just hitting this. Would be cool if there was an option to make the extension search the workspace for a Cargo.toml.

**Comment by xbtchunky** [comment]
Wow this has been an issue for almost 3 years and not fixed, very unfortunate

**Comment by xbtchunky** [comment]
I was getting this issue and couldn't figure it out until I realized it was because vscode was trying to load cargo --version from Windows and my cargo installation is on wsl in ~/.cargo/bin/cargo

I opened "remote explorer" in the sidebar for VSCode and right clicked the distro I'm using and hit "Connect to WSL" and it opened a new window of VSL and fixed it.

**Comment by yinyunpan** [comment]
Because the rust-analyzer cannot recognize that the folder with only a single file "main. rs" is a rust project, the initialization project must be created through cargo.

`cargo new study1`

![image](https://user-images.githubusercontent.com/6118991/200158321-f9b6313f-fd42-4df7-abea-4f58c3095772.png)

**Comment by wugifer** [comment]
plugin status: Activated by onTaskType:cargo event: 6ms
