### ISSUE TITLE
Self in struct is not highlighted as usage

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#7443]
![substrate-1611640509810](https://user-images.githubusercontent.com/3784017/105806052-d4ee6c80-5fd5-11eb-9595-9f33f4aafe06.gif)

_Originally posted by @0x7CFE in https://github.com/rust-analyzer/rust-analyzer/issues/3887#issuecomment-767315005_

**Comment by lnicola** [comment]
CC @Veykril

**Comment by Veykril** [comment]
The issue here is that we basically only do a text search for the identifier `HostState` here before then resolving those found identifiers, but for this case we would have to do a search for `Self` as well which. This shouldn't cause many problems but its probably better to do this after I'm done refactoring those areas.
