### ISSUE TITLE
Some methods won't show its traits on autocompletion (as it should per #7297)

### ISSUE THREAD

**Issue by rodrigocfd** [rust-analyzer/rust-analyzer#7456]
As seen on [Changelog #61](https://rust-analyzer.github.io/thisweek/2021/01/25/changelog-61.html), #7297 introduced trait information on autocompletion. It works perfectly here (VSCode + Win10), except the following methods won't show its traits:

* clone
* clone_from
* clone_into
* into
* to_owned

Is it expected?

**Comment by flodiebold** [comment]
I think the trait only shows if it's not in scope and would be autoimported, to show that an import will happen :thinking:

**Comment by Veykril** [comment]
Yes the trait should only show up in the completion text if the completion would import it: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/completion/src/item.rs#L329-L333
As in it is a hint to the user that this completion will add an import.

**Comment by rodrigocfd** [comment]
@flodiebold @Veykril I understand.

Personally, I believe that showing all source traits adds insightful information. I don't know if you guys agree with me, though.

**Comment by SomeoneToIgnore** [comment]
When this is added, it might be nice to distinguish somehow the completions where the trait import will be added from the ones that have this trait imported already: those are different kinds of completions under the hood and it helps debugging different issues with them.


If somebody wants to add the labels, this can be done the following way: 

We need to adjust `render.rs` [module](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/completion/src/render.rs) and all the places where the associated items that have traits are rendered into completion items.

You can search for `is_deprecated_assoc_item` method usage: it's used in `render.rs` and 3 submodules: `const_.rs`, `function.rs` and `type_alias.rs` to add the deprecation flag into the completion associated items who have the deprecated trait.

So in all those places you can already get the information whether some trait is associated with the item or not.
When you have it, all that's left is to add it into the completion item's label and maybe adjust the lookup text, similar to the code linked in the [message above](https://github.com/rust-analyzer/rust-analyzer/issues/7456#issuecomment-768423050)

To get the trait path to the label, you will need to call [`find_use_path`](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/hir/src/code_model.rs#L407) method on it, but we need the module for this, since the module paths are different depending on which module we're looking them from.
The module can be retrieved from the `CompletionContext`'s fields.

After that, tests can be added into completion modules: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/completion/src/completions/dot.rs and https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/completion/src/completions/qualified_path.rs to ensure that we actually display trait paths in all completion cases.
