### ISSUE TITLE
Semantic Highlighting: Function called str is considered builtin type

### ISSUE THREAD

**Issue by CryZe** [rust-analyzer/rust-analyzer#7479]
```rust
str();
```
is considered the builtin str type. Probably similar issues with the others.

![https://i.imgur.com/9uohbVe.png](https://i.imgur.com/9uohbVe.png)

**Comment by Veykril** [comment]
Hmm we don't seem to resolve these properly at all when classifying them as `goto def` and all the other stuff doesn't work. Oh wait this actually seems to be related to the fact that the type namespace shadows the value namespace here again similar to the problem here https://github.com/rust-analyzer/rust-analyzer/issues/7408 😕
