### ISSUE TITLE
Variables in destructing patterns are highlighted incorrectly

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#7524]
In code like
```rust
        let Meta { stamp, build_llvm_config, out_dir, root } = unimplemented!();
        t!(stamp.remove());
```
putting your cursor on `stamp,` does not highlight the use on the line below.

![image](https://user-images.githubusercontent.com/23638587/106628106-7716d300-6547-11eb-8d84-2e1d4cc6c3fe.png)

Strangely, putting the cursor on `stamp.` works correctly (it highlights `stamp` on both lines):

![image](https://user-images.githubusercontent.com/23638587/106628057-69614d80-6547-11eb-98a7-0301c6418b57.png)

Reproduction steps: https://github.com/rust-lang/rust/blob/e13786548f6313dd931a63932a802f6bdf7facc9/src/bootstrap/native.rs#L185

**Comment by Veykril** [comment]
The problem here is that fields of destructure patterns are both references to names(fields of the struct declaration) and new declarations(the new variables that are brought into scope).
As can be seen here, the highlight currently resolves to the field declaration. How to handle this hasn't been really thought about yet I think.
![image](https://user-images.githubusercontent.com/3757771/107428737-5fc97e00-6b23-11eb-988e-a4cb1b9cd388.png)

**Comment by matklad** [comment]
>How to handle this hasn't been really thought about yet I think.

It actually has been explicitly thought through and designed, after hitting the same problems in IntelliJ! The core type here is `NameClass`:

https://github.com/rust-analyzer/rust-analyzer/blob/325140a165e1081432cb758fc4114a3eff0af490/crates/ide_db/src/defs.rs#L286-L292

It explicitly encapsulates the knowledge that a single source ident actually points to two different defs. We just forget about this somewhere along the way. hightligt_related calls into `find_def` here:

https://github.com/rust-analyzer/rust-analyzer/blob/325140a165e1081432cb758fc4114a3eff0af490/crates/ide/src/highlight_related.rs#L61

which erases this info via the `.referenced` call here:

https://github.com/rust-analyzer/rust-analyzer/blob/325140a165e1081432cb758fc4114a3eff0af490/crates/ide/src/references.rs#L120

I guess, it makes sense replace the `.referenced` function with something which makes it clear at the call-site that we are doing a bised choice....

**Comment by Veykril** [comment]
Ah I thought this wasn't really final yet due to the comment here 😅
https://github.com/rust-analyzer/rust-analyzer/blob/325140a165e1081432cb758fc4114a3eff0af490/crates/ide_db/src/defs.rs#L300-L301

I guess it might also make sense to check all the places of `NameRefClass::referenced` and `NameClass::referenced_or_defined` whether they want the local or field ref.

When on a shorthand it feels like usually you would expect things to act on the local instead of the field ref, at least that's what I think?

**Comment by matklad** [comment]
>I guess it might also make sense to check all the places of NameRefClass::referenced and NameClass::referenced_or_defined whether they want the local or field ref.

Uhu! I'd guess it even makes sense to maybe just remove the `referenced` and write explicit matches at the call site..

**Comment by Veykril** [comment]
Ye I got a feeling that might be better, fortunately the two enums arent that big. I'll take a look.
