### ISSUE TITLE
support autocompletion in format string

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#7533]
now RA doesn't autocomplete `aa` `bb` `cc`, is it possible to support the autocompletion here?
![Peek 2021-02-03 15-46](https://user-images.githubusercontent.com/33961674/106714827-53cb5100-6637-11eb-81d7-fa83de551bba.gif)

**Comment by petr-tik** [comment]
i would like to take this one, if possible?

I haven't done much completion/static analysis work before - so might take some time and would welcome any pointers.

**Comment by Veykril** [comment]
Completion in general lives [here](https://github.com/rust-analyzer/rust-analyzer/tree/master/crates/completion/src). First steps would probably be to check and store the string literal/fmt macro call the cursor is on [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/completion/src/context.rs). Then you probably want to add a new module [here](https://github.com/rust-analyzer/rust-analyzer/tree/master/crates/completion/src/completions) for format string completion and see how the other modules roughly work to get an understanding for what to do. If you got specific questions feel free to ask them here or on the zulip.

**Comment by petr-tik** [comment]
awesome - thanks for the pointers. Does being inside a string count the same as being inside a macro? 

Also, wanted to check if I should complete variables of non-String type (like u64) but that implement Display trait?

**Comment by Veykril** [comment]
Okay actually you might not even need to add anything to the context, what you can do is check whether `token`(the field here https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/completion/src/context.rs#L36) is a string token and then check if that is in a format macro invocation which is already implemented here, https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/syntax_highlighting/format.rs#L30-L47. You can probably move that function so that you don't have to duplicate it, to `ide_db` or the `syntax` crate, not sure where it fits better but putting it into `token_ext` in the syntax crate is probably the simplest for now.

You probably Completing any var seems fine at first I'd say.

**Comment by Veykril** [comment]
We show completions in format strings here now, though the completions have to be explicitly requested in this position(I assume this is VSCode specific behaviour for when one types in a string literal?)

**Comment by norskeld** [comment]
> though the completions have to be explicitly requested in this position

If anyone looking for a fix: to show autocompletions in format strings in VS Code, you can enable `quickSuggestions` for strings in your `settings.json`:

```jsonc
{
  "editor.quickSuggestions": {
    "strings": "on"
  }
}
```
