### ISSUE TITLE
Setting to enable/disable specific codelenses

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#757]
Most language servers provide a way to disable different codelenses. We should probably do the same.

**Comment by matklad** [comment]
I am even all for having a flag for any single feature: it's a nice user experience if you can enable a thing which is slow/buggy for your project.

**Comment by kjeremy** [comment]
I'll tackle this along with the configuration messages.

**Comment by gilescope** [comment]
In particular if people could still run tests while the implementation code lens is turned off that would make some people happy - there are purists that don't like the lenses as they like each line to be exactly the same height. Ideally I think they'd like a gutter way of running / debugging tests rather than code lenses but for now this seems easier.

**Comment by ArtemGr** [comment]
The lenses also flicker a lot during editing, making the code jump up and down. Disabling the lens would allow users like me to workaround that problem whenever it appears or reappears.

**Comment by vsrs** [comment]
Fixed in https://github.com/rust-analyzer/rust-analyzer/pull/4499
