### ISSUE TITLE
Using as a code navigation tool

### ISSUE THREAD

**Issue by RazrFalcon** [rust-analyzer/rust-analyzer#764]
The title of this issue is a bit misleading, but I don't know how to formulate it better.

Let's say I want to check that a function can panic. AFAIU, I have to:

1. iterate over functions in a specific function
1. go to definition for each function
1. check that it doesn't have `panic!` macro or something
1. go to 1

So I have to have an access to the Rust AST with Go To Definition capabilities. Can `rust-analyzer` help me with this task or is it out of scope?

**Comment by matklad** [comment]
It is somewhat possible, yeah.

See, for example, https://github.com/rust-analyzer/rust-analyzer/pull/760, which searches for `dbg!` calls. 

The hard bit here is "go to definition for each function". It somewhat works currently, but there's a long way before it becomes reliable.

In terms of "how do I actually implement this?", it looks like a pretty niche use-case to me. It would be cool to expose some kind of scripting API so that you can implement similar analysis on the fly. There's no such API yet, but you could depend on rust-analyzer (as a git repo) and implement this.

**Comment by RazrFalcon** [comment]
Yes, I want to implement this as a separate crate, mainly because it will probably be very expensive. So I'm not asking to add this to the `rust-analyzer` directly, but rather to provide an api for plugins like this one.

I understand that there are no stable API yet, but I'm looking for at least something to start with.

**Comment by matklad** [comment]
@RazrFalcon the two main APIs you need to interact with are:

* `AnalysisHost/Analysis` from `ra_ide_api` They can be used to create a "context" for analysis and also to ask high-level questions about the code

* Various structs from `code_model_api` module of `ra_hir` crate. They can be used to conduct a low-level analysis of the code.

In terms of "how to create Analysis for my Cargo project" and "how to expose analysis results as CLI/HTML/whatever" we don't have a good answer currently. You can check `ra_lsp_server` to see how do we do this in context of LSP.

**Comment by RazrFalcon** [comment]
Thanks. Will look into it.

**Comment by matklad** [comment]
Let's close the issue then!

If you have any more questions, feel free to open other issues or to use the Discord (we might also be migrating to rust-lang/compiler's zulip soon....)
