### ISSUE TITLE
No completions for impl blocks on dyn traits with lifetimes

### ISSUE THREAD

**Issue by MaikKlein** [rust-analyzer/rust-analyzer#7683]
Follow up with #6777 because I noticed that it doesn't work in our internal project. After a quick investigation I noticed that lifetimes on impl blocks cause problems.

For example this code doesn't have any completions with the latest release

```rust
trait Foo {
    fn foo_dyn(&self, s: &str);
}

impl dyn Foo + '_ {
    pub fn foo<T: AsRef<str>>(&self, s: T) {
        self.foo_dyn(s.as_ref())
    }
}

impl Foo for u32 {
    fn foo_dyn(&self, s: &str) {
        println!("{} {}", self, s);
    }
}

fn completion(f: &dyn Foo) {
    // No completion
    f.foo("Hello");
}

fn main() {}
```
No completions if the impl block has a lifetime like this

```rust
impl dyn Foo + '_ {
impl<'a> dyn Foo + 'a {
impl dyn Foo + 'static {
```

**Comment by Veykril** [comment]
Okay I think I found the problem, in https://github.com/rust-analyzer/rust-analyzer/blob/ba3a5c518a4e20ddacad05d7a8a67704ca2b2a9a/crates/hir_ty/src/lower.rs#L708-L709 the `TraitRef::from_type_bound` call returns `None` when we check the lifetime bound as we haven't implemented lifetime generic predicates. Due to that the `None` gets mapped to a `GenericPredicate::Error` which then bubbles up to the method resolution stuff which then causes the impl to not match roughly speaking.

**Comment by MaikKlein** [comment]
Thanks a lot for looking into these issues <3

**Comment by Veykril** [comment]
I hope it will work for you this time 😄

**Comment by MaikKlein** [comment]
> I hope it will work for you this time

I can confirm that it works on nightly :)
