### ISSUE TITLE
"Apply De Morgan's law" assist does not account for precedence correctly

### ISSUE THREAD

**Issue by jDomantas** [rust-analyzer/rust-analyzer#7694]
```rust
fn bad_de_morgan() {
    if a < b && c {
        
    }
}
```

Cursor on `&&`, select "Apply De Morgan's law", and you get:

```rust
fn bad_de_morgan() {
    if !(!a < b || !c) {
        
    }
}
```

It's missing parentheses around `a < b`.

**Comment by Veykril** [comment]
I think we are merely missing the corresponding arms for `<`, `<=`, `>` and `>=` here https://github.com/rust-analyzer/rust-analyzer/blob/00d5a9563af9c84cdea9d029a9583be0513cc459/crates/assists/src/utils.rs#L217-L225

**Comment by jDomantas** [comment]
Why not parenthesize all binary expressions? All of them have smaller precedence than unary `!`. The user code needs to be a bit contrived for them to be valid bools (`true as bool` is legal, math operators can return bools), but even in presence of type errors I'd expect it either to work purely on grammatical assumptions, or not do anything at all. Sticking the `!` *wherever* is just plain wrong.

**Comment by Veykril** [comment]
That's a good point actually, I agree with you wrapping all binary expressions in `!()` instead of just a few seems good to me. Though we probably still want to special case the aforementioned 4 to be inverted directly.

**Comment by lbrande** [comment]
Can I work on this?

**Comment by Veykril** [comment]
Go ahead!

**Comment by lbrande** [comment]
Currently the docs for apply_demorgan claims "both operands being a negation of some kind" which is not the case with:
```rust
fn bad_de_morgan() {
    if a < b && c {
        
    }
}
```
I will thus remove that sentence from the docs, since this will work after the fix.

**Comment by lbrande** [comment]
After spending quite some time trying to figure out how to get the `TraitId` of `Ord` so that I can call `method_resolution::implements_trait` I've realized I probably won't figure it out on my own. If someone could give me a pointer, it would be greatly appreciated.

**Comment by Veykril** [comment]
You want to add a getter for `core::cmp::Ord` to `FamousDefs`, similar to this https://github.com/rust-analyzer/rust-analyzer/blob/14de9e54a6d9ef070399b34a11634294a8cc3ca5/crates/ide_db/src/helpers.rs#L56-L58. Add a copy of the trait definition(s) here https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_db/src/helpers/famous_defs_fixture.rs (so that this also works for tests) and then you can use a `FamousDefs` instance to access the trait id through the getter.
For seeing a bit more of how `FamousDefs` can be used, as well as how to get an instance of it, you can take a look at the inlay hints code for special casing iterator things https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/inlay_hints.rs#L226
