### ISSUE TITLE
Hide `doc(hidden)` items from auto suggestions

### ISSUE THREAD

**Issue by EFanZh** [rust-analyzer/rust-analyzer#7718]
For example, rust-analyzer suggests using `futures::FutureExt`, which is not publicly documented: <https://docs.rs/futures/0.3.12/futures/?search=FutureExt>.

**Comment by jhpratt** [comment]
This could probably be lumped in with #824.

**Comment by jonas-schievink** [comment]
`futures::FutureExt` is publicly documented and not marked `#[doc(hidden)]`, so it should appear in completions. However it does look like flyimport suggestions ignore `#[doc(hidden)]`, even after https://github.com/rust-analyzer/rust-analyzer/pull/9715.

**Comment by EFanZh** [comment]
@jonas-schievink The source code says `futures::FutureExt` is marked `#[doc(hidden)]`: <https://docs.rs/futures/0.3.16/src/futures/lib.rs.html#107-108>.

**Comment by lnicola** [comment]
The re-export is hidden, not the trait.

**Comment by flodiebold** [comment]
Soo if the reexport is hidden, does that mean we don't want to import `futures::FutureExt` and should use `futures::future::FutureExt`? :thinking:

**Comment by lnicola** [comment]
That's what I would expect.

**Comment by flodiebold** [comment]
What's the intention of these reexports then?

**Comment by flodiebold** [comment]
[This example](https://github.com/rust-lang/futures-rs/blob/master/examples/imperative/src/main.rs) imports `futures::StreamExt`, for example.

**Comment by Veykril** [comment]
That's blocked on recording imports in the hir then. cc https://github.com/rust-analyzer/rust-analyzer/issues/9197

**Comment by lnicola** [comment]
TBH, I think the intention was to use the re-export (otherwise why would it be there, and it's a common pattern to export shorter paths). But on the other hand, it makes sense for the documentation to sit next to the implementation, so I'm not sure what would be best here.

**Comment by flodiebold** [comment]
Yeah, I think my point is that it seems the situation with `doc(hidden)` isn't quite as clear as it seemed. Some reexports are `doc(hidden)` because they're not supposed to be used, but these ones are. Although, if they're supposed to be used, probably they'd ideally also be documented, just maybe in a different way? Maybe it's a missing rustdoc feature :thinking:

**Comment by lnicola** [comment]
Yeah, I feel the same way. Maybe there should be another attribute saying "use this other path instead of this one".

CC @jyn514 maybe.

**Comment by jyn514** [comment]
> Yeah, I think my point is that it seems the situation with doc(hidden) isn't quite as clear as it seemed. Some reexports are doc(hidden) because they're not supposed to be used, but these ones are. Although, if they're supposed to be used, probably they'd ideally also be documented, just maybe in a different way? Maybe it's a missing rustdoc feature thinking

This seems like a bug in the crate? Why would you annotate the item with `doc(hidden)` if you don't intend for it to be used? IMO the proper fix here is to remove `doc(hidden)` from `futures::Future` and add `doc(no_inline)` instead (which should be the default anyway).

**Comment by seanmonstar** [comment]
As another example, warp re-exports a lot of it's filters at the root, to allow for convenient usage (`warp::post()`, `warp::header()`, `warp::cors()`, etc). However, I manipulate the docs by making all of those doc(hidden), since I don't want the main doc page to have a huge lost of functions. Instead, the docs are structures to take a user to a filters or replies, and even then, filters are subdivided by types.

All the examples in warp show using the shorter import. I don't see that as a bug in warp, but as a way to direct the way a user finds the docs, in an attempt to not overwhelm them.

**Comment by jyn514** [comment]
@seanmonstar I have the same question though: why not use doc(no_inline)? That still shows the imports are available without adding all their docs to the main page. Currently it sounds like the docs for hyper aren't consistent with the examples.

**Comment by seanmonstar** [comment]
> I don't want the main doc page to have a huge list of functions.

This is why.
