### ISSUE TITLE
Include! macro behaviors differently between rust-analyzer and standard library

### ISSUE THREAD

**Issue by YuJuncen** [rust-analyzer/rust-analyzer#7846]
Hello! Recently, I found that seems there are some undocumented magic in the `include!` macro.

With this directory structure:
```
├── Cargo.toml
├── magic
│   ├── lib.rs
│   └── magic.rs
├── src
│   └── main.rs
```

... and those files:
```rust
// magic/lib.rs
pub mod magic;
```

```rust
// magic/magic.rs
pub fn hello() {
    println!("hello, world!")
}
```

```rust
// main.rs
include!("../magic/lib.rs");

fn main() {
    magic::hello();
}
```

Maybe a little strange, these compiles:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/36239017/109619355-a71bbb00-7b73-11eb-8b30-0de1249fc813.png">

... and `rustc` told us, those macro was expanded to:

```
#![feature(prelude_import)]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std;

pub mod magic {
    pub fn hello() {
        {
            ::std::io::_print(::core::fmt::Arguments::new_v1(&["hello, world!\n"],
                                                             &match () {
                                                                  () => [],
                                                              }));
        }
    }
}
fn main() { magic::hello(); }
```

... but `rust-analyzer` gave another version of the `include!` macro expansion, with an error `unresolved module`:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/36239017/109620009-5e183680-7b74-11eb-9484-28f55cef0869.png">

RA version:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/36239017/109621430-ecd98300-7b75-11eb-9ab3-886f86d3a415.png">

**Comment by jonas-schievink** [comment]
I think the missing piece here is that we don't treat the included file as the anchor for module file resolution.

**Comment by patrickelectric** [comment]
Is there someone working on that ? Or any light/tip about how and where this should be fixed ?

**Comment by edwin0cheng** [comment]
> Or any light/tip about how and where this should be fixed ?

I think the fix will be something like these:

Note that inside `include_expand` :

https://github.com/rust-analyzer/rust-analyzer/blob/d54e1157b66017e4aae38328cd213286e39ca130/crates/hir_expand/src/builtin_macro.rs#L346-L359

We already have the actual file id of that included file, we have to return it and store it in `EagerCallLoc` (maybe add a `included_file : Option<FileId>` field.

https://github.com/rust-analyzer/rust-analyzer/blob/d54e1157b66017e4aae38328cd213286e39ca130/crates/hir_expand/src/lib.rs#L301-L307

Another step is we should change `resolve_declaration` (which is called when resolving `mod foo;`) :

https://github.com/rust-analyzer/rust-analyzer/blob/d54e1157b66017e4aae38328cd213286e39ca130/crates/hir_def/src/nameres/mod_resolution.rs#L59-L68

Instead of using `file_id.original_file` , we should add a new function to get that `included_file` in eager macro case. (maybe add a new method in HirFileId)

And finally add a test in https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/hir_def/src/nameres/tests/macros.rs
