### ISSUE TITLE
Some structs from std::sync not appear in autocomplete

### ISSUE THREAD

**Issue by asv1** [rust-analyzer/rust-analyzer#7902]
Just try input Arc or Once. In autocomplete list it must appear under std::sync, but nothing here from that module.

**Comment by bjorn3** [comment]
Could `extern crate alloc as alloc_crate;` in `std/lib.rs` be handled incorrectly?

**Comment by asv1** [comment]
@bjorn3 
Maybe. But Mutex is imported correctly. Condvar too.

**Comment by bjorn3** [comment]
`Arc` and `Once` are defined in liballoc and re-exported in libstd. `Mutex` and `Condvar` are defined in libstd.

**Comment by jonas-schievink** [comment]
`std::sync::$0` does complete `Arc` and `Once`, but typing them without the path doesn't

**Comment by SomeoneToIgnore** [comment]
I think the reexport is the culprit indeed, my guess is that we're either ignoring them when populating `ImportMap` or somehow do not consider the reexported path afterwards, when doing the search.

The path prepending "fixing" the problem is explained by the fact that we use different logic to complete in this case (not from the `flyimport.rs` module, but from the `qualified_path.rs` one)

**Comment by SomeoneToIgnore** [comment]
I've debugged it using the  current `master` branch and looks like the issue is not with the item lookup, but with the search limits and the way we store the associated items.

If you bump the 
https://github.com/rust-analyzer/rust-analyzer/blob/342bf41022fa78856a48560b521ea32aa76f6f06/crates/ide_db/src/imports_locator.rs#L18

constant to, say, 100, `Arc` starts to pop-up in the results.
(we cannot remove the limit entirely or keep it very high, because it reduces the imports lookup speed)

Interesting to note, that on a zero-dependency project and bumped constants, I get 19 results in total:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/2690773/110253010-bdb97c00-7f90-11eb-8806-b032165f89e5.png">

So, even the default limit should suffice, but it does not.

The code that triggers the search is here: https://github.com/rust-analyzer/rust-analyzer/blob/09c11054a1b4886fdfd8f0bbb119aae0f264af1a/crates/ide_db/src/helpers/import_assets.rs#L183-L195

and the code that does the actual search, taking the `limit` into account is here: https://github.com/rust-analyzer/rust-analyzer/blob/af4e75533f2c071330e740e2fa94b131e3a2b538/crates/hir_def/src/import_map.rs

Right now, we exclude associated items from the fuzzy search (`(AssocItemSearch::Exclude, Some(DEFAULT_QUERY_SEARCH_LIMIT))`), but I'll include them in https://github.com/rust-analyzer/rust-analyzer/pull/7873 and `100` won't work anymore, you'll need `200` for that for a zero-dependency project and presumably way more for "real" projects.

So we cannot just bump the limit and hope for the best, we need to search for the dependencies in a more clever fashion somehow, maybe split the associated items from the rest of the items and search those separately?

**Comment by SomeoneToIgnore** [comment]
@asv1 , could you recheck the situation after https://github.com/rust-analyzer/rust-analyzer/pull/8131 lands?
That adds case-aware lookup into the completions, can help in your workflow.

**Comment by asv1** [comment]
@SomeoneToIgnore 
Looks like ok now.
