### ISSUE TITLE
Implement textDocument/documentHighlight

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#80]
I'm trying to implement `textDocument/documentHighlight` but am not sure how to find all references to a symbol. I was thinking of either using `world_symbols` and filtering on the file id or looping through  `world.analysis().file_structure(file_id)` and just returning all nodes that match the text in the params.

**Comment by matklad** [comment]
I think we can do this for local variables and function parameters, though it needs some work. 


FnScopes struct is responsible for creating a scoping structure inside a function:

https://github.com/matklad/rust-analyzer/blob/c2ab6ad73d2a7cd9a54dd8ee9f96dab25ec89600/crates/ra_editor/src/scope/fn_scope.rs

We currently only use scopes for completion, but we absolutely should use them for name resolution as well. 

The overall structure should be like this, I think:

* a function to get function's scope
* a function to resolve a local NameRef using scopes

On top of that, layer "approximately resolve" which tries to use local scope first, and falls back to an index-based implementation.

**Comment by kjeremy** [comment]
I have a few questions and am still getting used to the organization.

> We currently only use scopes for completion, but we absolutely should use them for name resolution as well.
> 
> The overall structure should be like this, I think:
> 
> * a function to get function's scope

Is a function's scope the module or possibly file's scope (ie what contains the function or is the scope the entire function)?

> * a function to resolve a local NameRef using scopes
> 
> On top of that, layer "approximately resolve" which tries to use local scope first, and falls back to an index-based implementation.

How is this different then the existing `approximately_resolve_symbol`? Would this new function be something like `approximately_resolve_namerefs` ?

Can you be a little more explicit about how I could fill in the details?

**Comment by matklad** [comment]
>Is a function's scope the module or possibly file's scope (ie what contains the function or is the scope the entire function)?

Let me be more specific: [`FnScopes`](https://github.com/matklad/rust-analyzer/blob/c2ab6ad73d2a7cd9a54dd8ee9f96dab25ec89600/crates/ra_editor/src/scope/fn_scope.rs#L15-L19) datastructure represents a tree of scopes for a function. Each scope is a set of bound names + a pointer to the parent scope. 

For example, for 

```
fn foo(x: i32, y: u32) {
    {
        let z = x * 2;
    }
    {
        let t = x * 3;
    }
}
```

It will contain three scopes: a scope with `x` and `y`, a scope with `z` (whose parent is the first scope) and a scope with `t` (whose parent is the first scope as well).

`FnScopes` currently does not deal with items.

**Comment by matklad** [comment]
>How is this different then the existing approximately_resolve_symbol? Would this new function be something like approximately_resolve_local_name(&self, file_id: FileId, range: TextRange) -> Vec<TextRange> ?


The important distinction to make here is between "IDE API" functions, which operate on `TextRange`s and in general can return approximate results, and "compiler internals" functions, which operate on syntax trees and must be precise. In this case, we should start with "compiler internals" bit, the new function would be precise, with a signature roughly `fn resolve_local_name(name_ref: NameRef, scopes: &FnScopes) -> Option<Name>`. It will be able to correctly(modulo bugs) resolve local names.

Then, we should surface this function to IDE to use. One way to do it is via `approximately_resolve_symbol`, so that go to definition correctly works for local variables. 


>Can you be a little more explicit about how I could fill in the details?

Sorry for being opaque here! I am myself not 100% sure what the shape of the code should be here, long term. To start though, I think we can add a function to `fn_scopes.rs` which resolves local name to definition. Then, we can use it inside `approximately_resolve_symbol` (that would be one chunk of work/PR). Then, we can add some additional surface API to analysis to implement document highlights. 

To get an idea about how `FnScopes` API works like, take a look at the `complete_fn` function.
