### ISSUE TITLE
Inside macros, methods don't show up in completion after a dot

### ISSUE THREAD

**Issue by xscd** [rust-analyzer/rust-analyzer#8158]
Methods do not show up inside macros. Needs some explicit letters else no methods are shown. 
![Peek 2021-03-22 20-28](https://user-images.githubusercontent.com/46658470/112047798-c304f200-8b5e-11eb-8e3e-10dea35dbf54.gif)

https://users.rust-lang.org/t/question-about-rust-analyzer-behaviour/57302

**Comment by Veykril** [comment]
The problem here is that just `println!("{}", a.)` can't be expanded as it doesn't match any of the macro matchers, therefor because the macro can't be expanded we cannot show completions as the `a.` is just tokens.

**Comment by lnicola** [comment]
Can we use the same trick of inserting a bogus identifier after dot in a macro invocation?

**Comment by Veykril** [comment]
We are doing that in general when calculating completions but the problem is that we fetch the relevant ast nodes from the original file here it seems, which in this case then don't exist. I'm not sure if we can fix this.

**Comment by flodiebold** [comment]
We do the trick and expand the macro with that input as well. The problem is that we can't resolve anything within the 'hypothetical' expansion, so to do further recursive expansion, we have to have a similar expansion in the original case (without the fake identifier) so we can check the resolution there. To fix this, we'd need to have some way of doing more deep analysis of those hypothetical ASTs.

**Comment by jonas-schievink** [comment]
Looks like this specific case still doesn't work right, even after #10162 

```rust
fn main() {
    let x = 0i32;
    println!("{}", x.$0)
}
```
