### ISSUE TITLE
Show Syntax selection

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#820]
It would be really cool if we could highlight rust syntax in the editor and have the "Show Syntax" window follow our selection.

Definitely a wish list item.

**Comment by matklad** [comment]
Yup. This is mostly VS Code thing though,

**Comment by vipentti** [comment]
I think an addition / a simpler alternative to this would be to add an option to "Show syntax for selection" command, which would basically take the selected range and dump the syntax similarly to the "Show syntax for file" action. 

I find myself often running `println!("{}", syntax().debug_dump())` while writing some new features/fixes and writing tests for them, to understand how the syntax looks. I think "Show syntax for selection" could allow me to show the syntax for a small subset of the code I'm working on. It would be even nicer if you could highlight the test input string, and dump the syntax of what the string contains as rust syntax, using this method as well.
e.g.

```rust
<|>fn foo() {}<|>
```

and
```rust
r#"
<|>fn foo() {}<|>
"#
```
would both produce similar syntax tree. I think the difference between this and "Show syntax for file" would be that the "Show syntax for selection" would not automatically change when you change selection. This would allow you to select a range, show its syntax and start editing while seeing how the syntax looks.

**Comment by matklad** [comment]
@vipentti excellent idea! I know understand that I've been wanting this feature since forever!

I think we can use a single `Show Syntax Tree` command for both cases: on the VS Code side, one can check if there's an active selection in the editor. If there's a selection, we show a (snapshot) of a tree for selection. Without selection, we maintain the current behavior with live-updating tree.

To implement this, I think we need to add an `Option<Range>` param to `ShowSyntaxTreeRequest` in `req.rs`, plumb it through `handlers.rs` to the `Analysis` struct in `ra_ide_api_ligt` and there use a combination of `find_covering_node` and `debug_dump`.

**Comment by vipentti** [comment]
I'll try this

**Comment by vipentti** [comment]
Implementation in #924
