### ISSUE TITLE
"MISSING: command" at top level of crate

### ISSUE THREAD

**Issue by pikajude** [rust-analyzer/rust-analyzer#8218]
![image](https://user-images.githubusercontent.com/316117/112734170-55134e80-8f01-11eb-9e52-9e175f28c180.png)

I don't really know what this means. The item is also clickable, but all it does is create a notification in the bottom right of my screen that says: `command 'missing' not found` which doesn't explain very much.

On the plus side, it does not seem to be interfering with rust-analyzer's diagnostics in any way.

**Comment by Veykril** [comment]
This has been fixed and should disappear next stable release. https://github.com/rust-analyzer/rust-analyzer/pull/8183

Regarding what this is, this appears when annotations can't be resolved(the `135 implementations` thing that appears above structs and the like), this resolving failure happens when macros create items currently which then appears at the top of the file as the text ranges are mapped incorrectly.

**Comment by dbsxdbsx** [comment]
@Veykril, with the latest rust analyzer(ra afterwards), I find  a bug:
In my module, I defined struct named `AgentPG` in file `agentPG`, and it is declared in the same folder of file `mod.rs` with``pub mod agentPG;  But still , ra mentioned `"MISSING: command" `  in file `agentPG`, and when I click the yellow light button on the right side,  it asked whether to add `mod AgentPg` or `pub mod AgentPg`., finally, the `mod.rs` file could be like this：
```
pub mod agentPG;//what I add
mod AgentPg;// what added automatically，
```
As you can see ,the auto generated struct name is incorrect.

**Comment by Veykril** [comment]
This seems unrelated to this PR(the missing command stuff seems to be a side effect).
Can you open a new issue aboue this with more information on the project structure?

**Comment by dbsxdbsx** [comment]
@Veykril, thanks for reply.  I mentioned it here：https://github.com/rust-analyzer/rust-analyzer/issues/9707
