### ISSUE TITLE
"remove dbg!" assist keeps unneeded parentheses

### ISSUE THREAD

**Issue by jDomantas** [rust-analyzer/rust-analyzer#8455]
```rust
fn repro(a: bool, b: bool) {
    dbg!(!a) && b;
    dbg!(a) && b;
}
```

`Remove dbg!` assist removes the parentheses in the second case, but not the first one:

```rust
fn repro(a: bool, b: bool) {
    (!a) && b;
    a && b;
}
```

**Comment by SomeoneToIgnore** [comment]
The code, determining whether to remove or retain the parentheses is here: 

https://github.com/rust-analyzer/rust-analyzer/blob/343b14f7e06f3ec82a15b3648ba229e03e0b0583/crates/ide_assists/src/handlers/remove_dbg.rs#L148-L193

This particular issue most probably is caused by `is_punct` in
https://github.com/rust-analyzer/rust-analyzer/blob/343b14f7e06f3ec82a15b3648ba229e03e0b0583/crates/ide_assists/src/handlers/remove_dbg.rs#L185

We need to find a better heuristics (preferably) or add another symbol as an exception in the check.

**Comment by jDomantas** [comment]
Isn't it viable to do this properly? I would imagine you could see what expression was the contents of the macro call parsed as, and then what expression is the call itself contained in. Determining if the parentheses should be added is not possible from contents alone, `dbg!(!a) && b` does not need them, but `dbg!(!a).field` does.

**Comment by flodiebold** [comment]
It would be nice if we could just construct the intended AST and have a general function that inserts parentheses if necessary.
