### ISSUE TITLE
auto-import and importing completions should add the `use` statement after any header comments

### ISSUE THREAD

**Issue by wtfsck** [rust-analyzer/rust-analyzer#8607]
Repro:

- Move to `HashSet` and press `Ctrl+.` in VSCode and import it

```rust
// Some license header

fn main() {
    let hset: Option<HashSet<usize>> = None;
}
```

Result:

```rust
use std::collections::HashSet;

// Some license header

fn main() {
    let hset: Option<HashSet<usize>> = None;
}
```

Expected result:

```rust
// Some license header

use std::collections::HashSet;

fn main() {
    let hset: Option<HashSet<usize>> = None;
}
```

**Comment by SomeoneToIgnore** [comment]
I see `S-actionable` label, but not sure I fully understand how to determine that a comment is an "any header comment" or a "license header".

The code, responsible for locating the place to insert the use statement is here:
https://github.com/rust-analyzer/rust-analyzer/blob/1ef55002c2db4ca68df31306290b019c7fbfb4fb/crates/ide_db/src/helpers/insert_use.rs#L45

The tests are [here](https://github.com/rust-analyzer/rust-analyzer/blob/1ef55002c2db4ca68df31306290b019c7fbfb4fb/crates/ide_db/src/helpers/insert_use/tests.rs).

So far, when searching for an insertion place, we've operated only simple semantic concept like "is it a module?" or "is it a source file?", as show in:

https://github.com/rust-analyzer/rust-analyzer/blob/1ef55002c2db4ca68df31306290b019c7fbfb4fb/crates/ide_db/src/helpers/insert_use.rs#L34-L42

In the same method, we can search for comments and get their textual representation, analyzing the text, so one who has a heuristics in mind, can try that.

**Comment by ivan770** [comment]
How are license headers different from any other comments?

**Comment by Veykril** [comment]
We special case inner doc comments and attributes here https://github.com/rust-analyzer/rust-analyzer/blob/1ef55002c2db4ca68df31306290b019c7fbfb4fb/crates/ide_db/src/helpers/insert_use.rs#L77-L90 so that we place the import under those instead before those. We could instead change this to inner doc comments, non doc comments and inner attributes(note that we dont want to do this for outer doc comments). This would unfortunately cause:
```rust
// this function does something
fn foo() {...}
```
to become
```rust
// this function does something
use some::import;

fn foo() {...}
```

I think this should be fine though as using license headers is more common than using a non-doc comment like that?

As Kirill said we can of course try to use some heuristic to figure out whether comments is a license as well which would probably be nicer.

**Comment by jonas-schievink** [comment]
> I think this should be fine though as using license headers is more common than using a non-doc comment like that?

I don't think it is, people often use non-doc comments to document internal functions.

**Comment by jonas-schievink** [comment]
Ah, but comments placed right before an item get put inside the item's syntax node, so this shouldn't be a problem. Just make sure to write a test.
