### ISSUE TITLE
Auto-import doesn't work near macro invocation

### ISSUE THREAD

**Issue by branpk** [rust-analyzer/rust-analyzer#8648]
When a macro is used inside a function, auto-import stops working within that function. Specifically, I believe it stops working in the same block or any sub-blocks:

This does not work:
```rust
fn main() {
  println!();
  HashM<cursor>
}
```

However this works:
```rust
fn main() {
    {
        println!();
    }
    HashM<cursor>
}
```

I'm guessing this is because the macro could theoretically spit out `use` statements. But given that this is probably uncommon, maybe it would be better to simply assume it doesn't? Maybe just for common macros like `println`, `todo`, etc?

Note that autocompletion (without importing) doesn't seem to have this problem:

```rust
fn func() {}

fn main() {
    println!();
    fun<cursor>
}
```

I personally run into this issue on a regular basis since I use `todo` a lot.

rust-analyzer version: 2021-04-19-1-gd906b7ad8

**Comment by SomeoneToIgnore** [comment]
That was supposed to be fixed in https://github.com/rust-analyzer/rust-analyzer/pull/8587

and works for me on the current nightly: 
<img width="381" alt="Screenshot 2021-04-24 at 20 36 59" src="https://user-images.githubusercontent.com/2690773/115967734-e3004a80-a53c-11eb-9aca-a78f14f951f6.png">

you version is supposed to include the fix, if I'm not mistaken, but could you please double-check on nightly?
Iin VSCode it's possible by setting the `"rust-analyzer.updates.channel": "nightly"` setting in your settings.json

**Comment by flodiebold** [comment]
The stable release doesn't contain the fix yet.

**Comment by branpk** [comment]
Yep it's fixed on nightly - forgot to search closed issues. Thanks!
