### ISSUE TITLE
Support analyzing linked libraries

### ISSUE THREAD

**Issue by chinedufn** [rust-analyzer/rust-analyzer#8669]
## The Scenario

Suppose I have a crate `foo-crate`.

```toml
# foo-crate's cargo.toml

[package]
name = "foo-crate"
```

```rust
# foo-crate's lib.rs

/// Adds `a` and `b`.
#[no_mangle]
pub fn add (a: u8, b: u32) -> i64 {
    a as i64 + b as i64
}
```

Now say I have a second crate, `bar-crate`, that statically links to the `foo-crate` described above.

```rust
// bar-crate's lib.rs

use foo_crate::add;

fn bar () {
    println!("{}", add(1, 2));
}
```

When typing out the `add` function in `bar-crate`'s lib.rs, you will not get any auto
complete. You also won't be able to see the `add` method's documentation.

This is normal and expected at this time. 

I'm going to propose why it could be nice to be able to somehow support this in the future.

## The Problem

_Imaginary story_

Suppose you are developing a novel image editor. 

You might build the editor as a binary to distribute to your customers.

Technically your customers could get source code by de-compiling your binary, but in practice it would be so unreadable and unmaintainable that this isn't a legitimate threat to your business.

Your image editor repository is a Cargo workspace with a bunch of different library crates, many of which are independently useful.

"Ah-ha", you think to yourself. "Why don't I distribute a library version of my image editor as well. This way people can do nifty things like easily embed it in their `winit` application, or make use of some of my cool novel futuristic enironmentally-friendly image editing algorithms."

So you build a `rlib`, and upload it along with the rustdocs (stripped of the source code since you want to keep it closed source).

Unfortunately, whenever someone is using your cool library, they get next to zero IDE support since the IDE knows nothing about your linked library.

So, the user is bouncing back in forth between their IDE and your online documentation, making typos left and right and generally having a poor experience.

## A Potential Solution

_I don't know enough about rust-analyzer to propose a detailed approach, so I'm first trying to put out a feeler to see if this is even possible or desirable to solve in the first place._

I think one solution might look like:

- rust-analyzer knows where statically/dynamically linked libraries live. Perhaps it picks that up from looking at what your build script writes to `stdout` or looking at Cargo metadata or something. I haven't thought deeply into this piece - right now I'm just looking to get a sense of if "solving" this is possible or desirable before researching it further.

- I'm assuming that rust-analyzer has some internal format that it uses to analyze a crate. If os, then it could be possible for someone to use the relevant parts of rust-analyzer in order to create a representation of their crate that they can then serialize to disk. If rust-analyzer sees this representation next to a linked library on disk it can use it to provide auto complete, documentation previews, etc.

## Main Value Proposition

Supporting this would help people that are using Rust to build closed source libraries deliver much better user experiences, especially for very complicated libraries where autocomplete and inline documentation are even more valuable.

## Caveats

- This mainly caters to people who are building closed source libraries that they plan to distribute outside of their Cargo workspace, which could be a small enough minority of people that this is a low priority feature.

- As mentioned, I have no idea how possible or desirable any of this is. Hopefully someone else can give feedback on that.

**Comment by bjorn3** [comment]
> Technically your customers could get source code by de-compiling your binary, but in practice it would be so unreadable and unmaintainable that this isn't a legitimate threat to your business.

Rust rlibs contain a lot of information that makes it a lot easier to decompile them than C libraries and executables. This includes source information (filename, line, column) for all definitions as well as for all generic, `#[inline]` and `const` functions the MIR which contains source information for each statement and terminator. It also contains the full definition and layout of every type and function signature of each function even when they are private.

https://github.com/rust-lang/rust/blob/8212de8eb18a8cc4ab74074f244c386d5e99b281/compiler/rustc_metadata/src/rmeta/mod.rs#L283-L317

> So you build a rlib, and upload it along with the rustdocs (stripped of the source code since you want to keep it closed source).

Rlibs are only compatible with a single rustc version. Any other version will reject it even when the actual metadata format hasn't changed. I doubt many customers are willing to get locked to a single rustc version when a new one releases every six weeks or when they may need to use a nightly compiler for whatever reason. This gets even worse when multiple libraries are used that are pre-compiled for different rustc versions.

If you want to keep the source private you are better of exposing a C api from your library and then writing an open source wrapper crate with all documentation and such. This wrapper could be made using for example the [abi_stable](https://crates.io/crates/abi_stable) crate.

Note that cargo already doesn't play nice with pre-compiled crates. It doesn't have any knowledge about it, so you need to use `RUSTFLAGS` to pass rustc the right flags to compile it and it becomes impossible for your user to depend on the same versions of crates as you due to conflicts. Rustc refuses to link multiple rlibs with identical name and version but different SVH (semantic version hash, depends on exact crate source, compilation options like optimization level and some other things) into the same artifact.

> rust-analyzer knows where statically/dynamically linked libraries live. Perhaps it picks that up from looking at what your build script writes to stdout or looking at Cargo metadata or something. I haven't thought deeply into this piece - right now I'm just looking to get a sense of if "solving" this is possible or desirable before researching it further.

Rust-analyzer completely ignores the actually compiled libraries. It only looks at source code. The only way compiled libraries play a role at all is when using proc-macros in which case rust-analyzer needs to dynamically link to the compiled proc-macros to run them on the source.

> I'm assuming that rust-analyzer has some internal format that it uses to analyze a crate. If os, then it could be possible for someone to use the relevant parts of rust-analyzer in order to create a representation of their crate that they can then serialize to disk. If rust-analyzer sees this representation next to a linked library on disk it can use it to provide auto complete, documentation previews, etc.

Even if rust-analyzer would get a way to dump and load the information on disk, this would:

1. Be in an unstable format to ensure that we can improve it.
2. Likely leak the full source code of the library and if it doesn't at least leak everything except for the function bodies.

**Comment by chinedufn** [comment]
> If you want to keep the source private you are better of exposing a C api from your library and then writing an open source wrapper crate with all documentation and such.

Ah, much simpler.

Thanks a lot for explaining all of that, I learned a few things from your answer.

Awesome, cheers.
