### ISSUE TITLE
rust-analyzer panics when trying to add import

### ISSUE THREAD

**Issue by Tiwalun** [rust-analyzer/rust-analyzer#8700]
When I try to add a missing import using the quick fix in VS Code, i.e. clicking on the light bulb and clicking `Import std::borrow`,
nothing happens.

The expected behaviour would be that the import is added at the top of the file.

When I look at the language server output, I can see that a panic occurred:

    thread '<unnamed>' panicked at 'can't resolve local ptr to SyntaxNode: SyntaxNodePtr { range: 3242..3515, kind: FN }', crates/syntax/src/ptr.rs:32:2

[Full Rust Analyzer output](https://gist.github.com/Tiwalun/2cc4b50199cc5044714a49ae8e0d73e7)

This happens with the nightly version: 80bee14e1 2021-04-30 nightly

**Comment by SomeoneToIgnore** [comment]
Could you share more details, some example/project where that is reproducible?

I'm trying to trigger the import on a sample project this way:
<img width="412" alt="Screenshot 2021-05-01 at 20 47 12" src="https://user-images.githubusercontent.com/2690773/116790706-71854680-aabe-11eb-9bb4-df0487dd95ec.png">

and it works for me, adding an import.

**Comment by Tiwalun** [comment]
It is reproducible with the following project: https://github.com/Tiwalun/probe-rs/tree/rust-analyzer-crash-repro-8700

The error happens on the following line:

https://github.com/Tiwalun/probe-rs/blob/17b3bc0bfa9539738d920ca99a5ff995f6204481/probe-rs/src/architecture/arm/core/m33.rs#L143

![image](https://user-images.githubusercontent.com/859555/116806181-a54a8580-ab2b-11eb-894e-7dde1f576525.png)

When I try to add the import, the file is unchanged, and the panic output can see in the Rust Analyzer output.


I will try to see if I can find a smaller example.

**Comment by SomeoneToIgnore** [comment]
Can reproduce it, thank you.
Minimized example:
```rust
pub trait CoreInterface {
    fn reset_and_halt(&mut self);
    fn step(&mut self);
}

pub struct M33;

impl CoreInterface for M33 {
    fn step(&mut self) {
        todo!()
    }

    fn reset_and_halt(&mut self) {
        String::from("dsds").borrow();
        todo!()
    }
}

fn main() {}
```

The actual culprit is not the import assist, but the `reorder_impl` one that's responsible for the "Sort methods" menu item on the screenshot, full trace show that:

```
thread '<unnamed>' panicked at 'can't resolve local ptr to SyntaxNode: SyntaxNodePtr { range: 185..276, kind: FN }', crates/syntax/src/ptr.rs:32:28
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: syntax::ptr::SyntaxNodePtr::to_node::{{closure}}
   3: syntax::ptr::SyntaxNodePtr::to_node
   4: ide_assists::assist_context::AssistBuilder::make_mut
   5: ide_assists::assist_context::Assists::add
   6: ide_assists::handlers::reorder_impl::reorder_impl
   7: ide_assists::Assist::get
   8: ide::Analysis::assists_with_fixes::{{closure}}
   9: std::panicking::try
  10: ide::Analysis::assists_with_fixes
  11: rust_analyzer::handlers::handle_code_action_resolve
  12: <F as threadpool::FnBox>::call_box
```

I see two issues here:
* rather weird, that we resolve other assists but the import one after *selecting* the import-related menu item: we need to apply the import assists and that's it
* the actual issue with the reorder_impl assist that's unable to find the syntax node pointer for some reason

Not sure what's happening in both issues, but the last one seems to be related to rowan, so CC @matklad just in case.

**Comment by Veykril** [comment]
Regarding point 2 the problem is that we mutate the ast while we are trying to traverse it, traversing happens with `make_ast_mut` call by mapping the nodes to their mutable countparts here: https://github.com/rust-analyzer/rust-analyzer/blob/e1bef531095f152649a7e20e992cf97ba6b3f990/crates/ide_assists/src/handlers/reorder_impl.rs#L82-L84
We need to collect all `make_ast_mut` call results first I believe before actually replacing the nodes.

**Comment by SomeoneToIgnore** [comment]
I've fixed the point 1 in https://github.com/rust-analyzer/rust-analyzer/pull/8711 and let the rest of the task to you @Veykril , since you're assigned :)

**Comment by Veykril** [comment]
2 is addressed with https://github.com/rust-analyzer/rust-analyzer/pull/8712
reorder_fields actually didn't have that problem
