### ISSUE TITLE
Go To Definition on definition site should succeed

### ISSUE THREAD

**Issue by djrenren** [rust-analyzer/rust-analyzer#877]
Currently if you invoke go to definition at an identifiers declaration site, no results are returned. Like so:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/634666/53211990-1ad77480-35f8-11e9-86f5-78ca50e74572.png">

I would inspect instead that it would navigate me to the beginning of the identifier of the declaration here:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/634666/53212039-3a6e9d00-35f8-11e9-828a-453564b9bf01.png">

(note that go to def at usage sites is working, just not at this location)

**Comment by matklad** [comment]
I kinda like the behavior of IntelliJ in this case: goto defiinition on the definition itself triggers "find references". But we probably just need to do what LSP and other LSP-using languages do.

**Comment by matklad** [comment]
I kinda like the behavior of IntelliJ in this case: goto defiinition on the definition itself triggers "find references". But we probably just need to do what LSP and other LSP-using languages do. We certantly can improve `goto_defenition` signature:

https://github.com/rust-analyzer/rust-analyzer/blob/bb665a70627cbc2f4fb930fefb04899941b6afa6/crates/ra_ide_api/src/lib.rs#L307-L312


Ideally, it should contain something like this:

```rust
struct DefenitionSearchResult {
   is_already_definition: bool,
   definitions: Vec<NavigationTarget>,
}
```

**Comment by djrenren** [comment]
I don't think it's a a structural issue... It just seems that `goto_definition` should return a location in this instance but isn't doing so.

**Comment by kjeremy** [comment]
What do other language servers do in this case?

**Comment by matklad** [comment]
It is a bit of a structural issue: the *library* should return more information about go to definition request. I think adding a `reference: TextRange` might be useful as well actually. 

The LSP server, which is a client of the library, could than use this additional info to implement custom logic for "what happens if goto def is executed on the def?". 

In general, I try to think in terms of the library interface and not in terms of the protocol :)

**Comment by djrenren** [comment]
@kjeremy: the typescript one successfully takes you to the beginning of the identifier.

@matklad: I understand the reasoning for keeping the two concepts separate, but I guess I don't understand why you *wouldn't* successfully produce the definition location in this case. If for some reason a caller wants to know if  `position` was contained within the result, this seems pretty easily doable by the caller.

**Comment by vipentti** [comment]
I think the problem is that `name_definition` https://github.com/rust-analyzer/rust-analyzer/blob/74ecfc2729d2d0771304a4fed3afdfa2c2d99b43/crates/ra_ide_api/src/goto_definition.rs#L112-L128

Doesn't properly handle when the cursor is over a name of a struct/enum etc. I could try to fix this and attempt to refactor the return value as well.

**Comment by djrenren** [comment]
:heart: Thanks all!
