### ISSUE TITLE
Indexing is too slow comparing to Clion

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#8810]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/33961674/117902838-ee0af700-b300-11eb-8a3d-ca32191b6c5e.png">

after upgrading to latest rust-analyzer, the indexing becomes extremly slow. I have been waiting for more than 10mins on my macbook pro m1

The test code: https://github.com/parallel-finance/parallel

**Comment by GopherJ** [comment]
I'm using RA@2021-05-10 and latest coc.nvim & latest coc-rust-analyzer

**Comment by GopherJ** [comment]
This is maybe a pb of substrate(https://github.com/paritytech/substrate), is there a way to make things faster? as if it's too slow, it basically means that we cannot use code substrate projects using RA

**Comment by GopherJ** [comment]
It's maybe related to https://github.com/paritytech/polkadot/issues/2919

**Comment by GopherJ** [comment]
yesterday's test:

> indexing is too slow and no cache persisted, currently if I open https://github.com/parallel-finance/parallel/blob/master/pallets/liquid-staking/src/lib.rs it took 3mins 1sec to finish indexing on a i9-10900k, 32GB PC

![image](https://user-images.githubusercontent.com/33961674/128891628-bdd205d5-3d86-46fa-8e4f-27fcd4d672cb.png)

**Comment by Veykril** [comment]
We minimzed what we prime in projects a bunch recently, can you check if things have gotten better here?

**Comment by lnicola** [comment]
We seem to spend about 20-30 seconds loading this project, which seems reasonable given the huge amount of code involved. The initial load is slower because a `check` build takes about 5 minutes.

**Comment by mathiaspeters** [comment]
I've also noticed in recent versions that indexing is slow, for me specifically with async-std. All other crates index in a second or two but async-std takes well over a minute

**Comment by lnicola** [comment]
@mathiaspeters are you using `async-std 1.11.0`?

**Comment by mathiaspeters** [comment]
`async-std 1.10.0`

**Comment by lnicola** [comment]
Try updating. They made some huge improvements in compile time in the latest version. `async-std 1.10` is specifically tracked on our side in https://github.com/rust-analyzer/rust-analyzer/issues/11363.

Besides that, you can now also use `"rust-analyzer.cache.warmup": false` to disable that "indexing" step, or you can disable build scripts, proc macros and/or check on save. Since we seem to be faster these days at loading that project, we don't know what or if is still slow, and there are some workarounds, I think we can close this for now.
