### ISSUE TITLE
Lints and feature gates should have hover hints

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-analyzer/rust-analyzer#8857]
Currently, lints display information about what they lint against while typing them:
<img src="https://user-images.githubusercontent.com/8634700/118406684-76133880-b642-11eb-85d7-e3eebf0365f1.png" alt="Typing `#!forbid[(unsafe_o)]` suggests several lints. `unsafe_op_in_unsafe fn` is highlighted, which causes documentation for the lint to appear next to it." width=600>

Features gates behave similarly, though their documentation just has the feature name written as a Markdown title (which seems like a bug). Additionally, hovering over a lint or a feature gate displays nothing:
<img src="https://user-images.githubusercontent.com/8634700/118406783-f9348e80-b642-11eb-9266-9e508080a5e9.png" alt="Screenshot showing a cursor hovering over `#![forbid(unsafe_op_in_unsafe_fn)]`. No hover hint is displayed." width=600>

I believe that adding the lint/feature gate documentation as a hover hint would be useful, as it would allow people to quickly understand what the lint/feature gate does without having to pull up a reference.

**Comment by Veykril** [comment]
Features not showing their description is certainly a bug, looks like the generated description strings of those is different than those of lints. <https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_completion/src/generated_lint_completions.rs>

Hovering is something I'd like for attributes to definitely work for, the current problem is that attributes merely contain unstructured tokens. In this case we can easily parse the attribute for the given structure and make it work though, so that shouldn't be a problem. I'll give that a look.
