### ISSUE TITLE
Trait in a trait impl not automatically considered in-scope

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#8912]
![screenshot-2021-05-21-19:03:48](https://user-images.githubusercontent.com/1786438/119173285-5a0aff00-ba67-11eb-8752-6595243907ae.png)

Here, the method call to `fmt` is unresolved, but it should resolve to `<Subtree as Display>::fmt`. The implemented trait is normally considered to be in scope while in the impl block, maybe that logic is missing from rust-analyzer?

**Comment by Veykril** [comment]
I think the problem is that we discard impl scopes here https://github.com/rust-analyzer/rust-analyzer/blob/33fdd512e318f86ccd66b84ce6128c03eb44cf77/crates/hir_def/src/resolver.rs#L337-L359

The thing is all we have access to there is a `hir_def::TraitRef` but we want a `hir_def::TraitId`. The only way to go from one to the other is with help of `hir_ty` which we don't have access to since we are inside the `hir_def` crate.

**Comment by jonas-schievink** [comment]
`hir_def` should be able to do that step, it involves resolving the `TraitRef`'s path to a `ModuleDefId::Trait`, which gives you the `TraitId`

**Comment by Veykril** [comment]
Oh right, ye okay than this seems simple enough to do
