### ISSUE TITLE
Give `defaultLibrary` semantic token modifier to items from standard library

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#8999]
This should apply to all items from the `std`, `core`, `alloc`, `test` and `proc_macro` crates. Should these items also be given the `library` modifier? I’d argue they should, since they still are from a crate other than the current one.

**Comment by Veykril** [comment]
Ye I agree, I think they should still be tagged with `library` since that still affects code when viewing the std source for example in which case the std source is only tagged as `defaultLibrary` and not `library`.

Also I could swear we had an issue for tagging std things with semantic highlighting tokens but I can't find it anymore 🤔.

**Comment by Veykril** [comment]
So to do this we want to fetch the std/core/... crates via FamousDefs here https://github.com/rust-analyzer/rust-analyzer/blob/bb1c7fc0cfe24a8477d943faa932992b9cd48957/crates/ide_db/src/helpers.rs#L82-L88 and compare those crates with the crate of the definition like we do for the `library` modifier then to determine whether they should be tagged with `defaultLibrary` or not.

**Comment by lhvy** [comment]
Would it be ok if I work on this?

**Comment by lnicola** [comment]
Sure!
