### ISSUE TITLE
Annoying extra space between struct definition and #derive-block

### ISSUE THREAD

**Issue by carlg0ransson** [rust-analyzer/rust-analyzer#9116]
After updating to the latest version, an extra line of space seems to be added between structs and their "derive-blocks". (Sorry I don't know the proper technical term). Please see the screenshot of what I mean. Previously this was not the behaviour.

Note that turning off the Implementations action via the settings doesn't seem to remove the space either.

![Skärmavbild 2021-06-02 kl  20 55 47](https://user-images.githubusercontent.com/16756570/120537101-2f189780-c3e5-11eb-8321-265bed7cb702.png)

**Comment by Veykril** [comment]
Basically the code lenses(the `3 implementations` here) previously were above attributes/docs of structs and other adts while being right above the signature of functions. We moved them to be below the attributes and docs for all things now because this way they are closer to the thing they are annotating(them being above really large docs isn't really that helpful after all).

For me turning the corresponding lenses off in the settings does get rid of the "blank" line for me though.

**Comment by carlg0ransson** [comment]
Oh I see - yeah I must have mistakenly not tried the combination of turning off both Implementations action & Implementations lens. With both off, the space is gone. Thanks for the very quick reply :)

**Comment by Veykril** [comment]
Oh I didn't notice you disabled the hover action. Disabling only the lens setting should suffice, the hover action is for the implementation links inside the hover pop up.
