### ISSUE TITLE
Any plan about caching on disk to speed up the loading upon initialization?

### ISSUE THREAD

**Issue by xymeng16** [rust-analyzer/rust-analyzer#9188]
Hi all,

I've read some issues related to caching but it is still not implemented in rust-analyzer. I wonder would it be a potential feature to be implemented? Or caching the previous states on disk does not conform to the designing philosophy of rust-analyzer? (If so I may implement it for myself to use, lol:D)

Thanks!

**Comment by lnicola** [comment]
This was discussed a bit in https://github.com/rust-analyzer/rust-analyzer/issues/1650. TL;DR persisting the analysis data would be really nice, but it's hard to implement and doesn't help when opening a project for the first time. So it kind of makes sense to optimize what we have before adding persistence, because then we'll be less likely to go back and work on it.

**Comment by flodiebold** [comment]
There's also #4712, of which I think we can count this as a duplicate.
