### ISSUE TITLE
Switch from `log` to `tracing`

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#9274]
We currently use `log` for logging, but we also pull in `tracing` through Chalk, and the nesting structure of `tracing` might be a good fit for us anyway. So, we should switch to `tracing` everywhere.

**Comment by matklad** [comment]
One obvious question is whether we should also switch out profiling infra to tracing. I’ve looked into that somewhat closely, and my conclusion is that a home-grown hierarchical profiling is better.

👍 for replacing log in particular with tracing!

**Comment by dzvon** [comment]
Hi, I'm Dezhi :D.

Is there anyone doing this? If not, I'd like to give it a try.

**Comment by lnicola** [comment]
It's yours!

**Comment by dzvon** [comment]
Okay, thank you! @lnicola 

By the way, any special considerations?

**Comment by lnicola** [comment]
Not from my side. Replacing the macros (as in https://docs.rs/tracing/0.1.26/tracing/#for-log-users) should work. If we want anything fancier, we get cover that in another PR.

**Comment by flodiebold** [comment]
We might also use https://crates.io/crates/tracing-log to avoid having to move over everything at once. That way, we could e.g. go crate by crate.

**Comment by flodiebold** [comment]
Oh, and

>  I’ve looked into that somewhat closely, and my conclusion is that a home-grown hierarchical profiling is better.

Could you elaborate a bit? If that's based on specific missing features, maybe we should let the `tracing` maintainers know?

**Comment by matklad** [comment]
cc @davidbarsky

We discussed this a while back: https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/tracing.20in.20chalk/near/184520775

I've also tried writing a simple hierachical consumer some time ago: https://github.com/near/nearcore/blob/793178eddc29727f88ac61f6241d713e2748154d/runtime/near-vm-runner-standalone/src/tracing_timings.rs

My conclusion is that expressing our `hprof` in tracing would be possible, but awkward, for two reasons:

*First*, tracing has some head-scratching APIs:

```rust
impl<S> Layer<S> for Timings
where
    S: Subscriber + for<'span> LookupSpan<'span> + fmt::Debug,
{
```

I think I understand why a reusable library needs these kinds of bounds, but I quite like it that in `hprof` we mostly avoid such heavy-duty type artillery, and just write the code that does stuff. This is beneficial because, during performance investigations, I occasionally patch `hprof` to do something ad-hoc data processing. As an example, if we do #9309, then sticking allocator's RAII guard into `ProfileSpan` would be a trivial change, while adding that to `Subscriber`'s infra would require more digging around.

*Second*, to me it seems that tracing is biased towards emitting events, and it's a bit hard (but not impossible), to write aggregating subscribers. hprof is aggregating in a sense that it prints to terminal the whole stack once the top span is popped, and it sums all fast spans. That can be implemented on top of tracing, but it will require extra code in comparison to what we have today.

*Third*, tracing has some extra runtime behaviors -- there will be RwLock and DynMap in the call stack. I don't think this'll cause any specific issues, but, as a rule of thumb, I prefer to use, at runtime, only stuff that's strictly necessary, as a way to keep overall complexity low.

All that being said, if we are using tracing anyway, the overall complexity might go down if we get rid of home-grown profiling infra which, admittedly, at the core does exactly the same thing as tracing. So, if one day someone sends a PR replacing hprof with a tracing based impl, preserving the API and the behavior, I think there will be no reason to reject such a PR.

**Comment by davidbarsky** [comment]
Thanks for cc'ing me, and sorry for the delay and the relatively poor editing! I'll try to address each point.

> First, tracing has some head-scratching APIs:
> 
> ```rust
> impl<S> Layer<S> for Timings
> where
>     S: Subscriber + for<'span> LookupSpan<'span> + fmt::Debug,
> {
> ```

I agree, that signature isn't the nicest looking one. For posterity, I'll explain what each portion represents.
- The `Layer` allows customers to decouple themselves from the underlying span storage system through `S`, which is bound to the `Subscriber` trait. In practice, this has allowed folks to write layers that work in `no_std` + `alloc` environments _and_ `std` environments. At my former job at Amazon, some folks wrote their own subscriber atop of https://docs.rs/sharded-slab (which [`tracing_subscriber::Registry`](https://docs.rs/tracing-subscriber/0.2.18/tracing_subscriber/struct.Registry.html) is built atop of) that _wasn't_ generic over what data is stored within subscriber and saw a non-trivial boost in performance for a pretty low implementation cost. If you don't plan to targeting other environments, hard-coding the layer to use `tracing_subscriber::Registry` (or your own subscriber, optimized for the data that _you_ want to store!) is perfectly acceptable.
- `for<'span> LookupSpan<'span>` is a fancy way of saying "please let me query the data that may-or-may-not be stored in the subscriber".

> Second, to me it seems that tracing is biased towards emitting events, and it's a bit hard (but not impossible), to write aggregating subscribers. 

Not especially! Aggregating layers/subscribers are decently easy to write with `tracing`. [`tracing_subscriber::fmt::Subscriber`](https://docs.rs/tracing-subscriber/0.2.18/tracing_subscriber/fmt/struct.Subscriber.html) _is_ optimized around emitting events, but there's no fundamental reason that the `Layer` trait implementation can't record timing/aggregated data. That being said, I don't _personally_ find [the timing layer](https://github.com/near/nearcore/blob/793178eddc29727f88ac61f6241d713e2748154d/runtime/near-vm-runner-standalone/src/tracing_timings.rs) you wrote to be awkward, but I'm probably biased. I'm also sure that the state of the world in tracing can _absolutely_ be improved, to be clear! I suspect that our current approach of indexing on a per-span basis introduces a degree of mental anchoring that might be somewhat counter-productive—I'd love to learn as to what you find a bit awkward in tracing's current model.

 > Third, tracing has some extra runtime behaviors -- there will be RwLock and DynMap in the call stack. I don't think this'll cause any specific issues, but, as a rule of thumb, I prefer to use, at runtime, only stuff that's strictly necessary, as a way to keep overall complexity low.

I get your hesitation. If you're to create your own Subscriber/`Registry`-like storage system tailored to storing the data [`sharded_slab::Pool`](https://docs.rs/sharded-slab/0.1.1/sharded_slab/struct.Pool.html) or [`sharded_slab::Slab`](https://docs.rs/sharded-slab/0.1.1/sharded_slab/struct.Slab.html), you _should_ be able to avoid the `DynMap` in the callstack. You won't be able to avoid the `RwLock`, but it should be _barely_ noticeable, as the `sharded-slab` is implemented using a "lock-free-but-with-locks" approach: https://twitter.com/mycoliza/status/1146831059796934656.

**Comment by lnicola** [comment]
CC #9432

**Comment by lnicola** [comment]
@dzvon hey, did you give this a try? Are you still planning to work on it?

**Comment by dzvon** [comment]
@lnicola Sorry for not submitting the PR until now. It seems some CI checks run into trouble, I'll fix it later.
