### ISSUE TITLE
x.py in rust-lang/rust does not like being called by rust-analyzer

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#9349]
```
[ERROR rust_analyzer::reload] failed to switch build data: cargo check failed:
error: failed to run custom build command for `bootstrap v0.0.0 (C:\Users\Joshua Nelson\src\rust\src\bootstrap)`

Caused by:
  process didn't exit successfully: `c:\Users\Joshua Nelson\src\rust\target\debug\build\bootstrap-4864c5f723b632c4\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rustc-env=BUILD_TRIPLE=x86_64-pc-windows-msvc

  --- stderr
  thread 'main' panicked at 'assertion failed: rustc.is_absolute()', src\bootstrap\build.rs:20:5
```

**Comment by jyn514** [comment]
It looks like VSCode is calling it with the env variable RUSTC set to `rustc`. I don't know why it would do that, bootstrap is not built with any rustc on the host PATH.

**Comment by bjorn3** [comment]
`RUSTC_WRAPPER` is set to point to rust-analyzer. This will cause cargo to call `rust-analyzer rustc` instead of `$RUSTC` and not `rust-analyzer $RUSTC` I think. Rust-analyzer simply uses the second argument as command to run. (`rustc` in this case) The `RUSTC_WRAPPER` is part of the code that allows building proc macros and running build scripts and getting their output (generated code, env vars, ...) without doing a full `cargo check` run. This was implemented in https://github.com/rust-analyzer/rust-analyzer/pull/8476.

**Comment by flodiebold** [comment]
This can be disabled with `rust-analyzer.cargo.useRustcWrapperForBuildScripts`, but I don't think we should be running it at all if you've got proc macros and build scripts disabled :thinking:

**Comment by flodiebold** [comment]
@jyn514 do you have `runBuildScripts` and `procMacros` disabled like in the [suggested settings](https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc)? Note that the defaults for this changed somewhat recently.

**Comment by jyn514** [comment]
Thanks! That worked around the issue, and now I just have the cyclic deps error (https://github.com/rust-analyzer/rust-analyzer/issues/8330). I suspect this is a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/9201 like you said.
