### ISSUE TITLE
Stack overflow and server crash on unclosed macro invocation

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#9358]
```rs
macro_rules! always {
    ($cond:expr) => {
        always!($cond, "assertion failed: {}", stringify!($cond))
    };

    ($cond:expr, $fmt:literal $($arg:tt)*) => {{
        let cond = $cond;
        if cfg!(debug_assertions) || $crate::__FORCE {
            assert!(cond, $fmt $($arg)*);
        }
        if !cond {
        }
        cond
    }};
}

fn f() {
    always!(comment_token.kind() != SyntaxKind::COMMENT
}
```

**Comment by matklad** [comment]
Minimized somewhat:

This kills parser:

```rust
macro_rules! m {
    ($cond:expr) => { m!($cond, stringify!($cond)) };
    ($cond:expr, $($arg:tt)*) => { $cond };
}

fn f() { m!( }
```

This kills expr collector:

```rust
macro_rules! m {
    ($cond:expr) => { m!($cond, "") };
    ($cond:expr, $($arg:tt)*) => { $cond };
}

fn f() { m!( }
```

**Comment by matklad** [comment]
Minimized more (just a bunch of nested parens): 

```rust
#[test]
fn parse_smoke_test() {
    let n = 100_000;
    let l = "(".repeat(n);
    let r = ")".repeat(n);
    let code = &format!("fn main() {{ {}{} }}", l, r);
    let parse = SourceFile::parse(code);
    assert!(parse.ok().is_ok());
}
```

https://gist.github.com/matklad/0dc92e3e5df2351a5a9c338adeef7bc4

Unsurprisingly, rustc stack overflows on this example as well. One more case where command line compiler can die while the IDE needs to be robust. While investigating this issue I've noticed that it makes `bat` hand as well.

Heartwarmingly, IntelliJ Rust does display this file successfully. Less heartwarmingly, editing this file freezes IntelliJ UI.

**Comment by matklad** [comment]
Figured out what's happening. We have two limits for run-away macro exapnsion -- breadth and depth. In this case, the expansion creates code as `( -> (( -> (((( -> ((((((((` -- ie, it hits the breadth limit. But, when we parse the result, the parser seems this as a deep, rather than broad code. 

Fixes:

* add a depth limit to the parser 
* don't try to expand macros whose argument has an unclosed parenthesis.

**Comment by flodiebold** [comment]
> * don't try to expand macros whose argument has an unclosed parenthesis.

Could we instead just add the closing parenthesis?

**Comment by matklad** [comment]
Good question! I was actually thinking about moving in the opposite direcion, and checking that the argument has all parens balanced (and not just the outer ones). The idea being to not expand obviously broken macros, rather than to try to recover thing. 

Thinking about this more, I realised there's a sound (if not always optimal) strategy to recover from unballanced parethesis. 

Consider this example:

```rust
pub(crate) fn status(db: &RootDatabase, file_id: Option<FileId>) -> String {
    let mut buf = String::new();
    format_to!(buf, "{}\n", FileTextQuery.in_db(db).entries::<FilesStats>() // <- unclosed paren
    format_to!(buf, "{}\n", LibrarySymbolsQuery.in_db(db).entries::<LibrarySymbolsStats>());
```

Here, the `)` is missing, so parser should decide when to finish the macro call. One consideration is that the macro call finishes at *some* point, and all the future tokens belong outside of the call. A way to approximate that is to say that the call finishes *immediately* after an unclosed parenthesis. That way, we'll wrongly skip over some of the real arguments, but (provided that parser recovery is any good) we'll correctly recognize the tail that's outside of macro invocation.

**Comment by matklad** [comment]
To clarify our (and intellij rust) strategy is to eat tokens until `}` is seen, exactly the oppostie to what I am describing here. 

I think that maybe we want to greedy eat token for function calls, but eagerly stop right after `!(` for macro calls?
