### ISSUE TITLE
Placing the cursor on `self` in a function without `self` argument highlights the entire file

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#9365]
![screenshot-2021-06-21-22:50:01](https://user-images.githubusercontent.com/1786438/122826171-1c59fa00-d2e3-11eb-9ee0-04abc704e6c1.png)

**Comment by matklad** [comment]
Annoying enough to be a broken window :-)

this happens because self is then considered to refer to the current module.

**Comment by Veykril** [comment]
So basically we want to just highlight the identifier instead of the module? If yes should this be for modules in general or just `self`?

**Comment by jonas-schievink** [comment]
I think a good middle-ground would be to highlight only the module's name in its declaration, instead of the whole module.

**Comment by Veykril** [comment]
Well we already do that for inline modules,
![image](https://user-images.githubusercontent.com/3757771/122955706-9db39a00-d380-11eb-87b6-f0d3d6281cc6.png)
the problem with out of line modules is that we can't really do that there since the declaration lies in another file. In this case we never set a `focus` range(since it doesn't exist for that file) which causes the entire module to be lit up. See 
https://github.com/rust-analyzer/rust-analyzer/blob/4e2ec914f4b9609d162c3fd1776e8d293428fe5a/crates/ide/src/display/navigation_target.rs#L269-L283

I think a good solution would be to just filter out all elements without focus ranges in the `document_highlight` handler.

**Comment by matklad** [comment]
We might want to move the highlighting logic from rust-analyzer/handlers.rs to a method of Analysis. Re-using Analysis methods to implement different features in handlers is a bit of an anti-pattern.

**Comment by matklad** [comment]
>is a bit of an anti-pattern.

To expand of this, it is yet another example of my favorite story -- each abstraction has two sides, implementor's side, and user's side. It's very easy to use part of the user's side when implementing an abstraction, and that leads to some non-trivial misery. 

In this case, `Analysis::find_all_refs` is a user-facing thing, which was used to implement another user-facing thing -- document  highlights. The problem here that it sort-of works, but breaks around the edges, and, whats worse, immediately sends you to thinking about how to change `NavigationTarget` here, while really NavigationTargets have nothing to do with hightlighting identifiers.

**Comment by Veykril** [comment]
Ye, I rebuild this on top of the `search` module now but there is still the problem of getting the identifier range of the definition. Currently we only have `NavigationTarget` for that from what I know.
