### ISSUE TITLE
Rerun analysis on all dirty files in the workspace?

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#9439]
I was running into some type errors from Rust-Analyzer (missing fields and a missing associated function) that cargo check did not report. I was used to saving the file (in the case, a module using a type from a different crate local to the same workspace) and this would "fix" the diagnostics in RA. However, I now noticed that saving the "using" file is not enough, and I had to save the "definition" file in order for RA to notice the updated type definitions.

It would be nice if, on file save, RA would re-evaluate all changed files in the workspace. This is particularly relevant because of things like changing branches with Git, where a lot of files change at the same time.

This seems to be a recent change in behavior, from maybe a week ago at most.

**Comment by flodiebold** [comment]
I don't think anything about this changed recently. Can you provide more detailed reproduction steps?

Note that there are different things here: RA's own analysis, which runs immediately even on unsaved files, and `cargo check`, which only runs on saved files, whenever you save one. Also, changing branches with git is still a slightly different case because it relies on the editor watching the files and reporting the changes to RA. Missing fields could be reported by RA's own analysis or by cargo check; missing associated functions currently can only come from cargo check. (The diagnostics say `rust-analyzer` or `rustc` depending on where the error comes from.)

**Comment by djc** [comment]
I don't have any detailed reproduction steps. :( I noticed this issue and it seemed to stick around for one or two days (throughout VS Code window reloads). But then I tried saving the defining file and it went away. I did have a screenshot which I uploaded to GitHub for the issue, but I'm not sure if I can recover that screenshot.

**Comment by flodiebold** [comment]
Without a reproduction, I don't think we can do much here :/
