### ISSUE TITLE
Generic argument type gets lost in completion

### ISSUE THREAD

**Issue by jakobhellermann** [rust-analyzer/rust-analyzer#9444]
Not sure if there is already an issue open for it, but in the following example
```rust
fn foo<T>(param: T) {}

fn main() {
  foo(<|>)
}
```
the type of `param` seems to get lost trying to display the expected types:

![image](https://user-images.githubusercontent.com/22177966/124154690-03e1a080-da96-11eb-9313-7ae3d0d3e20b.png)

Writing `fn foo(param: f32)` works as expected.

**Comment by flodiebold** [comment]
Well, this kind of is correct. If you wrote `foo::<f32>()`, you'd get `param: f32` as hint. Since you didn't specify the parameter, it has to be inferred, but there's not yet enough information to infer it. Showing `T` as the type would be kind of wrong since `T` isn't a valid type in this context, or it may even be a different type here if the function you're in also has a parameter `T`. Maybe there's something else we can display here though.

**Comment by jakobhellermann** [comment]
The way I found this was that I wanted to extend the `add_call_parenthesis` setting to handle cases like
```rust
fn accept_fn<F: Fn()>(f: F) {}

accept_fn(f<autocomplete>)
```
but the [expected_type](https://github.com/rust-analyzer/rust-analyzer/blob/3ae0c5911ab50ee209179ee4329b0551abe6fc48/crates/ide_completion/src/context.rs#L77) is `#error`. Do you know how I could get check whether the expected type would accept a function?

**Comment by flodiebold** [comment]
Ah well, that's the same issue I'm referring to in #8676 :sweat_smile: As I wrote there,

> This isn't completely trivial because it's not about the expected type, but about a trait bound on it. We should probably carry them over from type checking somehow; a simpler approach for now might be to only make it work if we're in a function parameter.

But as you noticed, it may actually not be easier for a function parameter, since the way we calculate the expected type there is by taking the type of the function expression :thinking: I don't really see an easy way to do this, unfortunately :confused:

**Comment by jakobhellermann** [comment]
Ah well I see, thank you. I'll close this then in favor of 8676.
