### ISSUE TITLE
Feature request: Convert to method assist

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#9616]
Hi! Today, I extracted some code from one function into a separate function and wanted that function to be a method. I hoped that after extracting the function, I could just "convert to method" to have RA generate an `impl` block for me and change the sole `foo: &Foo` argument of the function to `&self` (plus rewrite references to `foo`). Am I missing something or has this simply not come up as a helpful assist before (I couldn't find an existing issue)? :)

**Comment by Veykril** [comment]
You can rename the first param of a function to `self` if the function is in an impl block of the correct type, that will transform the parameter to the corresponding self param and fix up its usages, Though that doesn't fix up usages of the function *yet* unfortunately.

Otherwise no, there is no such assist yet.

**Comment by rylev** [comment]
This can be closed as it was implemented in #9804

**Comment by jplatte** [comment]
Not exactly what I asked for, but actually a better solution (at least for my use cases)!
